### ISSUE TITLE
Upgrade Firebase databases to paid plan

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1001]
`webmaker-app-data` and `webmaker-app-dev` are both running on the free "hacker" plan. We need to add a credit card and upgrade to a paid plan.

/cc @simonwex

**Comment by simonwex** [comment]
I've got a support request with firebase for adding a credit card from an account that isn't the owner. If we can't do that, I'll just smash keys on your individual machines tomorrow.

**Comment by thisandagain** [comment]
Two new endpoints have been created and set-up with billing. We now need to update the environment.
