### ISSUE TITLE
Empty state for data view

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1008]
The "data" view currently doesn't have much of an empty state:
![screen shot 2015-02-10 at 8 19 01 pm](https://cloud.githubusercontent.com/assets/747641/6141954/6377748e-b162-11e4-93af-743a337e9848.png)

**Comment by vazquez** [comment]
R? @thisandagain [flagged!]

https://redpen.io/br12075ef8c7266b95

**Comment by thisandagain** [comment]
Verbose comment left in redpen. :wink:

**Comment by vazquez** [comment]
I agree on removing Tuckers the Toucan. :bird: 

I have two options:

Version A: https://redpen.io/br12075ef8c7266b95
Version B: https://redpen.io/eh9c3e1fb5e6ea6960

R? @thisandagain [flagged!]

**Comment by thisandagain** [comment]
Solid. R+ on version A. :hatching_chick:

**Comment by vazquez** [comment]
Final design: https://redpen.io/br12075ef8c7266b95
2 assets are needed for this view. They are available on Google Drive (WMA > GUI > Icons)
counter-grey.svg
submit-grey.svg
