### ISSUE TITLE
Data submission failing on Firefox OS

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1010]
```
Error: Firebase.push failed: first argument contains undefined in property 'dataBlocks.0.label' index.js:4416:47
```

![screen shot 2015-02-10 at 8 48 41 pm](https://cloud.githubusercontent.com/assets/747641/6142212/9916340a-b166-11e4-890f-7c269b824aea.png)

**Comment by errietta** [comment]
@thisandagain R?
 [[flagged!]](http://plzkthx.herokuapp.com)
