### ISSUE TITLE
Empty state for profile view

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1027]
Our current empty state is ... :neckbeard: 
![screen shot 2015-02-11 at 2 02 48 pm](https://cloud.githubusercontent.com/assets/747641/6157500/bb75be18-b1f6-11e4-8f98-814fafb3e8c1.png)

**Comment by vazquez** [comment]
But the one we have looks great already!

![giphy](https://cloud.githubusercontent.com/assets/1119821/6157561/5a15b83e-b210-11e4-8a15-41a5a7bdb1b2.gif)

**Comment by vazquez** [comment]
What do you think @thisandagain? [flagged!]

https://redpen.io/jq2b67512f63652fd4

**Comment by thisandagain** [comment]
Perfect. Thanks @vazquez . R+ :ghost:

**Comment by vazquez** [comment]
The down arrow is available on Google Drive.

WMA > GUI > Icons > arrow-fade-down.svg
