### ISSUE TITLE
Share button results in a lovely white screen

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-app#1035]
hitting the "share" option from the side menu results in a blank screen that requires you force-quit the app. Not the best ux. Or, so people claim.

**Comment by k88hudson** [comment]
:ghost: :ghost: :ghost: :ghost: :ghost: :ghost: :ghost: :ghost:

**Comment by thisandagain** [comment]
To clarify, this is only when user is offline. @vazquez ideas for UX here? I'm thinking that we might want to CTA to let the user know that they need to connect to the internet or we could even disable the "Share" button when offline.

**Comment by vazquez** [comment]
1. We can disable the Share button
2. We can create an empty view (similar to empty data and empty profile) that says "You need to connect to the Internet to share your app" with a button that says "Try again" (or something similar) that would trigger the app to reload the view.

**Comment by davidascher** [comment]
I'm ok w/ disabling share when offline this week, but in the future, we
should have a "queue" that can let people initiative the share while
offline, and having it complete whenever the network shows up again (i.e.
we should file an issue on the future feature)

**Comment by k88hudson** [comment]
Hm, I'm not able to reproduce this. I tried creating an app, turning off network, and pressing share. I get an error message in the status bar below the menu, not a white screen – is there something else I need to do to trigger this error state?

**Comment by k88hudson** [comment]
@gesa @Pomax ^

**Comment by gesa** [comment]
I just set this to false: https://github.com/mozilla/webmaker-app/blob/master/lib/network.js#L7
