### ISSUE TITLE
Universal "Save" button should have disabled state

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#1046]
STR:

1. Add text block
2. First state we're seeing here is disabled state
3. Focus on a textarea (input) then it will be enabled state
4. You can save which is fine, but even if you are in an error state you still can save which is not the behaviour I think it suppose to be.

![screen shot 2015-02-11 at 19 58 44](https://cloud.githubusercontent.com/assets/4368149/6159792/a749fa62-b228-11e4-875c-43871cbe6b55.png)
![screen shot 2015-02-11 at 19 58 50](https://cloud.githubusercontent.com/assets/4368149/6159791/a748340c-b228-11e4-8616-edf67e53d0e8.png)
![screen shot 2015-02-11 at 19 58 53](https://cloud.githubusercontent.com/assets/4368149/6159793/a74a3c5c-b228-11e4-9a72-a20785e20b0b.png)

**Comment by alicoding** [comment]
@thisandagain @Pomax was this intentional? since the ticket is closed here https://github.com/mozilla/webmaker-app/issues/834

**Comment by thisandagain** [comment]
Good catch!

**Comment by Pomax** [comment]
yeah I mostly went with "click" because there does not seem to be a rigid enforcement of what qualifies as "should be submittable" and "should not be submittable". However, if we do have that in place we can make sure the save button gets disabled if there's an non-permited state.

**Comment by alicoding** [comment]
@Pomax from what I gathered from @vazquez we want to disable the button if any of this is met:

1. An empty textarea field
2. An empty input field
3. An invalid format for number field e.g. input is a character
4. Not selected color

Obviously they are not going to be all in one block but if number 1,2,3 are all in the same block which is possible in this case then we will have to make sure they are all filled and validated (for number 3).

**Comment by Pomax** [comment]
Filing #1135 to solve this properly, because there is no quick win here: editors right now don't even know what consistutes a "legal" state other than through vue magic, let alone having a nice DRY function they can trigger when they're in a bad state. This is a considerable amount of work to do right.

Instead, we're going to simply make the "save" button always enabled when editing bricks, for now. It's not "correct" but it'll feel less broken.
