### ISSUE TITLE
Hide the hamburger on apps that aren't ours

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1049]
![](http://media.giphy.com/media/40xTvlTunvUBO/giphy.gif)
![](http://media.giphy.com/media/eEdcid30jAfqE/giphy.gif)

**Comment by k88hudson** [comment]
On apps that are linked from the discovery page, there should only be a back button, not a hamburglar

**Comment by gvn** [comment]
I approve this bug description.

![giphy](https://cloud.githubusercontent.com/assets/206379/6160991/249b6f78-b21f-11e4-935f-ddb266a40831.gif)

**Comment by thisandagain** [comment]
@alicoding can you take this? This is one of the last critical items remaining for today.

**Comment by thisandagain** [comment]
@alicoding also... can you please add more :hamburger: ?

**Comment by thisandagain** [comment]
Reassigned to @Pomax
