### ISSUE TITLE
Share - Replace "share" view with native sharing flow

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1051]
After evaluating the existing share flow, it's become clear that the way in which [cordova](http://docs.phonegap.com/en/edge/cordova_contacts_contacts.md.html) handles contacts makes it difficult to produce a performant and safe implementation of the contacts selector and share view as spec'd. The existing implementation can cause devices to crash and in many cases causes performance of the app to slow significantly for users who have more than ~300 contacts.

#### Proposed Solution
- [x] Replace the current "share" view with a flow similar to the current SMS component that simply launches the device's native SMS app with a message pre-populated.
- [x] Redesign the publishing loading indicator to happen within the make view itself and redirect to the SMS flow `onSuccess`.
- [x] Present a modal `onFailure` for publishing

#### Next Steps
- @k88hudson Will remove the existing share view and add a callback for when publishing is complete
- @thisandagain Will add the new SMS flow

#### Replaces
#1026
#874

/cc @k88hudson @cadecairos @simonwex

**Comment by thisandagain** [comment]
https://github.com/k88hudson/webmaker-app/pull/1

**Comment by thisandagain** [comment]
https://github.com/mozilla/webmaker-app-cordova/pull/26

**Comment by simonwex** [comment]
@thisandagain, @k88hudson is there a bug filed against Cordova? Link?

**Comment by thisandagain** [comment]
Couple related issues:
https://issues.apache.org/jira/browse/CB-8395?jql=project%20%3D%20CB%20AND%20component%20%3D%20%22Plugin%20Contacts%22%20ORDER%20BY%20updated%20DESC%2C%20priority%20DESC%2C%20created%20ASC
https://issues.apache.org/jira/browse/CB-5769
https://issues.apache.org/jira/browse/CB-8290

No issue(s) that I can find in regards to the performance / interface problems.
