### ISSUE TITLE
Can't scroll while looking at or building apps on FFOS 2.1

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1059]
- Just installed as packaged app on FFOS 2.1 (34) through WebIDE.
- Clicked on "Create Survey"
- Viewed app, but couldn't scroll
- Clicked "Start building"
- Tried to edit app, but couldn't scroll
- Clicked on a pencil button for a component near bottom of screen, finally scrolled automatically

**Comment by secretrobotron** [comment]
Other functions seem to work fine, e.g. side menu button

**Comment by k88hudson** [comment]
This is definitely a problem with your firefoxos build, @pomax was seeing this as well. Installing a stable version of 2.1 should fix this. @pomax can you link to the exact image?

**Comment by thisandagain** [comment]
It looks like this is fixed in nightly for 2.1:
https://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/latest-mozilla-b2g34_v2_1-flame-kk/

**Comment by secretrobotron** [comment]
:+1: works when using the one labeled `a2`, but not the one built most recently.
Any idea why? That build's timestamp is from October. Are we relying on a build from months ago?
