### ISSUE TITLE
"+" sign on add new block is misplaced

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#1060]
![screen shot 2015-02-12 at 13 13 08](https://cloud.githubusercontent.com/assets/4368149/6173857/06bbe024-b2b9-11e4-850d-720498b9a6b1.png)

**Comment by k88hudson** [comment]
@alicoding is it ok if @gesa takes this one?

**Comment by alicoding** [comment]
Sure thing! I didn't start on it yet.
