### ISSUE TITLE
Regression: Title doesn't show up (in markup) on detail view

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker-app#1070]
*OS:* ALL
*Browser:* ALL
*Screenshot:* ![](http://snaps.akibraun.com/diu11.png)

**Repro Steps:**
1. In profile OR discovery view, tap any app to see its detail view

**Expected:** Title renders somewhere on page (presumably in that top nav bar)
**Actual:** No title anywhere!

**Comment by Pomax** [comment]
broke in 3198dc7f31474a89daa15385c68d842522b91af4
