### ISSUE TITLE
Published view header is not centered

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1072]
You can test this locally at `localhost:8080/publish-assets`

![image](https://cloud.githubusercontent.com/assets/1455535/6177606/e26a6bec-b2bc-11e4-84c1-674050e7c15b.png)

**Comment by gesa** [comment]
shoot.
![screen shot 2015-02-12 at 14 26 11](https://cloud.githubusercontent.com/assets/782056/6178371/1cc916b6-b2c3-11e4-8186-68a518b222a2.png)

```js
TypeError: json is undefined
```
From /publish/index.js:30

**Comment by gesa** [comment]
@k88hudson can I get clearer STR?

**Comment by davidascher** [comment]
(not the steps that @k88hudson was using, but for me: make an app, share,
send by email, get a URL, open it in your favorite browser.)

**Comment by gesa** [comment]
thanks @davidascher !
