### ISSUE TITLE
Preview view of a template still feels too much like the real thing

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1076]
Even though I know better in theory, I found myself doing things like pushing on the counter buttons in the "Promote your business" template even before getting in the editor mode.

I suspect the current use of margins to indicate that it's "not really the app" but a read-only view of that app, is too subtle.

@thisandagain was suggesting desaturation, a phone-like frame, or some other design treatment.

**Comment by vazquez** [comment]
What about something like this? http://invis.io/J2294VEDE

R? @thisandagain [flagged!]

**Comment by thisandagain** [comment]
Too subtle IMO. It still reads an interactive to me.

**Comment by vazquez** [comment]
What about this treatment? http://invis.io/MU295JJ9S

R? @thisandagain [flagged!]

**Comment by thisandagain** [comment]
How would we pull this off in CSS in a performant way?

**Comment by thisandagain** [comment]
@gesa @gavinsharp ^^

**Comment by gesa** [comment]
Something like this maybe.
```css
#preview {
  -webkit-filter: grayscale(100%);
  filter: grayscale(100%); 
}
```

**Comment by gavinsharp** [comment]
@thisandagain you've got your mozillian "Gavin S"s confused - you want @gvn

**Comment by gvn** [comment]
/me shakes fist at Android...

http://caniuse.com/#feat=css-filters

**Comment by gvn** [comment]
I can't think of a sane/simple way to desaturate an entire block of content. Also, FWIW, desaturation doesn't mean much if you're color blind. :wink:

**Comment by vazquez** [comment]
I tested against colour blindness and we are good with Presbyopia and Deuteranomaly, the two most common types of blindness. One can tell the difference between the desaturated and full-colour versions.

**Comment by gvn** [comment]
I was thinking specifically Monochromacy, but it is far less common! :+1:

**Comment by gesa** [comment]
@thisandagain To answer your question, basically the whole internet says you can't. I went off in the weeds on this one and found nothing that suits our needs. There are a couple of javascript libs that will grayscale an image, but not html elements.

**Comment by vazquez** [comment]
Thanks @gesa and @gvn for your investigation! :shipit:

We are thinking of an alternate approach.

**Comment by vazquez** [comment]
Okay! This is what we're doing:

http://invis.io/MU295JJ9S

1. We're adding a banner banner that says "Preview" on all Preview views
2.  We are reducing the opacity of all interactive elements inside of the preview (counters, buttons, etc) to 50%
3. If user taps anywhere in the Preview, we send them to the "Open" view
4. On tap of the preview, we show a "pressed" state of the entire #preview <div>  

This is ready for implementation! :tractor:
