### ISSUE TITLE
I'd love some transitions between screens

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1077]
Specifically:

 - transitioning from the initial list of templates to the 'preview' pane feels like it could easily be made smoother.
 - the interstitial w/ the spinning squares between preview and editor doesn't make sense - as a user, I expect that interstitial to only be in very rare occasions like initial load, or maybe "wait for network to do a thing".

**Comment by davidascher** [comment]
Also: a nicer transition between inline editor and the actual property editor sheet.

**Comment by thisandagain** [comment]
Now using native Android activity transitions between views
