### ISSUE TITLE
In editor, when moving a brick, the inline brick editor shouldn't go away after a move

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1078]
STR: 
 - in editor, select the pencil on a brick
 - hit the move-down or move-up icon

Expected:
 - being able to keep moving the brick up or down

Actual:
 - inline editor goes away, and i have to find the brick again, hit the pencil again.

**Comment by gesa** [comment]
Unassigning this (at least for now) because no amount of debugging is helping me understand why the inlineEditor disappears the block.
