### ISSUE TITLE
The pencil in the editor view should not be semi-transparent

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1087]
The pencil over the house's blue background fades against the blue background.  I suspect it's because the icon is treated w/ a CSS opacity, rather than using per-pixel alpha in the PNG.

![2015-02-12 22 29 59](https://cloud.githubusercontent.com/assets/51278/6178450/d8214cd0-b2c3-11e4-951e-d30d63ee9f42.png)

**Comment by davidascher** [comment]
Or maybe it's just a perceptual effect, in which case maybe we need a bit of a light outline on the pencil?

**Comment by gesa** [comment]
It's def css, i *think* we're still using ionicons for that, but @vazquez may be working on swapping the ionicon for an svg

**Comment by vazquez** [comment]
There is an issue filed. I'll submit a patch for it tomorrow. #1036
