### ISSUE TITLE
Counter +/- buttons don't work in the editor

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1090]
STR:
 - open Promote your business template
 - tap on the +/- buttons in the counter bricks and see nothing happen
 - tap "Start building"
 - tap on the +/- buttons in the counter bricks and see nothing happen
 - hit pencil on that button, see the inline editor
 - tap on the +/- buttons in the counter bricks and see nothing happen

At least the last two seem like reasonable ways to set the default value.  Having to go to the property editor seems like unnecessary long path.

**Comment by thisandagain** [comment]
- Preview (Expected behavior)
    - Open Promote your business template
    - Tap on the +/- buttons in the counter bricks and see nothing happen
- Make (Bug – Should increment / decrement the count)
    - Tap "Start building"
    - Tap on the +/- buttons in the counter bricks and see nothing happen
- Edit State (Bug – Should behave normally (see "Make"))
    - Tap pencil on that button, see the inline editor
    - Tap on the +/- buttons in the counter bricks and see nothing happen

I disagree that changing the value in the edit state is a good way to change defaults as that seems like an inconsistent use of a GUI element.

**Comment by thisandagain** [comment]
Pulling in from side conversation in IRC:
I think the fundamental question for the 2nd and 3rd use cases outlined above is, "should an author be able to edit and submit a form on an app that they are editing?" I'm suggesting that the answer should be, "yes".
