### ISSUE TITLE
Update "add" view design

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1094]
On the face of it, the distinction seems myserious.

![2015-02-12 22 45 01](https://cloud.githubusercontent.com/assets/51278/6178654/df3d02e6-b2c5-11e4-94ce-b776a8e7ea33.png)

**Comment by vazquez** [comment]
The new design is here https://redpen.io/npe2cac1ee7dcf37e2, we just need to implement it.

**Comment by JordanTheriault** [comment]
I'd be happy to implement this design @thisandagain

**Comment by thisandagain** [comment]
Go for it @JordanTheriault !

**Comment by JordanTheriault** [comment]
![Looks like this has already been fixed.](https://cloud.githubusercontent.com/assets/5931078/6836352/788654f4-d317-11e4-800e-6cf9cbc37090.png)
