### ISSUE TITLE
Tapping on Featured/Newest shouldn't be a toggle

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1100]
STR:

 - tap on discover icon to go to discover sheet
 - tap on newest to switch to newest (good)
 - tap on newest toggles back to featured (bad)

Tapping on featured should move to featured *or stay on featured if that's the current tab*. Same for newest.

**Comment by gesa** [comment]
fiddlesticks. this is fixed in browser and on FFOS, but it does not appear to be fixed on my android device.
