### ISSUE TITLE
The tray is anemic

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1108]
The hamburger/side tray UX is reasonable, but it leaves one unsated.

I've filed somewhere else I think the fact that the word ``MENU` seems pointless.
- Back to My Apps is odd if I didn't get to the app through the My Apps view.  
- I'd expect it to just be `Back` and "do the right thing
- Maybe we can add an **About** link that reminds people what this app is, who made it, what it's for, etc.  Especially if we're willing to, within the beta period, drive people to a bug tracker, issue filer, something.

**Comment by gesa** [comment]
Do you think maybe linking that **‘About’** control to the /make/:id/detail page would make the most sense? Or are you looking for more info than that?

**Comment by davidascher** [comment]
I was quite unclear.  I meant an "About Webmaker" link (that would point to
a new yet-to-be-written sheet)

But, now that you mention it, having a sidebar link that would let me go to
the app's details page would be really useful (e.g. to get to the data).

I think we need to rethink a bit the relationship between the
template-not-built, the app being built, and the details-view-with-data.

**Comment by xmatthewx** [comment]
We should also rethink the relationship between the menu drawer and bottom navigation. Would be happy to do this next heartbeat.

**Comment by thisandagain** [comment]
Tracking in #1179
