### ISSUE TITLE
Long title causes screen overflow and pushes icon out

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker-app#1115]
*OS:* ALL
*Browser:* ALL
*Screenshot:* 
![screen shot 2015-02-12 at 15 42 21](https://cloud.githubusercontent.com/assets/782056/6179413/dddec10c-b2cd-11e4-93e6-41b4d1081604.png)

**Repro Steps:**
1. Name an app something really long
2. Go back to the profile view

**Expected:** Long title wraps or overflows with ellipses
**Actual:** Long title makes `<body>` wider than viewport, pushes icon offscreen

**Comment by davidascher** [comment]
Interesting: I see something related but different in android 5 and flame: #1104
