### ISSUE TITLE
Published apps need a couple of tweaks

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1116]
Apparently the foo title fix is pending, but two other things in this screenshot:

![screenshot 2015-02-12 15 48 07](https://cloud.githubusercontent.com/assets/51278/6179504/a88ed82e-b2ce-11e4-955b-3222b1081440.png)

- [x] The bottom text is grey on blue, we can do better
- [ ] the counter shows up/down arrows that are tiny and unneeded

**Comment by gesa** [comment]
I do believe the text at the bottom is resolved? 
![jneff](https://cloud.githubusercontent.com/assets/782056/6195153/3685f35e-b380-11e4-989f-016c1a614479.png)
(from <http://apps.mofodev.net/p/-JgnMMhfyXXaoLYJkibR/>)

**Comment by gesa** [comment]
The title is merged, the footer text is merged, and #1192 hides the spinners on number inputs.
