### ISSUE TITLE
counter button layout gets confused on touch

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1132]
![2015-02-13 01 20 36](https://cloud.githubusercontent.com/assets/51278/6180613/565ff0f2-b2dc-11e4-8302-6f1ce5cea1bc.png)

**Comment by davidascher** [comment]
- [ ] The orange ring shouldn't exist as far as I can tell
- [ ] the height of the number box should never change.

**Comment by alicoding** [comment]
Is that Lollipop?

**Comment by alicoding** [comment]
I've tried on 4.4 and 5.0 and still can't reproduce this. @davidascher Can you confirm if this is fixed on your end?
