### ISSUE TITLE
Handle data submission in offline state

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1133]
STR:
- go offline (added by @thisandagain)
- choose survey app
- tap start building
- scroll to the bottom
- tap the `Submit` button

Nothing happens (and no data is visible in the app's Data tab)

**Comment by thisandagain** [comment]
Need to design a offline / disabled state for the submit button.

**Comment by vazquez** [comment]
R? @thisandagain [flagged!] http://invis.io/M52963EFW

For this view, I added an info bar and disabled the Submit button.

**Comment by thisandagain** [comment]
Nice. How would this interact with the publish loading indicator?

**Comment by vazquez** [comment]
Correct me if I'm wrong (probably am), but this offline state indicator would only appear if the user is interacting, and not editing the app, right? Conversely, the publishing indicator would only appear if the user is editing, not interacting with the app.

**Comment by thisandagain** [comment]
I'm think specifically of the use case where a user is editing their app while offline. In that case, would the "share" button be disabled? If so, we just need to spec.

**Comment by vazquez** [comment]
Right! What about this? If the user is editing their app while offline and taps on share, we show the offline indicator instead of the publishing indicator.

http://invis.io/KT2972FQ3

**Comment by thisandagain** [comment]
Nice! That works for me ... I think the only tweak is that we'll want the "offline" copy to be more generic.

**Comment by vazquez** [comment]
On it

**Comment by vazquez** [comment]
Okay! I made the offline text generic.

http://invis.io/M52963EFW: The view for use case when a user is viewing an app. Offline state indicator and disabled Submit button.

http://invis.io/KT2972FQ3: The interaction for the use case where a user is editing their app while offline and tap on Share.

R? @thisandagain [flagged!]

**Comment by thisandagain** [comment]
R+ :boom: :shipit: 

One clarification for implementation: The offline state indicator should *only* be visible when a user is viewing an app that has form components: Input text, counter, submit. I would be ok with us using the presence of a submit button as the boolean.

**Comment by thisandagain** [comment]
@gesa Want to take a crack at this one?

**Comment by vazquez** [comment]
Yes! Great point @thisandagain 

![giphy](https://cloud.githubusercontent.com/assets/1119821/6257388/8efc0454-b78d-11e4-8ca6-c59876735555.gif)

**Comment by davidascher** [comment]
Some sharing actions don't actually require the internet on Android I
believe (i.e. "send to Firefox", "send to Dropbox", etc.  So I'm not 100%
sure blocking share on offline makes a lot of sense.  Blocking _publishing_
does.

**Comment by vazquez** [comment]
Hmm, but doesn't the app publish in order to share?

**Comment by thisandagain** [comment]
Yeah ... share === save === publish (get a URL for the thing)

**Comment by gesa** [comment]
Okay so this thread feels like it has a kind of unusual scope, so I'm just going to repeat it back to you all to make sure I understand what I'm implementing here.

1. build the "You need to be connected to the internet" banner
2. write the script to display that banner when a person is not connected to the internet, and taps the "submit" button of their form (or any form) in the make view **regardless of mode**
2. write the script to display that banner when a person is not connected to the internet and taps the "share" button

**Comment by vazquez** [comment]
Responding to your list in a list @gesa :)

1. Yes.
2. In addition to displaying the banner, the script also needs to lower the opacity of the submit button when the person is not connected to the Internet. The script will also check for the presence of a submit button as the boolean to show the banner.
3. Yes.

**Comment by gesa** [comment]
Fantastic, thank you so much @vazquez! :bee: :sparkles: :metal:
