### ISSUE TITLE
Add locale selector to developer menu

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1141]
especially in a context like MWC, where switching OS locale wouldn't be a good way to demo it.

**Comment by thisandagain** [comment]
By switching OS locale, though I suppose we could add an option to override in the developer / debug menu.

**Comment by davidascher** [comment]
To be clear: the problem w/ switching locale is if I switch my phone to Bangla the chance of my being able to find the path to switching it back to a language I can read w/o a factory reset are slim.

A hidden-developer-menu selector would be lovely.

**Comment by alicoding** [comment]
We are just adding it to the `Developer Health Check` is that correct?

**Comment by thisandagain** [comment]
Yup! Add drop-down menu on `/healthcheck`
