### ISSUE TITLE
Deployment is broken

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1144]
Right now deployment is broken because different build matrixes need to be set up for `install`, since ffos requires a different install/build step than android.

In the meantime, i've manually uploaded the current build to `webmaker-dist/staging/android/` and `webmaker-dist/staging/firefoxos/` on `mozilla-labs` and set the bitly links (mzl.la/android and mzl.la/ffos) to point to them. **If you need to upload a new version, please do it manually to those buckets**

cc @thisandagain @gvn

**Comment by thisandagain** [comment]
Thanks @k88hudson

**Comment by k88hudson** [comment]
This is now resolved
