### ISSUE TITLE
Implement MOFO style guide

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1154]
/cc @k88hudson @simonwex @gvn

**Comment by gesa** [comment]
YES. :+1: 

(will need to change `.editorconfig` as well)

**Comment by gvn** [comment]
Also `wma.sublime-project`

**Comment by gesa** [comment]
that reminds me! for future reference on new projects, there's an [editorconfig plugin for sublime](https://github.com/sindresorhus/editorconfig-sublime)

**Comment by gvn** [comment]
Starred! :star:

**Comment by simonwex** [comment]
I think the task should actually be, implement our style guide. It's installable as an npm module and then the appropriate linters can be referenced:
`npm install mofo-style --save-dev`

https://github.com/MozillaFoundation/javascript-style-guide

**Comment by thisandagain** [comment]
:+1:
