### ISSUE TITLE
Editing App title is really difficult

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1163]
Just tried to remix a couple different apps from the discover tab. When I went to change the title of each app, parts of the title would pop back into the textbox. Particularly the "My" and "App" bookends.

**Comment by secretrobotron** [comment]
The app icon is similarly difficult to change.

**Comment by gvn** [comment]
@secretrobotron Are you having this issue? I'm having problems reproducing it. I throttled to 50kbps to see if it was a latency issue, but I'm still able to edit as expected.

**Comment by secretrobotron** [comment]
Yeah, might be Android specific. I'm trying on my Galaxy S3 now; similar problems.

Just try remixing an app from the discover tab, and changing the title and icon a bunch. Eventually, it will start trying to replace your app name with blanks, or words you didn't type.

**Comment by gvn** [comment]
Couldn't repro with **Micromax A106 (v4.4.2)**. 

Will try another device once it charges...

**Comment by gvn** [comment]
@secretrobotron What version of Android are you running on the S3?

**Comment by gvn** [comment]
Ok, I think the problem was that data was being saved on every `keyup`. PR incoming...

**Comment by secretrobotron** [comment]
> What version of Android are you running on the S3?

4.4.2

I think I have some better STR, and an explanation:
1. Remix an app.
2. Click on the pencil to change its title.
3. Click inside the textbox to edit the title.
4. Change it a bit.
5. Quickly hit a new colour or the > button to change the app's icon.

You'll see the app name flip back and forth between what you changed it to, and what it was previously. My guess is that there's a sync issue between local & server, and before it's commited the change, it's in a weird state. In fact, as soon as I see one of these appended in the console, it's fine:

```
index.js:2748 [Store]  App changed
```

The reason this is so obvious on my phone is because the speed of the connection and/or the processor is slower than my desktop browser. So, it flip-flops a lot slower there.

Here's a video of me struggling with it a bunch (feel free to laugh): https://dl.dropboxusercontent.com/u/7054348/app%20name%20woes.mov

**Comment by gvn** [comment]
Ah, thanks for that! Yes, I think you'll have better luck with the PR I just opened... :clap:
