### ISSUE TITLE
Publishing errors on Android

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1164]
When I remix an app (after significant trouble in #1163), I have to publish twice. The first time, it says there's an error.

**Comment by Pomax** [comment]
when you say remix, do you mean after picking a template, hitting the "build" button, and then publishing (after zero or more customizations)?

**Comment by secretrobotron** [comment]
Not a template, but someone else's app. My guess is there's no difference
though.

**Comment by Pomax** [comment]
it changes the STR, which is what I need to work on the issue =)

plain publish seems to always work, moving on to editing someone else's app now.

**Comment by Pomax** [comment]
I don't get any errors on publish for remixed apps on Android, is there a specific device you're running into this with?

**Comment by Pomax** [comment]
I can't reproduce this bug on Android, nor FFOS, do you have specific STR that I can follow to reproduce this bug?

**Comment by secretrobotron** [comment]
Doesn't look like this is happening anymore. Could have been fixed incidentally last week.
