### ISSUE TITLE
"Webmaker" to "Appmaker" in manifest file

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker-app#1171]
When i install the app in Firefox OS its called "Webmaker" with the webmaker logo.

Should it not be called "Appmaker" and have the Appmaker logo ?

**Comment by thisandagain** [comment]
Nope... the brand is "Webmaker".

**Comment by scootergrisen** [comment]
So what if Popcorn is made for mobile. Would it then be one app called Webmaker with two tools in it ?
