### ISSUE TITLE
tabBar covers the last menu item (on desktop)

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker-app#1175]
Because the CSS id tabBar is using position: fixed; it sits above the bottom content so if you make the browser window small so you can scroll the tabBar will cover up half of the last item.

tabBar dont cover the last item when run in Firefox OS, both as an app and in the browser app.

Dont know why there is a difference.

**Comment by thisandagain** [comment]
Hey @scootergrisen could you attach some screenshots for reference?

**Comment by scootergrisen** [comment]
Strange i build it again and now i does not cover half the last item.
dont know what happened there.

But still the scrollbar is covered.
I made tabBar semitransparent so you can see the scrollbar though it.
http://netkoder.dk/test/billeder/billed0039.png

**Comment by alicoding** [comment]
This is the screenshot for the smallest screen size we support (320x480).

![screen shot 2015-02-20 at 08 56 29](https://cloud.githubusercontent.com/assets/4368149/6287307/84273c86-b8de-11e4-9723-f37d2bbaaf2d.png)

This is not a bug imo?

**Comment by alicoding** [comment]
Also this was the bug we fixed too https://github.com/mozilla/webmaker-app/pull/1162

**Comment by scootergrisen** [comment]
Should it look good in desktop browser to or does it not matter how it looks there ?

**Comment by alicoding** [comment]
@scootergrisen In browser should still looks good, but minimum size that we focus should not be smaller than 320x480 I believe, @thisandagain ?

**Comment by scootergrisen** [comment]
Check out these paddings:
```
#templates .template-cell .left, #templates .template-cell .middle, #templates .template-cell .right {
    float: none;
    width: auto;
    padding: 16px;
}
.cell .left, .cell .right {
    padding: 10px;
}
```
Also it depends on the string length whether at what with the vertical scrollbar will appear, so it might be nice in english, but in another locale with longer strings there might be a vertical scrollbar at 320 pixels width.

**Comment by alicoding** [comment]
I see what you mean now :+1: 

![screen shot 2015-02-20 at 10 32 01](https://cloud.githubusercontent.com/assets/4368149/6289110/c2f91bd4-b8eb-11e4-971f-a5b9eef76066.png)
