### ISSUE TITLE
Fix navigation flow / inconsistencies

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1179]
The current navigation flow & IA doesn't feel quite right as designed and has been a major sticking point during testing over the past week. We need to devise a short-term fix that can be implemented quickly to help reduce this friction.

**Comment by thisandagain** [comment]
Just look at this amazingly clear and communicative whiteboard drawing :sparkles: :wink: 

![img_1751](https://cloud.githubusercontent.com/assets/747641/6236225/750a83e0-b69d-11e4-9a19-62281859f6fa.JPG)

**Comment by thisandagain** [comment]
.... and progress! :smile: 
http://invis.io/XY28UASA2

/cc @davidascher

**Comment by davidascher** [comment]
Niiiice.

**Comment by xmatthewx** [comment]
Link doesn't work. Curious what you've drafted.

**Comment by thisandagain** [comment]
http://invis.io/RT28VT0G6

**Comment by vazquez** [comment]
We have two prototypes! :ghost: 

1. http://invis.io/4Y28VUMQM. This prototype addresses the navigation concerns we have been facing. By removing the royale with cheese, we were able to move actions one layer up allowing the view to become clearer.
2. http://invis.io/CJ28VW05Q. This prototype addresses the ambiguous "Has it saved?" question that a user goes through while interacting with the app. We show a checkmark when a change has been made in the app. After tapping save, the user has the opportunity to share their app.

These will be filed as two separate implementations.

R? @thisandagain @davidascher [flagged!]


This is the latest prototype we have.

**Comment by xmatthewx** [comment]
Nice. 

 - I like that you demoted the app title while editing. Do you access that via the settings gear?
 - I wonder if Delete doesn't belong on the Details/Admin view. Maybe below the share-in-gallery checkbox. Reduce icons in editor view.  
 - While I like the checkmark to publish, I'm not sure it would grab my attention. If someone hits the back arrow, can we offer a publish/share button on the Details/Admin view? On the level of Open and Remix?
 - I wonder if Publish, Share and Settings need to be on a fixed bar. What if they were at the top of the scrollable area in a nice big space dedicated to the the title and these actions?

**Comment by vazquez** [comment]
Thanks Matthew :)

To answer your 1st point. Yes, app name is accessed through the settings
gear. I will create a tap state to reflect this.

To answer your 2nd point, Andrew and I spoke about moving Delete to the
Preview view. I think I would just like to see how this iteration performs
with users before changing it.

To answer your 4th point (I wonder if Publish, Share and Settings need to
be on a fixed bar?), we want to stay in line with Android design guidelines
for consistency as well as to leverage off of learned behaviour. Another
reason is usability. If the user edits something at the bottom of the app
and wishes to publish, s/he would need to swipe all the way to the top to
tap on the Publish icon.

On Tuesday, February 17, 2015, matthew w <notifications@github.com> wrote:

> Nice.
>
>    - I like that you demoted the app title while editing. Do you access
>    that via the settings gear?
>    - I wonder if Delete doesn't belong on the Details/Admin view. Maybe
>    below the share-in-gallery checkbox. Reduce icons in editor view.
>     - While I like the checkmark to publish, I'm not sure it would grab
>    my attention. If someone hits the back arrow, can we offer a publish/share
>    button on the Details/Admin view? On the level of Open and Remix?
>    - I wonder if Publish, Share and Settings need to be on a fixed bar.
>    What if they were at the top of the scrollable area in a nice big space
>    dedicated to the the title and these actions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-app/issues/1179#issuecomment-74776608>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by xmatthewx** [comment]
All sounds good @vazquez. 

On the 4th point, take a look at the Play store. In this case you have a large colorful branded space that collapses into an efficient title bar. The install button vanishes unless you scroll back to the top. This could be a way to integrate the title and icon selector in the editor, without claiming too much fixed real estate. 

Regardless, you nicely dissolved the nav drawer. I'm excited to see how people respond to your cleaner flow through the app.

**Comment by vazquez** [comment]
I've updated the prototype. The biggest change is when you tap on "Open App". David had an excellent suggestion of placing a remix action, so that the user doesn't have to go back a view to remix.

I have also added a view when you tap on Settings.

http://invis.io/4Y28VUMQM

R? @thisandagain @davidascher  [flagged!]

**Comment by thisandagain** [comment]
Looks good. Thanks @vazquez R+

**Comment by thisandagain** [comment]
@gvn this is ready to go. Do you want to take this?

**Comment by vazquez** [comment]
@gvn I have updated the UI Toolkit with the new accent colour and the Navigation designs. I created a new Page called Header Navigation.

WMA > GUI > UI Toolkit.sketch

**Comment by gvn** [comment]
Sure thing. Grabbin' it.

**Comment by thisandagain** [comment]
```
Gavin Suntop
Senior Hamburger Removal Specialist aka "Hamburglar"
Hamburglar@mozillafoundation.org
```
![](http://media.giphy.com/media/ZomGmtAV9k1fa/giphy.gif)

**Comment by gvn** [comment]
Lol...putting a Service Now request for that email. :hamburger: :hammer:

**Comment by vazquez** [comment]
Hooray! Amazing!

**Comment by gvn** [comment]
:metal:
