### ISSUE TITLE
TypeError: obj is undefined

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker-app#1189]
*OS:* ALL
*Browser:* ALL
*Screenshot:* N/A

**Repro Steps:**
There are lots of ways to get here, I'll try to offer up a couple
1. Load webmaker app's home (make view)
2. Tap the "Share Community News" template
3. proceed to "start building"

**Expected:** Webmaker app generates a new make and loads the make view for it
**Actual:** `TypeError: obj is undefined` is thrown and the app gets stuck in the loading screen. back button does not change the view. basically have to force quit.

Less urgent STR:
1. Load the app by navigating directly to a make (either by entering in the URL for a make in the URL bar or by refreshing)

**Expected:** Webmaker app loads the make in question and shows the make view for it
**Actual:** `TypeError: obj is undefined` is thrown and the app gets stuck in the loading screen. back button does not change the view. basically have to force quit.

**Comment by gesa** [comment]
(in case it's not clear above, this is happening in the compiled app as well as the browser)

**Comment by alicoding** [comment]
I'm hitting this too.

**Comment by Pomax** [comment]
confirmed, hunting it down now.

**Comment by Pomax** [comment]
This seems caused by the changes introduced in https://github.com/mozilla/webmaker-app/issues/975, updating the templates.json to make sure all phone bricks have the new color property added
