### ISSUE TITLE
no internet found for the discovery view, despite having working wifi (FFOS)

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-app#1190]
on FFOS (2.1, wifi enabled, no sim card) firing up the latest webmaker-app and selecting "discover" reports that I have no internet, despite being able to load web pages in the browser upon testing.

**Comment by thisandagain** [comment]
Resolved in 2e2a7e015fd0aaad77f7974253c60560ab7d6902

**Comment by alicoding** [comment]
should we close this bug then? @thisandagain  or you want @Pomax to test and confirm before closing?

**Comment by thisandagain** [comment]
Fix hasn't landed yet: https://github.com/mozilla/webmaker-app/pull/1243

**Comment by alicoding** [comment]
Ah! My bad heh. I thought that was a commit message from master branch :P
