### ISSUE TITLE
Selection grabbers visible after switching screens

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1196]
Android 4.4.2, Samsung Galaxy S3

STR
1. Make an app that can submit data.
2. Open that app and submit some data.
3. Check out the data you submitted on the App Data tab.
4. Press+hold to bring about the native highlight selection functionality.
5. Switch to another screen.

![screenshot_2015-02-17-15-35-48](https://cloud.githubusercontent.com/assets/403231/6247664/343ed53e-b745-11e4-836b-1595ba72e3ea.png)

Not sure if this is because we're keeping those DOM elements on the page or if the OS is just confused.

**Comment by k88hudson** [comment]
I'm guessing this is related to the very old version problem. @secretrobotron can you confirm/close?

**Comment by secretrobotron** [comment]
Yeah, works fine after re-install. Yay!
