### ISSUE TITLE
Pressing native "back" button leads to error page eventually

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1197]
Android 4.4.2, Samsung Galaxy S3

After doing some app-making, I pushed the back button continually to see if I could get back to the OS easily. After a bunch of screens went by, the error page below appeared. It's probably the landing page, since pressing back once more does finally go back to the OS.

![screenshot_2015-02-17-15-37-11](https://cloud.githubusercontent.com/assets/403231/6247669/44686696-b745-11e4-9e1b-f400ceb72d34.png)

(Ignore the floating selection grabber things. Filed as a separate issue here: #1196)

**Comment by secretrobotron** [comment]
Update: this happens if you push the back button as your first action in the app.

**Comment by k88hudson** [comment]
I'm having trouble reproducing this -- mine goes back to the OS. Running 4.4.2 on a nexus 4

**Comment by k88hudson** [comment]
@secretrobotron can i borrow your phone to debug when you get a chance?

**Comment by k88hudson** [comment]
This ended up being because @secretrobotron had a super old version of the app. Problem solved!
