### ISSUE TITLE
it's very weird to have to pick "back to my apps" if I want to stop making and just get back to discover

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-app#1209]
Right now, once you started working on a thing, the only way to "get back to the main screen" is to touch the hamburger and pick "back to my apps", which might not make a lot of sense when a user doesn't want "their apps" but wants "the main view, where I can pick discover, make, and my apps".

**Comment by thisandagain** [comment]
Tracking fix in #1179
