### ISSUE TITLE
Refactor model.js

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-app#1214]
Mostly the https://github.com/mozilla/webmaker-app/blob/master/lib/model.js#L128 bit seems a little curious, it makes more sense to separate the "creation" from the "getting the instance" functionality, since the way it is now the function looks like it should be callable multiple times, with different options objects, but only the first ever request object will get bound.

```
var singletonModel = false;
module.exports = {
  initialise: function(options) {
    if (!singletonModel) {
      singletonModel = new Model(options);
    } else {
      // update the properties for this model
      singletonModel.rebind(options);
    }
  },
  getModel: function() {
   if (!singletonModel) {
    this.initialise({});
  }
  return singletonModel;
};
```

**Comment by thisandagain** [comment]
:+1:
