### ISSUE TITLE
`gulp test` is failing

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-app#1218]
Looks like a bunch of JS formatting issues with `lib/analytics.js`

**Comment by thisandagain** [comment]
Weird that is passed Travis. Hmm.

**Comment by adamlofting** [comment]
I hate to say "works for me", but `gulp test` is passing here. 

![screen shot 2015-02-19 at 09 26 51](https://cloud.githubusercontent.com/assets/1901816/6264212/77c0327e-b819-11e4-80b5-74b161b1917e.png)

What issues is it flagging up?

**Comment by gvn** [comment]
Here's what I get when I run `gulp lint` on master:

```bash
~/Documents/mozilla-code/webmaker-app (master) ▶ gulp lint
[10:00:13] Using gulpfile ~/Documents/mozilla-code/webmaker-app/gulpfile.js
[10:00:13] Starting 'jshint'...
[10:00:13] Starting 'jscs'...
[10:00:14] 'jscs' errored after 1.15 s
[10:00:14] Error in plugin 'gulp-jscs'
Message:
    Invalid quote mark found at lib/analytics.js :
     6 | */
     7 |
     8 |var xhr = require("xhr");
--------------------------^
     9 |var localForage = require('localforage');
    10 |var clone = require('clone');

Illegal space after key at lib/analytics.js :
   133 |        // Required
   134 |        v: 1,                               // MP Version
   135 |        tid : config.GA_TRACKING_ID,        // Tracking ID / Property ID.
-------------------^
   136 |        cid : model.data.session.guestId,   // Anonymous Client ID.
   137 |

Illegal space after key at lib/analytics.js :
   134 |        v: 1,                               // MP Version
   135 |        tid : config.GA_TRACKING_ID,        // Tracking ID / Property ID.
   136 |        cid : model.data.session.guestId,   // Anonymous Client ID.
-------------------^
   137 |
   138 |        // Additional values we want to use for App Specific measurement

Illegal space after key at lib/analytics.js :
   137 |
   138 |        // Additional values we want to use for App Specific measurement
   139 |        an : packageJSON.name,              // Application Name
------------------^
   140 |        //aid : '',                         // Application ID
   141 |        av : packageJSON.version,           // Application Version

Illegal space after key at lib/analytics.js :
   139 |        an : packageJSON.name,              // Application Name
   140 |        //aid : '',                         // Application ID
   141 |        av : packageJSON.version,           // Application Version
------------------^
   142 |        //aiid : '',                        // Application Installer ID
   143 |        ds: 'app',                          // Data Source

Invalid quote mark found at lib/analytics.js :
   182 |    xhr({
   183 |        body: gaBody,
   184 |        uri: "https://ssl.google-analytics.com/collect",
---------------------^
   185 |        method: "POST"
   186 |    }, function (err, resp, body) {

Invalid quote mark found at lib/analytics.js :
   183 |        body: gaBody,
   184 |        uri: "https://ssl.google-analytics.com/collect",
   185 |        method: "POST"
------------------------^
   186 |    }, function (err, resp, body) {
   187 |        if (resp.statusCode === 200) {
[10:00:14] Finished 'jshint' after 1.16 s
```

**Comment by gvn** [comment]
Seems like maybe this should be an npm module? Do we use this lib in multiple projects?

**Comment by thisandagain** [comment]
Agreed. Tracking here: https://github.com/mozilla/webmaker-app/issues/1198

**Comment by thisandagain** [comment]
Resolved lint issues in 72abca7ab5a49fa1ad6564a7443ba4d4547bf18f

**Comment by adamlofting** [comment]
Thanks for fixing. :smile: 

Any ideas why my `gulp lint` would let these particular formatting issues by? (and I guess the same for Travis?)

Even when I pull latest from master and deliberately re-introduce those formatting issues it doesn't give me an error. It does error if I do something more drastic like delete a function, or a closing brace though. My `.jscsrc` matches up with https://github.com/mozilla/webmaker-app/blob/master/.jscsrc

Is this worth filing as a separate bug?

**Comment by thisandagain** [comment]
Seems to be a race condition within the `gulp test` task. Can you file @adamlofting ?

**Comment by Pomax** [comment]
`gulp lint` is not the same as `gulp jscs`. The linting is fine (there are no syntactical errors) but you're failing the style guide that JSCS is testing for. `gulp test` does the "full testing" that travis does

**Comment by gvn** [comment]
Actually `gulp lint` does run the `jshint` and `jscs` tasks. (`gulp.task('lint', ['jshint', 'jscs']);`)

`gulp test` just runs `gulp lint` plus the unit tests.

**Comment by hansiemithun** [comment]
Hi folks, any idea about this error, similar to the thread: http://stackoverflow.com/questions/35766128/how-to-supress-the-error-illegal-space-before-opening-round-brace-at-from-jsrc. Please help
