### ISSUE TITLE
Editor Icons are not up to spec

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#1232]
The icons that appear on the editor are a bit different than the design.

![screenshot 2015-02-19 09 39 55](https://cloud.githubusercontent.com/assets/1119821/6268496/4d6d2764-b81b-11e4-92c8-87f6698adbaf.png)

![screenshot 2015-02-19 09 40 51](https://cloud.githubusercontent.com/assets/1119821/6268504/65e178e0-b81b-11e4-83b5-b9b88114d90f.png)

**Comment by thisandagain** [comment]
:+1: Marking as "bug". Thanks for catching this @vazquez
