### ISSUE TITLE
Editor should have a dotted outline on the element being edited

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#1233]
![screenshot 2015-02-19 09 40 51](https://cloud.githubusercontent.com/assets/1119821/6268611/2aa8ae78-b81c-11e4-9bf2-66f3d104b780.png)

**Comment by thisandagain** [comment]
We removed this last week as it was causing some weird layout issues where the content would shift ever so slightly between normal and edit modes on Android. I'm sure we can find a way to get it to return if you feel it's warranted.

**Comment by vazquez** [comment]
Oh! Okay no problem, I will cancel the PR

**Comment by vazquez** [comment]
Closing issue.
