### ISSUE TITLE
Add TOS and Privacy Policy links to Profile View

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1240]
Until we release to the Google Play and Firefox Marketplace, we need to add a link to our Webmaker TOS and Privacy Policy to the app. My thought is that this can be added to the bottom of the profile view for now and then removed once we release 1.0. TOS and privacy terms are generally handled by the marketplace for mobile apps.

Two small text links (blue) side-by-side should be fine:
```
"Legal" https://webmaker.org/en-US/terms
"Privacy Policy" https://webmaker.org/en-US/privacy
```

@gesa can you take this?

**Comment by gesa** [comment]
Definitely! I also would love to have a broader discussion about keeping them in long-term. (maybe in that "about" view that @davidascher had alluded to earlier?) It just feels like a super transparent, pro-user step to take in the long run.
