### ISSUE TITLE
Update bitly links for wminstall/webmaker and add redirect code back in

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1246]
Right now the redirect on the installation service is disabled. Once the install page has landed, let's:

* [x] point mzl.la/installwm to the install service
* [x] point mzl.la/webmaker to the install page at webmaker.mofostaging.net/app (for testing)
* [x] point mzl.la/webmaker to the install page at webmaker.org/app
* [x] update the code in webmaker-app-cordova/install/install.js to enable the redirect for desktop browsers

**Comment by k88hudson** [comment]
I'm going to leave it to @secretrobotron to update the mzl.la/webmaker to the prod link when it's deployed/ready.

**Comment by secretrobotron** [comment]
(｀_´)ゞ

**Comment by thisandagain** [comment]
@secretrobotron update?

**Comment by secretrobotron** [comment]
Looks like this is all taken care of now.
