### ISSUE TITLE
Android setup docs links

### ISSUE THREAD

**Issue by pippinlee** [mozilla/webmaker-app#1250]
Was going through setting up Cordova/Android SDK and found a few small errors in docs.

All related to this [Android docs](http://webmaker-mobile-guide.mofodev.net/_docs/get_started/android.html) page

* Top Android sdk link broken, needs reformatted

* Wrong ngrok website link, should be [https://ngrok.com/download](https://ngrok.com/download)

* Incomplete sentence describing `adb version` command

Sorry if I missed these discussed elsewhere. Happy to submit a PR if these should be fixed.

**Comment by thisandagain** [comment]
Great catch @pippinlee. Thanks! Happy to accept a PR if you are up for it!
:smile:

**Comment by k88hudson** [comment]
:scroll:  :scroll: :dizzy: 

 (^ docs emoji)

**Comment by thisandagain** [comment]
Resolved by https://github.com/mozilla/webmaker-app/pull/1256
