### ISSUE TITLE
Cancel on adding block page shouldn't add a block

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#1252]
STR:

1. Click "Make" tab
2. Choose "Start From Scratch"
3. Tap the "+" sign
4. Choose "Text" block
5. Tap "Cancel" on top left

Expected:
Shouldn't add Text block to my app

What happen:
Text block was added to my app

**Comment by k88hudson** [comment]
definitely worth fixing but maybe after MWC?

**Comment by alicoding** [comment]
@k88hudson I'm not sure if it is a bad bug or not, but it's just annoying when everytime you press cancel and then you see the block that you didn't want to add in the app itself, so I will let you decide here then if we want to merge before MWC or after.

**Comment by k88hudson** [comment]
Sure, this is awesome :) i will review asap
