### ISSUE TITLE
Access Denied S3 message when sharing app

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1254]
Just tried to publish an app on Galaxy S3, Android 4.4.2, latest build from mzl.la/android.

Publish works fine, but share doesn't. I get a classic S3 AccessDenied message: https://apps.mofostaging.net/p/-JibxBIC65UDIP3SGsoB/

**Comment by k88hudson** [comment]
@secretrobotron there was an issue with the cloudfront configuration, should be good now

**Comment by k88hudson** [comment]
(will be a few minutes to take affect though)

**Comment by k88hudson** [comment]
Ok, looks like that fixed it. :dancer: 

Thanks for filing!

**Comment by secretrobotron** [comment]
:dancers: :tangerine: :dancer:
