### ISSUE TITLE
Desktop resolutions leads to huge UI elements and graphics

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-app#1263]
not-even-full-screen browser:

![](http://i.imgur.com/mIEEnhj.png)

Which looks fine, until you click on it to see the image real size. That's what we look like at the moment =x

**Comment by errietta** [comment]
So the buttons are so big because of the display: flex layout. We can make them smaller by reducing the width of the images inside the box depending on the resolution. But as for the campus map image itself: We can't both have it not be huge AND have it take up the entire width, as far as I'm concerned (unless we crop it). What's a good way to deal with that one?

**Comment by davidascher** [comment]
I think there's a bug somewhere that explains that we want a mobile-sized
view even on desktop (much like we did w/ Appmaker)

**Comment by Pomax** [comment]
this raises the question of why we want something that looks absolutely horrible instead of wanting something that looks nice...

**Comment by errietta** [comment]
Indeed. I thought this was going to be one app for all devices? in which
case it should be responsive :/
or am I making stuff up?

On Mon, Feb 23, 2015 at 4:57 PM, Mike Kamermans <notifications@github.com>
wrote:

> this raises the question of why we want something that looks absolutely
> horrible instead of wanting something that looks nice...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-app/issues/1263#issuecomment-75582865>
> .
>



--  [[unflagged]](http://plzkthx.herokuapp.com)
Errietta Kostala

Web: http://www.errietta.me

**Comment by davidascher** [comment]
Pomax: i don't understand your comment. Please be more explicit.

Erietta: the plan is for the web view over time to be a way more responsive
experience but thats not just about layout, we also need to adjust the
whole ux.

**Comment by Pomax** [comment]
my comment was in relation to the fact that there is a difference between not spending effort on making a marginal aspect of our product as pretty as the rest, and not spending time on at least ensuring that marginal aspect is not incredibly ugly. This came before I'd seen the issue that recommend doing away entirely with the desktop experience, which if that's what we're doing, voids this issue completely.
