### ISSUE TITLE
Android - SMS brick does not open messaging on tap

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1270]
*OS:* Android 5.0

**Repro Steps:**
1. Open app w/ SMS brick
2. Tap SMS brick to create message

**Expected:** Default messaging app opens w/ phone number & body pre-populated
**Actual:** Nothing happens

**Comment by thisandagain** [comment]
Update @Pomax ?

**Comment by Pomax** [comment]
Two things wrong here

1. SMS brick needs to bind onClick as prototype function and needs to call it using a v-on property,
2. Cordova needs to whitelist sms: (and tel: and mailto:) for external app launching, https://github.com/mozilla/webmaker-app-cordova/pull/39
