### ISSUE TITLE
Windows - mkdirp breaks cordova build

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1271]
This recent line change from https://github.com/mozilla/webmaker-app-cordova/pull/33/files seems to be the culprit:
```
"add-platform": "mkdirp www && cordova platform add android firefoxos",
```

/cc @Pomax

**Comment by Pomax** [comment]
the reason that this fails, incidentally, is simply that `mkdirp` does not exist on windows, not even with the git unix tools extensions (it only has mkdir)

**Comment by jbuck** [comment]
The issue here was that I added a new node dependency (`mkdirp`) and Pomax hadn't run `npm install` after updating to the latest version of `webmaker-app-cordova`. It also turns out that npm v1.4 doesn't alias mkdirp to mkdirp.bat, but updating to npm 2.x works. Hooray!
