### ISSUE TITLE
Preview - Remove tabBar from template preview

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1284]
We currently display the tabBar in the template preview view. This feels a little odd to me as it is a child of the template view. I propose we remove it. Thoughts?

/cc @vazquez @k88hudson 

![preview_00](https://cloud.githubusercontent.com/assets/747641/6334721/84fa5ed0-bb64-11e4-927d-6239ba204b8d.png)

**Comment by k88hudson** [comment]
@thisandagain I agree, let's remove it

**Comment by vazquez** [comment]
Definitely! :+1: it's actually a bug, the designs don't feature the tab bar in previews.
