### ISSUE TITLE
mzl.la/installwm just shows a blue screen

### ISSUE THREAD

**Issue by mikeconley** [mozilla/webmaker-app#1285]
STR:

1) On a Nexus 5 running Firefox for Android 35, browse to mzl.la/installwm

ER:

This should initiate a download for the Webmaker app, I believe.

AR:

I just see a blue background colour, and no download starts.

**Comment by mikeconley** [comment]
Video of problem: https://www.youtube.com/watch?v=rXPRLPAe21k

**Comment by davidascher** [comment]
See the same thing using Firefox on nexus 5

**Comment by k88hudson** [comment]
Hm, so the error is:
```
 [JavaScript Error: "TypeError: version is undefined" {file: "http://webmaker-dist.s3.amazonaws.com/install.js" line: 19}]
```

looks like the UA parser is unable to determine the OS version on Firefox for Android.

**Comment by k88hudson** [comment]
@davidascher @mikeconley this should be resolved now. Thanks for filing!

**Comment by mikeconley** [comment]
Verified fixed! Thanks for the speedy work.
