### ISSUE TITLE
Rm plugins/platform directories before npm start

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1288]
In order to ensure npm start works on webmaker-app-cordova, we need to `rm` the plaform and plugins directory. Otherwise, the command will fail/plugins won't get copied.

**Comment by k88hudson** [comment]
cc @thisandagain @jbuck

**Comment by jbuck** [comment]
I ran into this as well, and I fixed it in https://github.com/mozilla/webmaker-app-cordova/pull/35

**Comment by jbuck** [comment]
Landed mozilla/webmaker-app-cordova#35, marking as closed
