### ISSUE TITLE
can't share on a Nexus 7 with Android 4.4.4

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-app#1291]
It looks like sharing on a Nexus 7 (which has no phone capabilities) with Android 4.4.4 doesn't work. The console reveals that we successfully publish, and that the socialsharing plugin is installed correctly, but the actual call to `window.plugins.socialsharing.share(...)` does not result in the "pick a thing to now share on" picker that's supposed to show up

I've filed https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/issues/310 to hopefully hear back whether that's a known issue or whether it's a complete mystery.

**Comment by k88hudson** [comment]
I think we should move this to backlog for now, since tablet is not a critical focus for MWC

**Comment by Pomax** [comment]
actually, I don't know what we did in the last two days, but sharing works now, so I'm just closing this as resolved
