### ISSUE TITLE
Submitting a survey does nothing

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1296]
* Created a survey app
* published it, shared it w/ myself (http://apps.mofodev.net/p/-JisxemGRl0KHBBVAFEF/)
* opened the link in firefox beta on android 5.
* filled in the form, hit submit

Actual -> nothing happened.
Expected -> a "thank you for submitting" form of some kind.

**Comment by k88hudson** [comment]
This is expected, although I agree, not an ideal experience. Is this something we want to tackle before MWC @thisandagain @vazquez?

**Comment by davidascher** [comment]
If it does nothing, then I don't think we should have it as a template.  It
leads people to puzzlement and dismay.

**Comment by k88hudson** [comment]
@davidascher does the button text change to "Data submitted"  or does it actually do nothing at all?

**Comment by k88hudson** [comment]
Interesting. seems to *actually* do nothing. this is indeed a bug

**Comment by k88hudson** [comment]
Apologies ^_^

**Comment by thisandagain** [comment]
@k88hudson can you take this one?

**Comment by k88hudson** [comment]
can do
