### ISSUE TITLE
Android: adding a photo from camera causes app to hang

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker-app#1297]
*OS:* Android 4.4
*Browser:* N/A
*Screenshot:* 
![screenshot_2015-02-23-17-03-08](https://cloud.githubusercontent.com/assets/782056/6341371/76002e0e-bb7e-11e4-8f5c-7101b9ce6df6.png)

**Repro Steps:**
1. In the inline editor for a photo block, tap the pencil
2. tap the camera icon

**Expected:** Device camera interaction
**Actual:** App hangs at the above screen (loading icon in center of block does animate)

**Comment by gesa** [comment]
**Alternative repro steps:**
1. In the inline editor for a photo block, tap the pencil
2. tap the gallery icon

**Comment by alicoding** [comment]
@gesa I can't seem to reproduce this at all... I think this might related to default app that was set on the device itself which I don't know how to solve except the user needs to go to the system setting and reset app default and it should work again. Can you try to do that? Let me know if you need help going through testing that.

**Comment by gesa** [comment]
uhh. after our hours and hours of experimenting, it suddenly works. so. i guess i'm going to close it now.
