### ISSUE TITLE
Android: when editing a photo, can't change from camera to gallery

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker-app#1299]
*OS:* Android (4.4)
*Browser:* n/a
*Screenshot:*
![screenshot_2015-02-23-20-30-19 png](https://cloud.githubusercontent.com/assets/782056/6343368/4c7de882-bb9c-11e4-8e0d-b7c92e752231.png)

**note: i've only verified this bug on a device which also has the #1297 bug**

**Repro Steps:**
1. In an app, tap the pencil which corresponds to an image block
2. Tap the pencil to select a new image
3. Choose either camera or gallery (loading gif forever)
4. Tap outside the inline editor to close
5. Open the same image's inline editor
6. Tap the pencil to select a new image

**Expected:** Should be presented with the option to choose either camera or gallery
**Actual:** Loading gif, no option to choose image source

**Comment by alicoding** [comment]
I couldn't reproduce this app.

I've tested on HTC with 5.0.1, FirefoxOS 2.2 and Nexus 4 with 4.4 and they are all working as expected.

**Comment by gesa** [comment]
This bug has mysteriously disappeared.
