### ISSUE TITLE
Hindi not in the list under Developer Health Check > CURRENT_LANG

### ISSUE THREAD

**Issue by abhishekvp** [mozilla/webmaker-app#1312]
I downloaded and installed the app from http://mzl.la/installwm But Hindi is not listed under Developer Health Check > CURRENT_LANG. 

I even changed my phone's locale to Hindi, but still could not see Hindi listed in the CURRENT_LANG.
My phone is running Android 4.4.4 and a Cynogenmod Kernel.

**Comment by abhishekvp** [comment]
Found in #1281

**Comment by k88hudson** [comment]
Thanks @abhishekvp! Looks like the translation is still in progress, @alicoding will update as soon as it's ready.
