### ISSUE TITLE
On Click Discover Button in Firefox OS no makes are shown

### ISSUE THREAD

**Issue by viswaprasath** [mozilla/webmaker-app#1313]
I have connected to WIFI when accessing the application. I tried to explore certain parts of app.

I click on Discover. I thought it will be showing apps made all over the world.
But it was saying 

The Internet fall asleep!
An active connection is needed to display the Discovery Gallery
Head Overt o make to start creating your very own app.

But I am sure I have active internet connection.

Firefox OS I am using is latest build updated today.
OS version 3.0.0.0
Build Number 39
build Identifier 20150224010314
Update Channel nightly

**Comment by thisandagain** [comment]
Tracking in #949
