### ISSUE TITLE
Add a button to clear profile

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1317]
The developer menu should have a "clear profile" button so devs don't have to uninstall/reinstall app when they want to check things.

cc @alicoding

**Comment by alicoding** [comment]
I'm closing this one since this ticket should solve the problem we were having which is clearing locale when we changed the language preference on the device itself https://github.com/mozilla/webmaker-app/pull/1328

**Comment by alicoding** [comment]
Unless we want it for clearing everything please feel free to reopen this ticket.
