### ISSUE TITLE
long press on top bar no longer showing developer menu

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1319]
android 5, using a build from yesterday late afternoon PST.

**Comment by k88hudson** [comment]
I think the bug might be long press doesn't work on `/make/:id`, but it does on other views

**Comment by davidascher** [comment]
Tried in:

* My Apps
* Discover
* Create a How To Guide
* editing my own

none of them work (pressing for 5+seconds)

FWIW, I think long-press is more like 2s usually

**Comment by thisandagain** [comment]
I'm not able to replicate in any of the views with a navigationBar *except* for the editor on Android 5.0.1 (Nexus 5) on current `master`. @davidascher are you on 5.0.0 or 5.0.1? Just want to make sure I'm getting as close as possible.

**Comment by davidascher** [comment]
I'm on 5.0.1

**Comment by thisandagain** [comment]
Added ticket #1340 to cover the editor issue, this is fixed on current `master`. Resolved by https://github.com/mozilla/webmaker-app/pull/1275
