### ISSUE TITLE
Back button on /make/:id has unexpected behaviour

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-app#1331]
Right now if you build a template, edit a component, change its values, save those changes, and then hit "back", you're taking back to the "change the values" screen, rather than to the "build the template" screen. It feels like we're doing this:

    build template -> history.pushState
    tap component edit button
    get into edit view -> history.pushState
    save change
    get back to app view -> history.pushState
    tap component edit button
    get into edit view -> history.pushState
    save change
    get back to app view -> history.pushState

when we should probably be doing:

    build template -> history.pushState
    tap component edit button
    get into edit view -> history.pushState
    save change
    get back to app view -> remove edit state from history
    tap component edit button
    get into edit view -> history.pushState
    save change
    get back to app view -> remove edit state from history

That way, in order to "get back" to things like the template menu, you're not first tapping "back" through however many edits you made to your app.

(found during https://github.com/mozilla/webmaker.org/issues/1261 QA checking)

**Comment by gvn** [comment]
Note: http://docs.phonegap.com/en/4.0.0/cordova_events_events.md.html#backbutton
