### ISSUE TITLE
improve the "share" flow to also allow users to open their app in webmaker-app in addition to sharing out

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-app#1335]
It feels like we're missing a way to open up the app you just made in webmaker-app, during the share action, without having to hit back a lot of times before you get back to a menu that lets you pick "my apps".

**Comment by xmatthewx** [comment]
In new v1 app, this is resolved. Via the vertical ellipses menu, a user can 
 - "Play" a project they're editing
 - "Edit" their project while playing 
 - "Remix" a project by someone else
