### ISSUE TITLE
"Build" and "App" words overlap on Splash Page on Desktop

### ISSUE THREAD

**Issue by abhishekvp** [mozilla/webmaker-app#1336]
The Splash Page looks proper on mobile screens but the words "Build" and "App" overlap on desktop.
Tested on Firefox 35.0.1, Ubuntu

Attaching the Screenshot.

![screenshot from 2015-02-25 01 12 57](https://cloud.githubusercontent.com/assets/2259697/6357667/1e89b028-bc8c-11e4-8c7a-ce4dc5cccef3.png)

**Comment by abhishekvp** [comment]
Found in #1281

**Comment by thisandagain** [comment]
Thanks @abhishekvp !

Tracking in https://github.com/mozilla/webmaker.org/issues/1295
