### ISSUE TITLE
Image picker doesn't work for pngs on FirefoxOS

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1343]
E.g.: https://apps.mofostaging.net/p/-JiwMaBWYWlLlre-5VhJ/

**Comment by Pomax** [comment]
looks like it's prefixing too much in this case. The image has src `data:image/jpg,base64,data:image/png,base64.--------`, and removing the leading `data:image/jpg,base64,` results in a correct png

**Comment by k88hudson** [comment]
This should be fixed on master
