### ISSUE TITLE
Title still off-centre on the "add-block" page

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1351]
![image](https://cloud.githubusercontent.com/assets/1455535/6362818/e6129886-bc5e-11e4-872a-118f18b1535b.png)

**Comment by thisandagain** [comment]
Upon further inspection this seems to not just be limited to the "Edit" and "Add" views. Titles seem to be off center throughout the application:

- [ ] Open view
- [ ] Detail view
- [ ] Edit view
- [ ] Add view

**Comment by thisandagain** [comment]
@gesa @gvn @k88hudson Any thoughts on how to audit / resolve this quickly throughout the app?

**Comment by gvn** [comment]
It's tough because there are literally ~12 variants on the navbar, so it's very fragile. Basically I just try to check all the other views when I change one of the navbars... :frowning:

**Comment by thisandagain** [comment]
Resolved in https://github.com/mozilla/webmaker-app/pull/1370
