### ISSUE TITLE
Apps you look at get added to in your "My Apps" section

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1356]
From a contributor:

>  I was just checking out some of the existing makes in the app and somehow unknowingly those makes were added into 'my makes' collection. Is that supposed to happen? I was merely testing those makes. Not remixing them.

I've noticed this a bunch too. When I'm looking at someone else's app, I often get my own copy of it.

**Comment by thisandagain** [comment]
@k88hudson we had this issue before? Is it possible that we had a regression?

**Comment by secretrobotron** [comment]
Also depends on when it was fixed. The contributor I asked may have a build that's a couple days old now (lol).

**Comment by thisandagain** [comment]
Confirmed on latest `master`. STR:
- Go to "Discover" view
- Select an app
- Press "Open App"
- Go back x2
- Go to "My Apps"
- App that you viewed is now available

**Comment by thisandagain** [comment]
Added the `critical` flag. This is a blocker for RC.
