### ISSUE TITLE
Back - After editing, "back" takes you back to the editor

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1365]
* [x]  A: app editor > edit block > cancel > back button (or android back)
* [x] B: app editor > add block > choose block > cancel > back button (or android back)
* [x] C: app editor > add block > choose image > back button (or android back)
* [x] D: app editor > add block > choose text > done
* [x] E: app editor > edit block > colour picker > done or cancel > done > back button
* [x] F: app editor > edit block > done > back button (or android back)
* [x] G: app editor > edit block > colour picker > done or cancel > done > back button

Related to https://github.com/mozilla/webmaker-app/pull/1362

**Comment by k88hudson** [comment]
Ok, I'm pretty sure that list covers it.
