### ISSUE TITLE
Use cloudfront / shortener for published apps

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1366]
We are still using `mofostaging` for published apps.

**Comment by thisandagain** [comment]
Settled on `m.makes.org`. @jbuck has setup the DNS and SSL cert. We now need to update app / publisher.

**Comment by k88hudson** [comment]
Nice work. updating now

**Comment by k88hudson** [comment]
configuration change is done https://github.com/mozilla/webmaker-app-publisher/commit/672cb67629ca164440dca276f54820efb787aa1d

**Comment by k88hudson** [comment]
waiting for jenkins build to finish
