### ISSUE TITLE
Can't publish/view apps

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#1372]
Can't publish/view makes today. Just made one fine in webmaker app, but publishing it yields this: https://m.makes.org/p/-Jj5pVpoLpvNlC-hmu74/

```
console.error("Error: Line 1: Unexpected token < while parsing file: /Users/k88hudson/github/webmaker-app/components/alert/index.html")x.html")
```

![screenshot 2015-02-26 12 03 53](https://cloud.githubusercontent.com/assets/403231/6396934/8ecb5548-bdaf-11e4-8e44-a48fedde866e.png)

**Comment by thisandagain** [comment]
See also: #1366

**Comment by k88hudson** [comment]
Should be fixed as soon as mozilla/webmaker-app-publisher@672cb67 builds. Old apps will need to be republished.

**Comment by k88hudson** [comment]
Ok, issue is resolved. https://m.makes.org/p/-Jj66qx10hQ8MTO74ToR/
