### ISSUE TITLE
Back - Pressing "back" quickly can cause unexpected error states

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1376]
We should disable the back button after initial press to avoid strange race conditions that can occur when history back is triggered multiple times.

**Comment by gvn** [comment]
Here's a sequence that caused a blank white screen (initiated by EXTREME CLICKING):

```
/android_asset/www/index.html
/
/template/b9483c11-077e-4396-84e2-c0454c36a741/detail
/make/-Jj6dje12KVK70QmuB34
/template/b9483c11-077e-4396-84e2-c0454c36a741/detail
/
/make/-Jj6dntAElY6ZJkgGZ10
/healthcheck
/make/-Jj6dntAElY6ZJkgGZ10
```

**Comment by gvn** [comment]
When remote debugging use: `urlHistory.forEach(function (i) { console.log(i); });` to get your current view history.

**Comment by gvn** [comment]
Pretty sure this is healthcheck related. Taking it out solved the problem for me...
