### ISSUE TITLE
Android - Tablet causes layout issues on "Add" view

### ISSUE THREAD

**Issue by cbaba20** [mozilla/webmaker-app#1378]
The screen shows half tone image of buttons because the screen is not properly rendered with it. most in cases with tablets (640*480) .

Steps to reproduce : 
>>Open app >>>tap on any of building block >>> start creating new >>> and it will shows the available buttons and options.
Now do edits with buttons(edit message or links anything) and press back key . It shows a half visible image.
![shot_2015-02-27_00-39-03 1](https://cloud.githubusercontent.com/assets/8758288/6400566/b5cfdb6c-be1f-11e4-8430-74164b6d134b.png)
Screen rotations does no effect,view as same above

**Comment by secretrobotron** [comment]
Happens in the emulator on chrome too. Looks like the page layout is just stale. Any way to force things to re-center?

**Comment by thisandagain** [comment]
Based on the status bar, this looks like a really old OS. Can we confirm?

**Comment by cbaba20** [comment]
mm.... this one is yes an old one 4.1.2 , but again got the same in 4.4 .

**Comment by secretrobotron** [comment]
@cbaba20 really? can you tell us your steps again? Like...
1. Open an app
2. Add a new block
3. Edit it
...

I've been trying on my devices here, and can't reproduce. What device are you using?

**Comment by cbaba20** [comment]
Samsung Galaxy Tab 2 it is.
 steps: 
>>open an app
>>Goto Start from scratch
>>use any tool(whether it will be pencil tool or add image tool)
>>again back to use the next tool and you will get the layout is zagged like above.
____
I am getting again.

**Comment by secretrobotron** [comment]
@cbaba20 ok! thanks!
I'm seeing the same problem using an Android 4.1 tablet. Are you able to confirm you got the same problem on a 4.4 device? Can you reproduce on a phone? (We're not officially supporting tablets atm.)

**Comment by cbaba20** [comment]
mm... on Sony M series phones Yes ,it is happening.

**Comment by secretrobotron** [comment]
Same version of Android? 4.1.2?

**Comment by cbaba20** [comment]
No, its 4.4 (upgraded from 4.2). Let me check with other models .

**Comment by cbaba20** [comment]
And if tablets are not supported then this means testing results are limited to phones only.

**Comment by secretrobotron** [comment]
That's right. We're really focused on phones!

**Comment by cbaba20** [comment]
Seems Wow !! So, I think we don't need to focus on Tablets (pushing this one from tablets to Phones testing part :) )

**Comment by thisandagain** [comment]
Thanks @cbaba20 we've resolved this on the latest branch called `v1` which is available here:
https://github.com/mozilla/webmaker-app/tree/v1

I think we've resolved your issue, but please take a look and let us know if you still notice any layout issues on your tablet.
