### ISSUE TITLE
My app title not saved after hit the check mark

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#1391]
STR:

1. Open the app
2. Go to "Make"
3. Choose "Start from scratch"
4. Click the gear icon
5. Change the title
6. Tap the check mark while your keyboard still focus on the input (check mark should be grey)

Expect result:
It should save my title after I go back to the edit my app

Actual result:

It reverted back to before I edit the title

**Comment by xmatthewx** [comment]
> Tap the check mark while your keyboard still focus on the input (check mark should be grey)

Yes. And, users shouldn't need to remove focus from the input to enable the confirmation button.

**Comment by ryandang** [comment]
I was not able to reproduce the bug for this. The issue with app title only trigger the save button on focus out is fixed at #1444
