### ISSUE TITLE
Pull from Transifex once again before  MWC

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#1398]
#1397 

A lot of these languages including **French**, **Bengali**, **Spanish** and **Portuguese** apparently got a very bad bug on translating the templating variable (variable names) e.g. 

```
  "My {{template}} App": {
    "message": "My {{template}} App",
    "description": "Title for a newly created app from a template"
  },
  "by _": {
    "message": "by {{name}}",
    "description": "For apps, e.g. My Cool App, by {{name}}"
  },
```

In `sv` it was translated as:

```
    "My {{template}} App": {
        "message": "Min {{mall}} App",
        "description": "Title for a newly created app from a template"
    },
```

`{{mall}}` is going to break the app and I found many other ones, but I have fixed them all on Transifex and we just need to rebuild after it gets update on our S3 server.

**Comment by thisandagain** [comment]
@k88hudson @alicoding Update? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by k88hudson** [comment]
@thisandagain tag pushed, deploying now

**Comment by k88hudson** [comment]
@alicoding I'm still seeing some old strings on RC3 in French. Any reason why they wouldn't be updating after a new deploy?

**Comment by alicoding** [comment]
@k88hudson do you have any example? I'm running locally right now and I see those broken templating fixed for French.

**Comment by k88hudson** [comment]
@alicoding on the templates page, the start from scratch should say `Démarrer à zero`, not `de zero`

**Comment by alicoding** [comment]
I see this @k88hudson 
![screen shot 2015-02-28 at 11 51 36](https://cloud.githubusercontent.com/assets/4368149/6426966/2d040804-bf40-11e4-84ed-ff4d3f5d56cf.png)

**Comment by davidascher** [comment]
There's also a mix between imperative and infinitive on that page (-ez vs.
-er)

**Comment by k88hudson** [comment]
@davidascher Should also be fixed when the new translations get built

**Comment by k88hudson** [comment]
Issues are resolved, changes are deployed.
