### ISSUE TITLE
Can't change app name

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-app#1404]
Everytime I try to save a new name for an app, it reverts back to the template name.

Platform: Firefox OS 2.1 (Flame)

**Comment by errietta** [comment]
@cadecairos  this is because the settings page calls the 'name updated' code on blur, but if you click the save button this somehow doesn't happen fast enough. It works if we change to keyup, but I'm afraid it makes the typing slower...
Thoughts?

**Comment by errietta** [comment]
@cadecairos  R?
