### ISSUE TITLE
Prototype unified making experience for mobile

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1422]
This is the meta ticket for the **Mobile** prototype based on planning in https://github.com/MozillaFoundation/plan/issues/365

The desktop "Tiles" prototype hints toward a compelling platform for creation that's both webby and different from other existing channels for making and sharing. This heartbeat aims to design the features and complete a coherent look at this new tool across desktop, tablet, and mobile.

### Audience 

- Primary addressable audience: Firefox users on desktop and Android
 - Users on Webmaker who want to create content
 - People who view content on Webmaker

### Success :v: 

**Primary** - Articulate a complete experience for both viewers and creators, to discover, share, and make on Webmaker, with parity across mobile and desktop/tablet.
 
**Secondary** - Design an editor that hints at the underlying technology. (May differ for authors on desktop and mobile.)

### Vision

If Webmaker was a polaroid, the end of this heartbeat would be the moment _other people_ could grok the whole image despite the fuzzy corners. To achieve this:

  - Define _key_ features and their use (sorry text shadow). Each feature should be necessary or high value.
  - Better emphasize the inherent flexibility enabled by moving and linking tiles.
  - Identify ways to clarify the zoom nav metaphor (ex: view transitions, ambient indicators).

### Scope

in scope
 - gallery
 - viewing (start flag)
 - making
 - element properties (text, image, button, my-code™)
 - attribute editor (simple & advanced layers)
 - share to gallery (public/private)
 - jiggles

out of scope :do_not_litter: 
 - onboarding
 - profile
 - animation
 - social

### Deliverables :package: 

 - Unifying reference doc 
 - InVision or similar prototype
 - Annotation on interactions and transitions
 - Nice to have: Working prototype to demo author navigation on mobile 

### Links :fist: 
 - planning - https://github.com/MozillaFoundation/plan/issues/365
 - inVision - http://invis.io/PA2CNPOYG
 - gSlides - https://docs.google.com/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit?usp=sharing

cc: @flukeout @sabrinang @thisandagain @cassiemc

**Comment by k88hudson** [comment]
Sounds exciting :open_mouth: !!

**Comment by xmatthewx** [comment]
@flukeout @sabrinang produced a comprehensive view of the tool. Great work!
 - Mobile Prototype - http://invis.io/HZ2F7KDFA
 - Tablet Prototype - Done-ish! http://invis.io/HE2FK9JTP
 - Design Notebook - http://bit.ly/1FI5LFM

There are a few UX issues to iron out as we shift our eye toward UI. https://github.com/MozillaFoundation/plan/issues/377

**Comment by xmatthewx** [comment]
Revised mobile prototype. Nicely integrated sharing, better zoom, and consistent toolbar. :dart: 

http://invis.io/8X2GM9GDN

**Comment by xmatthewx** [comment]
- Plan for next steps: https://github.com/MozillaFoundation/plan/issues/377
 - Tracking specific issues in webmaker-desktop [Unified UI milestone](https://github.com/mozilla/webmaker-desktop/milestones/Unified%20UI)
