### ISSUE TITLE
target screensize

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1429]
What mobile screensize should we target for the Webmaker tiles prototype?

cc @simonwex @thisandagain @secretrobotron

**Comment by simonwex** [comment]
This has actually come up a couple times today. 

I'd break touch devices into three categories for resolution:
Low: 320 x 480 (~$40 Android, 165ppi)
Mid: 1280 x 768 (~$200 Nexus 4, ~320ppi)
High: 2560 x 1440 (~$800 Samsung S6, ~600ppi)

This is through a north-american lens. But how does this feel as a starting point? If that's the case, who do we want to focus on, @thisandagain, @secretrobotron, @davidascher

**Comment by davidascher** [comment]
I'd start with the midrange as a way of getting a version that doesn't feel
terrible on "our" phones but isn't so high end that we'll paint ourselves
in a retina world.

**Comment by thisandagain** [comment]
Thanks for pulling this together @simonwex. There is a pretty big gap between the low and mid-range devices you have listed here. For WMA we had been using the Huawei Y600 (http://www.gsmarena.com/huawei_ascend_y600-6278.php) as our reference for a low-end Android device that is popular in both the new and used markets that is comparable to many other of the most popular models from MicroMax, ZTE, Spice, and Samsung. That said, I think the Nexus 4 you have listed for "Mid" is right on and a good place for us to focus for now.

**Comment by xmatthewx** [comment]
Excellent. Thanks.
