### ISSUE TITLE
Have a delete button beside open my app?

### ISSUE THREAD

**Issue by ryandang** [mozilla/webmaker-app#1436]
I know you can delete the app after you open it but I think it's would be nice if we have a delete button before open the app.

we'll have the delete button in red color
![delete](https://cloud.githubusercontent.com/assets/7368258/6743926/4a3e236e-ce77-11e4-95eb-eae4c05d958e.png)

**Comment by thisandagain** [comment]
@flukeout Something to think about in the spec for the updated project detail view.
