### ISSUE TITLE
console.error("Error: Cannot find module './lib/primitives' from 'D:\\Git\\webmaker-app\\node_modules\\vue\\src\\vendor'")dor'")

### ISSUE THREAD

**Issue by 285858315** [mozilla/webmaker-app#1438]
Why ? where is "lib/primitives" ?

**Comment by 285858315** [comment]
![Uploading QQ图片20150325122629.png . . .]()

**Comment by 285858315** [comment]
![qq 20150325122629](https://cloud.githubusercontent.com/assets/2813953/6818432/715ba184-d2ea-11e4-9759-6646e634f2f1.png)

**Comment by thisandagain** [comment]
Hey @285858315 could you explain how you are running the app? Is this when running `gulp dev` on the latest from the `master` branch?

**Comment by thisandagain** [comment]
Closing for now, but please let us know if you have any details to share or run into any further issues! :+1:
