### ISSUE TITLE
fxos-only build?

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-app#1441]
webmaker-app-cordova requires that an android emulator & adb & friends are installed, even if you only want to build for FirefoxOS, which IMO is very annoying. I think we should only require the android tools if you're building for android. Thoughs?

**Comment by Pomax** [comment]
don't we already? If, rather than letting npm add the platforms, you manually add them, you can make sure to add only firefoxos rather than also adding android. You shouldn't need the android studio then?

**Comment by errietta** [comment]
Ah I didn't know! Thanks @Pomax :grinning:
