### ISSUE TITLE
UI - Page view

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1447]
Finalize UI design for the mobile tile view based on UX from @flukeout and @sabrinang.

**Comment by vazquez** [comment]
This is where I am right now:

![tile view](https://cloud.githubusercontent.com/assets/1119821/6974089/a65be69a-d95d-11e4-94d8-09f737ef319e.png)

**Comment by xmatthewx** [comment]
@vazquez, ~~tile~~ page editor is lookin' sharp. 
 - indicate neighboring tiles
 - remove or de-emphasize neighbor indicator when an element is selected

**Comment by xmatthewx** [comment]
Probably a good idea to look at how the (+) element will fan out with more than 3 element types. In the future, they might require labels, though not sure if we need to tackle that now.

**Comment by vazquez** [comment]
Leave UI Feedback: http://invis.io/BK2M18Q28
Marvel Prototype: http://marvl.in/ee2f0e

Progress on indicating neighbouring tiles:

![tile view](https://cloud.githubusercontent.com/assets/1119821/6983829/5a7ad0a4-d9f0-11e4-9985-6086b80b4b4f.png)

**Comment by xmatthewx** [comment]
Can we call this done? Only pending detail: consistent page proportions and size of neighbor hints across all view states.

**Comment by vazquez** [comment]
This has been addressed. The view has been made more consistent to what exists in @flukeout's prototypes. We have also removed borders and added colour to neighbouring tiles.

![tile view](https://cloud.githubusercontent.com/assets/1119821/7320417/770f5ac0-ea6a-11e4-91d8-a605a85f3af6.png)

**Comment by vazquez** [comment]
Safe to close and file anything else as additional issues.
