### ISSUE TITLE
UI - Project settings view

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1448]
Finalize UI design for the mobile project detail view based on UX from @flukeout and @sabrinang.

**Comment by xmatthewx** [comment]
This is accessed via the vertical ellipses on Project Map view. 

Includes in RC v1
 - project title

Possible future home of
 - project thumb
 - project color
 - allow zoom
 - etc

**Comment by xmatthewx** [comment]
@vazquez let's add a Description field below title on this view.

**Comment by vazquez** [comment]
+1

**Comment by vazquez** [comment]
### Benchmarks

![2015-04-21 14 33 22](https://cloud.githubusercontent.com/assets/1119821/7254820/5ff45100-e813-11e4-86ee-b31519e3c772.png)

![2015-04-21 14 35 19](https://cloud.githubusercontent.com/assets/1119821/7254826/6365e344-e813-11e4-91c8-a94440749790.png)

![2015-04-21 14 36 45](https://cloud.githubusercontent.com/assets/1119821/7254830/672eadb2-e813-11e4-8d3a-7b714248175a.png)

![2015-04-21 14 40 09](https://cloud.githubusercontent.com/assets/1119821/7254839/6f8e0b92-e813-11e4-819d-4af023c8d591.png)

![2015-04-21 14 40 36](https://cloud.githubusercontent.com/assets/1119821/7254843/74fcb498-e813-11e4-8232-23a40cc3ed18.png)

![2015-04-21 14 41 37](https://cloud.githubusercontent.com/assets/1119821/7254852/7b8db6ae-e813-11e4-81ae-888b2dde9e0d.png)

**Comment by xmatthewx** [comment]
Thanks @vazquez 

UX for this was never completed. Clarifying in #1531. Don't worry about future features. Let's keep this as simple as possible.

**Comment by vazquez** [comment]
Leave UI Feedback: http://invis.io/BK2M18Q28

![project settings](https://cloud.githubusercontent.com/assets/1119821/7256790/483f920c-e81f-11e4-96c3-7cb27496270e.png)

![project settings edit title](https://cloud.githubusercontent.com/assets/1119821/7256792/4adef71e-e81f-11e4-96b9-7109ce92c97e.png)

**Comment by vazquez** [comment]
I just saw #1531. So I have green light to remove Project Description for now @xmatthewx?

**Comment by xmatthewx** [comment]
Yes. Check plus. Remove project description. Added some notes to invision.

**Comment by vazquez** [comment]
Done! :boom:

**Comment by xmatthewx** [comment]
![project settings focus](https://cloud.githubusercontent.com/assets/53411/7327313/3d0e452c-ea9a-11e4-8955-1bfdcc5ee9d9.png)
