### ISSUE TITLE
UI - Pages map view

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1449]
Finalize UI design for the mobile editor view based on UX from @flukeout and @sabrinang.

**Comment by xmatthewx** [comment]
@vazquez, for the ~~aerial~~ map view of ~~tiles~~ pages...
 
 - pre-select a tile
 - primary tool: zoom in ( === edit) 
 - secondary tool: delete
 - secondary tool: maybe add paint since we're dropping edit

**Comment by vazquez** [comment]
I have a view of the Editor now, without Tinker mode designed. I will tackle that next. Let me know what you think.

Both Marvel and InVision have been updated.

Leave UI Feedback: http://invis.io/BK2M18Q28
Marvel Prototype: http://marvl.in/ee2f0e

![edit element](https://cloud.githubusercontent.com/assets/1119821/7011832/7782ab0e-dc7a-11e4-85b5-f300e94088b0.png)  

![edit element opacity](https://cloud.githubusercontent.com/assets/1119821/7011836/7a29ea52-dc7a-11e4-8cf9-dc6e57db9904.png)

**Comment by xmatthewx** [comment]
Base UI is mostly done. 
 - increase fidelity of floating tools over noisy content
 - design state changes for drag and drop pages
 - design state changes for delete tile animation

**Comment by xmatthewx** [comment]
@vazquez - Ready to close? Update [build slides](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae0e362d5_2_52) to your latest comps with dev notes.
