### ISSUE TITLE
UI - Discover view

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1451]
Finalize UI design for the mobile discovery view based on UX from @flukeout and @sabrinang.

Go to InVision to leave UI feedback: http://invis.io/BK2M18Q28

**Comment by xmatthewx** [comment]
@vazquez - notes from our conversation:

 - remove the Webmaker header and put the tabs up top. 
 - make author name more tap friendly 
 - tap to open a project... 
   - let's try a [parent child transition](http://www.google.com/design/spec/patterns/navigational-transitions.html#navigational-transitions-parent-to-child) rather than a sibling push
   - within a project, we can replace the back arrow with a discover icon to exit

**Comment by vazquez** [comment]
I have not taken @xmatthewx's feedback into consideration yet, but wanted to share where this screen is at the moment.

![discover view](https://cloud.githubusercontent.com/assets/1119821/6974172/64cf3c58-d95e-11e4-9057-c13a6185206c.png)

**Comment by thisandagain** [comment]
Top level navigation challenge ... it's currently not clear to me that I would go to "Profile" to make something. Should we consider a persistent "Add Project" button or control? Something less clinical / more action oriented than "Profile"?

**Comment by xmatthewx** [comment]
Good catch @thisandagain. It should be called 'Make' rather than profile. See #1464

**Comment by vazquez** [comment]
Feedback has been addressed. This is where the screen is at the moment:

Leave UI Feedback: http://invis.io/BK2M18Q28
Marvel Prototype: http://marvl.in/ee2f0e

![discover view](https://cloud.githubusercontent.com/assets/1119821/7006870/9037a42e-dc52-11e4-9119-aa9dac3a01d2.png)

**Comment by xmatthewx** [comment]
We like the full preview, but need to test whether people understand horizontal browsing. Also need to resolve additional gray background when adding bigger hints of neighboring projects. 

![dicover view full alt](https://cloud.githubusercontent.com/assets/53411/7236018/03a19542-e760-11e4-9a9c-ce9844e1940d.png)

Add to testing plan.

**Comment by thisandagain** [comment]
I think I need to reiterate my earlier feedback that the primary goal of discovery / consumptive views like this is to allow users to scan a large amount of content quickly. We seem to be optimizing for aesthetics here with full scale previews and horizontal scrolling rather than the ability for a new or non-engaged user to find a compelling piece of content. I recommend that we take another look at the earlier cropped / vertical iteration.

**Comment by xmatthewx** [comment]
Noted. We have the cropped view done. Can run with that.

**Comment by vazquez** [comment]
Okay! I've made the modifications for the cropped view. I've made the cropped view larger while still maintaining a view of the project to come. I've also added some texture to the background as per Matthew's explorations.

Leave UI Feedback: http://invis.io/BK2M18Q28

![discover view](https://cloud.githubusercontent.com/assets/1119821/7237973/4818cc6a-e76d-11e4-9703-36a18db445e7.png)

**Comment by vazquez** [comment]
Closing! :stars:

**Comment by flukeout** [comment]
@vazquez Whoa :stars: - our new tinker icon??
