### ISSUE TITLE
UI - Bottom navigation components 

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1453]
Finalize UI design for the bottom navigation components.

Go to InVision to leave feedback: http://invis.io/BK2M18Q28

**Comment by vazquez** [comment]
Bottom navigation components are following Android Material Design guidelines and are taking Luke and Sabrina's depth explorations. They can be seen in the following mocks:

![tile view](https://cloud.githubusercontent.com/assets/1119821/6974116/db0d9b72-d95d-11e4-9391-b4e124b09c63.png)

![add element to tile](https://cloud.githubusercontent.com/assets/1119821/6974123/e2699916-d95d-11e4-94ce-ace6bf88f6e4.png)

**Comment by xmatthewx** [comment]
Update the zoom in and out for the Play experience to match @flukeout's prototype. Good to go otherwise.

**Comment by vazquez** [comment]
Matched play experience to match the prototype. Moving this to Alpha 2/2 for tracking.

**Comment by xmatthewx** [comment]
:+1:
