### ISSUE TITLE
UI - Icon set

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1454]
Build icon set for mobile / desktop application. Bias towards feeling idomatic for Android.

Go to InVision to leave feedback: http://invis.io/BK2M18Q28

**Comment by vazquez** [comment]
Some progress has been done here.

![screenshot 2015-04-02 17 34 58](https://cloud.githubusercontent.com/assets/1119821/6974188/9eb1d4a8-d95e-11e4-8221-e128bb7c6a59.png)
![screenshot 2015-04-02 17 35 23](https://cloud.githubusercontent.com/assets/1119821/6974217/d2472b42-d95e-11e4-95c1-eca0dbd4589d.png)

**Comment by xmatthewx** [comment]
Icon for button link could use improvement. Probably not our highest priority.

**Comment by thisandagain** [comment]
Agreed. That iconography is fairly specific to iOS.

**Comment by vazquez** [comment]
Moving to Alpha 2/2

**Comment by xmatthewx** [comment]
The pop-up tool buttons are nearly the same size as zoom-minus and paintbrush, but not quite (+5px). Align these sizes and make sure they have nice musical proportions relative to the larger primary button and minor trash button. 

Now's a good time to take inventory of all the icons to make sure things are either optically the same or intentionally different. 
 - tools 
 - checkmark
 - ellipses
 - back arrow
 - exit arrow
 - slider knob 
 - swatches
 - tinker tab icons
 - ...?

**Comment by vazquez** [comment]
Done and done.

Leave UI Feedback: http://invis.io/BK2M18Q28

**Comment by vazquez** [comment]
Icon inventory.

![icons](https://cloud.githubusercontent.com/assets/1119821/7373335/c123263c-ed99-11e4-86ce-c0dc026c82f4.png)
