### ISSUE TITLE
Services - API

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1461]
With the MWC release out of the way we should re-evaluate our use of Firebase and the observer-based data model approach that we have today. This issue is to track discussion on the pros and cons of various different approaches TBD.

**Comment by thisandagain** [comment]
Related: https://github.com/mozilla/webmaker-desktop/issues/26

**Comment by thisandagain** [comment]
@xmatthewx Any updates?

**Comment by xmatthewx** [comment]
Some discussion in the related planning ticket, but no specific proposals yet that I know about. 
https://github.com/MozillaFoundation/plan/issues/427

cc @jbuck @k88hudson

**Comment by thisandagain** [comment]
Tracking in https://github.com/mozilla/api.webmaker.org/issues
