### ISSUE TITLE
UI - Make view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1464]
Finalize UI design for the mobile 'Make' view based on UX below. MVP profile could be simplified to username. Should consider empty state CTA.

![screenshot-2015-04-02-22 46 34](https://cloud.githubusercontent.com/assets/53411/6977451/565dd882-d98b-11e4-91ac-27260a1ab6f0.png)

**Comment by xmatthewx** [comment]
Done ![make view](https://cloud.githubusercontent.com/assets/53411/7236127/fc879652-e760-11e4-925c-2f95f6e334a7.png)

**Comment by gvn** [comment]
@vazquez What are the dots for to the right of "The Birds of the Amazon"?

**Comment by xmatthewx** [comment]
For now, delete would be great. 

![screenshot 2015-05-04 18 20 20](https://cloud.githubusercontent.com/assets/53411/7463765/3fc8afa8-f28a-11e4-828d-29343e92a0e4.png)

**Comment by thisandagain** [comment]
@vazquez @xmatthewx I have a slight concern with how we are spec-ing an Android `OptionsMenu` for the delete, duplicate, and share functionality here. We aren't able to use native Android drawable (UI) components outside of the navigation in the header. Thus, we would need to rebuild and fake this using HTML / CSS / JS which is always going to feel slightly off. I'd rather us spec something simple and custom that doesn't put us down the path of rebuilding material UI. Thoughts?

**Comment by vazquez** [comment]
@thisandagain - Ah interesting. We would then be steering outside of Android design patterns, would we be okay with this? I would also need to use something other than the vertical ellipsis, as it's odd to give users two different visual treatments based on one icon. 

I'm kind of torn here, because if I were to design something custom, I would still make it pretty similar to Material UI so as to keep a consistent visual language (depth treatment, icon-less list). So my gut says, "hey Ricardo, why not keep it the way it is?".

**Comment by thisandagain** [comment]
@vazquez Perhaps take a look at how Instagram handles this on Android. They use the vertical ellipsis (as is convention) but have a much simpler modal dialog.

**Comment by vazquez** [comment]
You make an excellent point :+1: 

Here are some benchmarks in which you see something other than Material design sheets for more actions.

##### Instagram
When tapping more actions (vertical ellipsis), a modal is disclosed.  

![screenshot_2015-05-05-13-57-56](https://cloud.githubusercontent.com/assets/1119821/7479508/f57b2f2e-f316-11e4-9ee3-29c109def8b4.png)

---

##### Evernote
When tapping more actions (vertical ellipsis), a modal is disclosed.  

![screenshot_2015-05-05-13-56-29](https://cloud.githubusercontent.com/assets/1119821/7479537/3168823e-f317-11e4-94f1-d53d43664887.png)

---

##### Dropbox
When tapping more actions (downward facing caret), a horizontal list is shown.

![screenshot_2015-05-05-13-58-26](https://cloud.githubusercontent.com/assets/1119821/7479549/46e50fec-f317-11e4-95fa-32feeef3c793.png)

**Comment by vazquez** [comment]
I will update the UI shortly.

**Comment by vazquez** [comment]
#### Updating UI

The vertical ellipsis will now disclose a modal overlay.

##### Notes

- Pressing system back button or tapping anywhere in the grey area will remove the modal.

![make view more actions](https://cloud.githubusercontent.com/assets/1119821/7480321/a7c0e318-f31c-11e4-807f-7d0f9a689153.png)

**Comment by davidascher** [comment]
We may need a "flag as inappropriate content" option as well as per DMCA
iirc.

**Comment by vazquez** [comment]
#### Updating UI

The vertical ellipsis discloses a modal overlay. Adding a `flag as inappropriate content` option. Re-ordering list.

##### Notes

- Pressing system back button or tapping anywhere in the grey area will remove the modal.

![make view more actions](https://cloud.githubusercontent.com/assets/1119821/7484428/426467a8-f33d-11e4-8032-5e097f06ef04.png)

**Comment by thisandagain** [comment]
Awesome. Thanks for the updates @vazquez
