### ISSUE TITLE
UX - Produce site map

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1465]
LOL @ "Site map" but it would be helpful to have an updated high-level outline of all the views for both engineering planning and UI. Doesn't need to be pretty, we could even produce it in Google Slides as to keep it easy to update by the whole team.

**Comment by xmatthewx** [comment]
Draft doc on views, nav, and transitions below. This will live in the [build deck](https://docs.google.com/a/mozillafoundation.org/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.g9180dbc48_20_21) for future reference. Comments welcome here or there. 

![webmaker_views](https://cloud.githubusercontent.com/assets/53411/7009799/ca95c1a6-dc6a-11e4-8c57-88e0eca78fb5.png)

**Comment by xmatthewx** [comment]
cc @flukeout @vazquez @k88hudson @gvn @Pomax @secretrobotron @LauraReynal

**Comment by thisandagain** [comment]
Looks great. Thanks for pulling this together @xmatthewx

**Comment by LauraReynal** [comment]
Thanks @xmatthewx this is great !

**Comment by k88hudson** [comment]
Looks good to me. This is missing the login/sign up states, wherever in the flow that happens – is that intentional?

**Comment by xmatthewx** [comment]
Sorry 'bout that. Latest version will always be in the [build deck](https://docs.google.com/a/mozillafoundation.org/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.g9180dbc48_20_21). It shows where signup/login hooks in, but doesn't detail that flow.   

![webmaker_views](https://cloud.githubusercontent.com/assets/53411/7026909/a9d879c6-dd1a-11e4-95e5-26ed08d4f3ef.png)

**Comment by k88hudson** [comment]
Cool, thanks!

**Comment by davidascher** [comment]
Looking at that map it's not clear to me how one gets back to the
discover/play home page from the project page.
