### ISSUE TITLE
v1 - Add JS tests

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1468]
As per the work done in the last two heartbeats with Mocha, Phantom, and React Testutils. :smile:

**Comment by gvn** [comment]
@thisandagain : Since this is kind of a generalized ask, do you have any objection to moving it out of this sprint?

**Comment by thisandagain** [comment]
Nope. Actually I'm just going to close this and we should replace with detailed testing requirements (multiple tickets). Thanks for the follow-up.

**Comment by gvn** [comment]
:+1:
