### ISSUE TITLE
v1 - Persist state onDestroy of WebView

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1470]
via @k88hudson 
"If you go from section 1 > 2 > 3 and then back to 1, the Webview in section 1 seems to reload"

**Comment by thisandagain** [comment]
Allowing the OS to destroy the WebView when the fragment is destroyed is the right thing to do, my assumption is we'll want to resolve this in the data model rather than trying to keep WebViews in memory.

**Comment by k88hudson** [comment]
Agreed!
