### ISSUE TITLE
UI - Edit Element View

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#1473]
Finalize UI design for the mobile project edit element view based on UX from @flukeout and @sabrinang.
---

I have a view of the Editor now, without Tinker mode designed. I will tackle that next. Let me know what you think.

Both Marvel and InVision have been updated.

Leave UI Feedback: http://invis.io/BK2M18Q28
Marvel Prototype: http://marvl.in/ee2f0e

![edit element](https://cloud.githubusercontent.com/assets/1119821/7011832/7782ab0e-dc7a-11e4-85b5-f300e94088b0.png)  

![edit element opacity](https://cloud.githubusercontent.com/assets/1119821/7011836/7a29ea52-dc7a-11e4-8cf9-dc6e57db9904.png)

cc @thisandagain @xmatthewx

**Comment by vazquez** [comment]
Addressed feedback and made element editing light theme alongside other changes.

![edit element light](https://cloud.githubusercontent.com/assets/1119821/7032439/ceed4522-dd40-11e4-9cff-16a0e05316c4.png)

Started on Tinker Mode, with a dark theme to allow for the invoking of the powerful wizards of code.

Leave UI Feedback: http://invis.io/BK2M18Q28
Marvel Prototype: http://marvl.in/ee2f0e

![border colour tinker mode 1](https://cloud.githubusercontent.com/assets/1119821/7032505/117def4a-dd41-11e4-8597-ed22ab99bb91.png)  

![border colour tinker mode 2](https://cloud.githubusercontent.com/assets/1119821/7032515/1c49d1b4-dd41-11e4-8749-f59ba2508953.png)

Leave UI Feedback: http://invis.io/BK2M18Q28
Marvel Prototype: http://marvl.in/ee2f0e

cc @xmatthewx @thisandagain @flukeout

**Comment by thisandagain** [comment]
Awesome. Great progress. Do you folks have any benchmarks for the color picker / dropper on mobile that you think are great? I haven't seen a single one that I like yet aside from Paper (https://www.fiftythree.com/paper) and I worry this implementation is very desktop / mouse-centric.

**Comment by vazquez** [comment]
I'm worrying about the same thing actually. The touch targets are small but
making them bigger obfuscates the colour gradient. What we could do is
reveal a loupe similar to when you select text in iOS.

On Tuesday, April 7, 2015, Andrew Sliwinski <notifications@github.com>
wrote:

> Awesome. Great progress. Do you folks have any benchmarks for the color
> picker / dropper on mobile that you think are great? I haven't seen a
> single one that I like yet aside from Paper (
> https://www.fiftythree.com/paper) and I worry this implementation is very
> desktop / mouse-centric.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-app/issues/1473#issuecomment-90719885>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by thisandagain** [comment]
True. I guess I'm curious if this is the right paradigm... LOTS of history and different options to draw from when it comes to color selection UI design:

http://paletton.com/#uid=15C0u0kllllaFw0g0qFqFg0w0aF
http://www.flatuicolorpicker.com/
https://maniacdev.com/2011/11/open-source-ios-color-picker-components-roundup
https://github.com/hayashi311/Color-Picker-for-iOS
http://stackoverflow.com/questions/21981640/how-to-add-a-color-picker-to-an-ios-app-xcode-5
etc.

**Comment by vazquez** [comment]
Yes, I think a different paradigm might be simpler to visually digest. From
a UI perspective, hayashi's examples allow the user to intuitively
understand the tool. The examples have also eliminated the need for a hue
slider, which would make the UI less information dense.

Matthew and Luke, what do you think?

Ricardo

On Tuesday, April 7, 2015, Andrew Sliwinski <notifications@github.com>
wrote:

> True. I guess I'm curious if this is the right paradigm... LOTS of history
> and different options to draw from when it comes to color selection UI
> design:
>
> http://paletton.com/#uid=15C0u0kllllaFw0g0qFqFg0w0aF
> http://www.flatuicolorpicker.com/
>
> https://maniacdev.com/2011/11/open-source-ios-color-picker-components-roundup
> https://github.com/hayashi311/Color-Picker-for-iOS
>
> http://stackoverflow.com/questions/21981640/how-to-add-a-color-picker-to-an-ios-app-xcode-5
> etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-app/issues/1473#issuecomment-90723051>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by flukeout** [comment]
I think we can take some cues from hayashi's picker but keep the general paradigm. In that example, I like that the touch targets on the slider and hue grid are consistent in style and don't obscure the selection you're making - can you try that in your UI?

I also like a preview swatch, which we could place next to the HEX or RGBA value in your design. We'll also get a live preview of the element as you update the color.

The hayashi picker still ends up relying on a slider & 2d plane, just for different aspects of the color - so I'm okay with moving forward with that paradigm.

As an alternative, we could try the 3 slider approach of hue / saturation / lightness - which I really like. It's also a 'learning moment' because it introduces some color concepts, even if we don't use the HSL color model rule. That would be my other choice for further exploration.

**Comment by xmatthewx** [comment]
Swatches and HSL sliders ultimately give people more control than relying on a 2d plane. 


#### hyrbrid 

![screenshot 2015-04-07 17 38 19](https://cloud.githubusercontent.com/assets/53411/7034098/25bd2bea-dd4d-11e4-82a9-cd25ea541a9a.png)

#### circle + 2d

 - A circle for hue effectively gives you a longer slider for more control. yay π!  :cake: 
 - For 2d, I like how this puts white/black on the up/down axis. 

![screenshot 2015-04-07 17 28 28](https://cloud.githubusercontent.com/assets/53411/7033914/b7f72a80-dd4b-11e4-9ee6-d7ac67c5df39.png)

#### slider

 - This slider doesn't obscure selection

![screenshot 2015-04-07 17 29 45](https://cloud.githubusercontent.com/assets/53411/7033912/b7f3f5ae-dd4b-11e4-9928-9e90dd2f7914.png)

**Comment by xmatthewx** [comment]
Done for the image and text elements. 

Discussion about color picker continues in #1528
