### ISSUE TITLE
Improve prototypes for testing in Chicago

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#1502]
Hey @xmatthewx @flukeout @vazquez 

@sabrinang and I did our first testing today with the 2 prototypes, and it would be great if we could make a few changes asap for our testing. Here are some feedbacks.

* The experience is fragmented, and therefore confusing.
We show 2 different prototype, and none is complete - 1 is the zoom, 1 is the edits. Would it be possible to either have one experience that communicates the different elements to test (zoom + tinker + ...) or have 2 prototypes but with the same content so that users understand we are talking about the same app (Tucker, fowers and receipes) ? 

* Flukeout's prototype is good for showing the zoom but its difficult to navigate, so the user (and us) gets lost.
    - Could we organize it or is this on purpose ? sometimes you swipe within pages and you have blank pages, it looks broken and does not communicate the relationship between pages (ie telling a story)
    - The receipe one highlights the utility aspect, but it appears at random times when you refresh the page. 
=> Can we have it on a separate prototype ?
*  Ricardo's prototypes takes a lot of screen space because there is a phone wireframe => Extra status bar and navigation. Could we take them out ?
   - If possible, can we add text on the Tucker screen so that its shows the different components you can add in a page ? Right now it feels like the only thing you can use are images. 

Let us know if this would be doable ? As soon as you guys ship stuff, we can test them the day after :)
Any idea or suggestions are welcome! Thank you very much :cat: :joy_cat: :koala:

**Comment by xmatthewx** [comment]
@LauraReynal - We will try and make some easy improvements, but it won't be possible to create a single prototype that integrates everything. 

I realize this trip is like taking a step backwards from your previous trips. You have more to talk about, but less to show. 

 - @flukeout updated [tiles-nav-2](http://flukeout.com/examples/tiles-nav-2/) with more clean content.
 - I will try and fix Ricardo's and remove the phone status bar and nav.
 - At the end of this week, we can see how much the engineers accomplished, and whether they have something that you can use next week. 
 - In London, we will have a better chance to test a more fully functional experience. 
 - On this trip, you will likely need to lean more on your paper based test. 
 - You can also use the app from your previous trip to talk about what people like to make and share in general. The new tool will be like a multipage version of that app with more freedom with layout. 
 - You could also use PicCollage to learn a lot about the new making experience. The new tool will be a multipage version of that.

**Comment by LauraReynal** [comment]
Other links from Luke

[14/04/2015 14:49:12] Luke Pacholski: http://flukeout.com/examples/tiles-nav-2/?project=yams
[14/04/2015 14:49:19] Luke Pacholski: http://flukeout.com/examples/tiles-nav-2/?project=atkins

**Comment by LauraReynal** [comment]
@xmatthewx ok for the prototype work, no problem. Just checking to see what we can test 

@flukeout do you think we could have an example (it can be a static mockup) of some more serious content ? I think it would be interesting to check out what a blog would look like for example. 

Let us know if this would be doable without taking most of your time. I'm thinking a "Welcome to Chicago travel blog" or anything you feel like testing.

**Comment by xmatthewx** [comment]
@LauraReynal here's an improved version of @vazquez's  prototype removing the status bar and android buttons. http://marvl.in/f8hj9j. Save to homescreen and open for fullscreen mode.

@flukeout - take it for quick spin for oops'es

**Comment by xmatthewx** [comment]
You can now get to atkins and yams and eventually new projects at http://flukeout.com/examples/tiles-nav-2/load.html

**Comment by flukeout** [comment]
@LauraReynal The link above is the one you want to "Add to Homescreen" - from there you can access all three content types. Give it a little time after you choose a project, it takes a while to load.

**Comment by xmatthewx** [comment]
@sabrinang - feel free to make a project. just send image files to @flukeout that roughly match the proportions of the yams project.

**Comment by flukeout** [comment]
The tiles size I'm using is 350 x 420

**Comment by davidascher** [comment]
@flukeout: known that http://flukeout.com/examples/tiles-nav-2/index.html
doesn't work in Firefox?

**Comment by sabrinang** [comment]
![screen shot 2015-04-20 at 8 20 49 am](https://cloud.githubusercontent.com/assets/2492510/7230754/7e2c847c-e736-11e4-9c67-204e67bb1117.png)
![screen shot 2015-04-20 at 8 21 04 am](https://cloud.githubusercontent.com/assets/2492510/7230755/7e37b9a0-e736-11e4-8ce6-e185b8a2ad2e.png)
![screen shot 2015-04-20 at 8 21 15 am](https://cloud.githubusercontent.com/assets/2492510/7230756/7e4386cc-e736-11e4-88f2-faf1cc15b1f3.png)

I made some example projects, if you can put them in as examples that'd be great.
@flukeout I have all the image files exported at 350x420 here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efjQ4M1Vjd0VKb01TR0d5WU1yUHQwdkVZT1ZrZGY1MU5RSG1jU2VMR2RyQXc&usp=sharing

**Comment by flukeout** [comment]
@sabrinang Awesome, I'll get these ported over!

**Comment by xmatthewx** [comment]
@sabrinang - these are great. A good range of things you read in different ways. 
cc @flukeout

**Comment by flukeout** [comment]
@sabrinang Can you provide a UI and Background color for these?

![image](https://cloud.githubusercontent.com/assets/25212/7241386/76e00068-e76d-11e4-83a1-ac52e5874e09.png)

**Comment by xmatthewx** [comment]
@flukeout - let's use the app blue for @sabrinang's content. We might not launch with custom project colors. We don't have UX for that yet and the engineers have a lot on their plate. :fork_and_knife:

**Comment by flukeout** [comment]
Sounds good.

**Comment by flukeout** [comment]
@davidascher Works in FF now too.
