### ISSUE TITLE
Discover - Implement Project component and discovery list

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1508]

**Comment by thisandagain** [comment]
@vazquez Can you add the final design, sketch file, and any implementation notes in here?

**Comment by xmatthewx** [comment]
Here's the UI thread #1451.
@vazquez - bump final artwork here  
@flukeout - hop in with any notes

**Comment by vazquez** [comment]
##### Sketch File Download
https://dl.dropboxusercontent.com/u/43783651/Mozilla/Webmaker%20App%20Segmented%20Files/Discover.sketch

##### Notes

- The tab bar navigation is discussed a bit more in detail in #1604. 
- This design follows the [Card Component](http://www.google.com/design/spec/components/cards.html#) paradigm as shown in Google's Material Design. 
- The user scrolls top to bottom to view new Projects. 
- When tapped, a [Parent to Child](http://www.google.com/design/spec/patterns/navigational-transitions.html#navigational-transitions-parent-to-child) navigation transition occurs. 
- The user can tap on the Author's name to access their Profile (this design is not complete)


##### Final Design
![discover view](https://cloud.githubusercontent.com/assets/1119821/7398422/e76f31ee-ee7c-11e4-8b4a-e74c5b916cf8.png)

**Comment by thisandagain** [comment]
@vazquez Do we have a design for pull to refresh spec'd out yet?

**Comment by thisandagain** [comment]
@vazquez Also curious if you have an offline / no connection state ready here.

**Comment by vazquez** [comment]
@thisandagain None for both of them. But I do have a nice offline/no connection design that I can bring from the previous iteration.

![discover view no connection](https://cloud.githubusercontent.com/assets/1119821/7430126/2a66aa30-efdc-11e4-8580-ea59f6d9174f.png)

**Comment by xmatthewx** [comment]
Pull to refresh was listed as Beta 2/2 in the roadmap. I'm curious what aspects of it is defined/designed by Android, and what aspects we need to provide. #1540

**Comment by thisandagain** [comment]
@vazquez Perfect! Thanks.
@xmatthewx Ah ... good catch. I'll do some digging in the material APIs for you.

**Comment by thisandagain** [comment]
Resolved in #1622
