### ISSUE TITLE
Map	Prototype

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1513]
Produce map view prototype to test performance. 

I believe this is nearly complete. Next:
 - implement '3 across' zoom state
 - iterate on IxD to match @flukeout's prototype
 - test within Android wrapper

**Comment by flukeout** [comment]
IxD described here
https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.g98904dc8c_6_0

**Comment by xmatthewx** [comment]
Great. Details are clear. 

Question: in page view, can user nav to empty space marked with [+] and add a tile? Is the nav 'error' for these [+] neighbors or the blank space beyond?

**Comment by flukeout** [comment]
In edit mode, when zoomed in to a single tile, you can swipe to an adjacent (+) tile and create a tile by tapping it.

I'll create two sets of specs, one for Edit and one for Play.

**Comment by thisandagain** [comment]
Tracking in #1514
