### ISSUE TITLE
Implement map view front-end

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1514]
Work started in #1504

**Comment by flukeout** [comment]
Early feedback on @gvn's work:
* [ ] Start map in 'middle zoom' by default
* [ ] Slow down transition when adding a new tile. Add in the new tile and (+), then pan over
* [ ] Make map pannable on 6-up and 3-up views

**Comment by gvn** [comment]
I just edited your previous comment. I think for *alpha* we should prioritize missing/broken functionality over aesthetic updates.

**Comment by flukeout** [comment]
@gvn Sounds good, I'll use that comment above to add new items as I find them.

**Comment by xmatthewx** [comment]
- [UI comps](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae0e362d5_2_52)
 - [UX notes](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae931fbd6_7_20) (2 slides)

**Comment by gvn** [comment]
@xmatthewx Are there unflattened versions of these comps available?

**Comment by xmatthewx** [comment]
@vazquez has collected the icons. Let's share them via gDrive.

**Comment by vazquez** [comment]
I have placed all Icons in `svg` format are available in Google Drive. 

WMA > Version 2.0 >  icons

@gvn Is this what you need?

**Comment by gvn** [comment]
That's helpful, but I really appreciate a source/unflattened version of any comp I'm building so that I can get in and measure things more accurately.

**Comment by gvn** [comment]
Also can you please just attach directly to the ticket? It's much easier for me to locate that way...

**Comment by vazquez** [comment]
I can't upload Sketch files so here is the link: https://www.dropbox.com/s/alb2u2xroin6mmx/Map%20View.sketch?dl=0

I added a couple of extra screens just for context. I also added Icons as you will need them.

:rocket:

**Comment by k88hudson** [comment]
Hey everyone, I spoke to @xmatthewx, @flukeout, and @vazquez about the flow for the editing view for the 6-up, 3-up, and 1-up zoom levels, I just wanted to post my summary here so we've got a unified record of what the flow is

https://drive.google.com/file/d/0B9Spnx3qAl7pamtRQTJfLUg2elE/view?usp=sharing

Let's discuss at stand up.

**Comment by k88hudson** [comment]
cc @thisandagain

**Comment by k88hudson** [comment]
Summary of technical issues we also need to discuss:

* mapping cartesian coordinates / perf issues
* "double taps"
* zoom states / cannonical size
* transitioning from map view => page editor

**Comment by thisandagain** [comment]
Just to follow-up from the stand-up:

- @flukeout is going to put together a proposal for how we might do a more conventional pinch zoom for the map view. We'll review and make a decision tomorrow.
- @k88hudson has an updated branch that uses Cartesian coordinates and helps with some perf issues on the existing map view spec
- Depending on the approach we choose, we'll need to discuss the transitions tomorrow
- We didn't cover double taps at all ... we can discuss tomorrow

**Comment by gvn** [comment]
For the transition to page editor, I was thinking a horizontal slide right to enter and a slide left to exit might feel good.

**Comment by flukeout** [comment]
@gvn @xmatthewx First pass on Zoom UX for Edit View
https://dl.dropboxusercontent.com/u/109902/tiles/zoom-ux.pdf

**Comment by gvn** [comment]
Anyone think we should break this up into smaller tickets now?

**Comment by thisandagain** [comment]
:+1: Let's do it. :boom:

**Comment by thisandagain** [comment]
@flukeout can you create individual `bug` tickets for each of your unresolved comments?
