### ISSUE TITLE
Implement page front-end

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1515]
Ability to add and transform text element and images (via URL only - a temporary feature).

 - [add element ui](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae0e362d5_2_128)
 - [image selected](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae0e362d5_2_114)
 - [text with bounding box transform](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae0e362d5_2_96)

**Comment by Pomax** [comment]
current "live" version up on http://pomax.github.io/webmaker-app/pages/project/ with PR https://github.com/mozilla/webmaker-app/pull/1538

**Comment by flukeout** [comment]
Some feedback:
* [ ] Often the "shadow" of the element will disconnect, and the gestures only affect the shadow
* [ ] Rotation gestures where both fingers rotate around a point between them produce unexpected results
* [ ] It's possible to pan things off of the tile area, and not grab them again while seeing their shadow
* [ ] When an element is selected, I should be able to deselect it by tapping on empty space in the tile
* [ ] Can we show a 'trash' icon when an element is selected and be able to delete the elemetn?
* [ ] Elements 'jump' a little bit after rotating them, removing second finger, and panning
* [ ] Can we show the 'clipped shadow' only when an element is selected? 
* [ ] We are working under the assumption that a 'swipe' gesture will transition pages, but right now the 'swipe' is being interpreted as an element move if you swipe over an element - we need to resolve this

**Comment by xmatthewx** [comment]
[UI comps](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae0e362d5_2_74)

**Comment by k88hudson** [comment]
I'm going to work on this for a bit if that's OK

**Comment by xmatthewx** [comment]
Page editor interactions need to be optimized. 

**Problem**: User can't deselect an element if their page is piled high with many elements. Add-element button is replaced with pencil. Tap to deselect element would force us to reconsider how we handle z-index. Tapping outside page collides with nav between pages ux-wise.

**Proposed solution**: Keep buttons stationary. Align background color & edit element since they are variations on the same thing. 

![page interactions](https://cloud.githubusercontent.com/assets/53411/7436569/de755be4-f01c-11e4-9d07-ce92d52fbe0d.png)

**Comment by thisandagain** [comment]
Major :+1: on the proposed solution. :smile:

**Comment by thisandagain** [comment]
Only thing (not related to your solution) that feels a little odd is that we have two identical "trash" icons on the same view that two very different things. /cc @xmatthewx @flukeout

**Comment by xmatthewx** [comment]
cc @vazquez 

My gut says the position of page trash makes this ok. My head says we should wait to address this after testing. Previously page delete was X, but that felt too ambiguous.

**Comment by xmatthewx** [comment]
Sorry to clutter the conversation. But, if this is easy, let's add undo. If not, I'll add an issue for the backlog. 

![delete](https://cloud.githubusercontent.com/assets/53411/7436796/df4bfce2-f01e-11e4-895e-73584d9f14dd.png)

Android specs: http://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-usage

**Comment by thisandagain** [comment]
@xmatthewx Totally fair. Re: undo. Totally agree it's needed, but let's add to backlog.

**Comment by Pomax** [comment]
https://github.com/mozilla/webmaker-app/pull/1611 landed, which improved the touch handling for the project view

**Comment by k88hudson** [comment]
This is complete IMO, further issues are filed separately.
