### ISSUE TITLE
Element attribute UI - text and image

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1516]
Finalize UI for any missing [attributes](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.ga9196a78b_043) and interactions

 - text style: bold, underline, italic
 - available fonts and preview in selector
 - text editing
 - ~~image source selector~~

**Comment by xmatthewx** [comment]
We will want to offer users a handful of fonts to use in their projects. 

What tech should guide our design choices? Does Android include a bundle? Will we include a bundle? Should we rely on google fonts or another web service? 

cc @thisandagain @Pomax @gvn @cadecairos @simonwex @jbuck

**Comment by vazquez** [comment]
@xmatthewx has explored Google Fonts. I support this, since licensing wouldn't be a problem if we use Google Fonts.

**Comment by vazquez** [comment]
From my research, Android only provides Roboto and Noto font families.

**Comment by vazquez** [comment]
This is the progress that I have for today.
Leave UI Feedback: http://invis.io/BK2M18Q28

I added text style option, and I took a stab at choosing some font families. Slab font, serif, sans serif, display, handwritten.

![text options](https://cloud.githubusercontent.com/assets/1119821/7261623/40ed1bd8-e841-11e4-861d-cc7070c97e1e.png)

![text options dropdown](https://cloud.githubusercontent.com/assets/1119821/7261629/444ea850-e841-11e4-9c02-dad82c741333.png)

**Comment by xmatthewx** [comment]
Nice work. Comments in [invision](http://invis.io/BK2M18Q28).

**Comment by vazquez** [comment]
Closing this. All comments have been addressed in InVision.
