### ISSUE TITLE
Implement element / attribute front-end

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1518]
Text element + image element only. For alpha, image src set via temp URL modal.   	

 - UI for [image attributes](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae0e362d5_2_114)
 - UI for [text attributes](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae0e362d5_2_96)

**Comment by vazquez** [comment]
### Design Documentation

##### Image Attributes Screen

The Image Attributes Screen allows the user to set control of the following:

- Changing the Image
- Transparency
- Corners (which we refer to as border radius)
- Border Colour
- Border Thickness

###### Notes

- The user is presented with sliders that allow for the modification of values. At the right hand side of the slider, an updating value is shown in `px` values. The opacity of the value changes if it's not the minimum. As an example, if the Corners value is set at 0px, then we reduce the opacity of the number to decrease the cognitive load of the user. However, as soon as Corners is set to 1px/5px/any value, we change the opacity of the number to 100%.

- To confirm changes, the UI uses the [Element Options Navigation](https://github.com/mozilla/webmaker-app/issues/1604) in which the user needs to tap the check-mark to confirm changes.

- Border Color has a small circle inside the colour that is presently selected.

- *Nice to have:* In the case that the options are too long to fit in the screen, it would be really nice if we could hide the content underneath the Preview screen.

![edit element opacity](https://cloud.githubusercontent.com/assets/1119821/7462752/cf6714f0-f268-11e4-8a48-64997a75773c.png)

---

##### Text Attributes Screen

The Text Attributes Screen allows the user to modify the following:

- Text Size
- Font Family
- Color
- Text Style
- Text Alignment

###### Notes

- The Font Family selector acts as a [Material Design dropdown list](http://www.google.com/design/spec/components/menus.html#menus-behavior). It's pretty much the same as a normal dropdown except it looks just a little bit different.
- The user has the freedom to select the text to be bold AND italicized AND underlined.
- The user can only select one text alignment property. As an example, the text cannot be left aligned AND right aligned.
- Selected states for Text Style and Text Alignment is represented by a blue 'active state', as shown below.

![text options 2](https://cloud.githubusercontent.com/assets/1119821/7462955/79d643a6-f26a-11e4-8727-f9c3b53ae50c.png)

##### Text Options with Dropdown selected

- Every font shown here is accessible through Google Fonts.

![text options dropdown](https://cloud.githubusercontent.com/assets/1119821/7463148/d1d6d1aa-f26b-11e4-8dda-17e85a7e6f99.png)

##### Text Options Text Selected

- If the user taps on the text in the Preview window, the keyboard will disclose and the user will be able to edit the text.

![text options edit text](https://cloud.githubusercontent.com/assets/1119821/7463188/27794430-f26c-11e4-85ca-3061ae0568bc.png)

**Comment by k88hudson** [comment]
done
