### ISSUE TITLE
Design Play UI

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1519]
The Play experience for visitors will be slightly different from the editor view. @vazquez discuss content experiments with @flukeout for insight.
 - slide to hide header on page view for immersive experience
 - increase fidelity of floating tool buttons over noisy content in map view
 - consider pulling share and remix actions from ellipses menu for more accessibility

**Comment by xmatthewx** [comment]
see https://github.com/mozilla/webmaker-desktop/issues/27 for more discussion

**Comment by xmatthewx** [comment]
depends on #1511

**Comment by xmatthewx** [comment]
@vazquez - add your final screens to [this slide in the build deck](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.g99832357e_3_7). Add notes for implementation and close this issue.

**Comment by vazquez** [comment]
I added the Play zoomed out (6 tile arrangement) view to the deck. I feel like I'm missing something though.

**Comment by xmatthewx** [comment]
As long as you have a version of Map view for both play and edit, and a version of Page view for play and edit, we should be good to go. In the build deck, these might be a bit mixed up.

**Comment by vazquez** [comment]
Ok, I think we're good to go then.
