### ISSUE TITLE
UX for image element source

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1523]
UX for image selector (photo, gallery, uploader) is probably done already. Review and add clean set of notes to the build deck.

**Comment by xmatthewx** [comment]
Consider in tandem with loading indicators #1540

Will camera and gallery failures be handled by Android? cc @thisandagain

**Comment by flukeout** [comment]
Super rough UX for Web Image Search.

**Questions**
* What other Options are important
* Can we pre-populate the results?
  * Previous searches
  * Last used in other project

![image](https://cloud.githubusercontent.com/assets/25212/7359184/6c3a6b7a-ecf0-11e4-88a5-c5ba7d1c4d6b.png)

**Comment by xmatthewx** [comment]
We should have @cadecairos investigate search services after he finishes his other API work to help figure out these parameters.

**Comment by thisandagain** [comment]
I'd prefer to keep this UX exploration constrained to what is in-scope for v1.0 as we have a pretty heavy workload already.

**Comment by xmatthewx** [comment]
@flukeout - for camera and gallery selector on mobile, can we call this done? I filed issue for search in the desktop repo. 

I'm assuming that camera and gallery failures will be handled by Android. Notice for upload failures tracked in #1540

**Comment by thisandagain** [comment]
Yup, we'll use the OS-level camera and gallery. Building up that SOW in #1615

**Comment by flukeout** [comment]
Closing since not currently in scope, we'll make a new ticket down the road.
