### ISSUE TITLE
UX for button link element

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1524]
UX includes:
 - set destination
 - style
 - notes on tap to edit vs use while in editor

Documented on [two slides](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gacde6376b_0_82) in the build deck. Review before we jump to UI. 

Note: Button icon or shape selector is probably post RC1

**Comment by flukeout** [comment]
@xmatthewx I feel like the UX described in the build deck is solid - do you see any gaps to address?

**Comment by xmatthewx** [comment]
I think it's solid. We'll have to revisit later this year to add more flexibility in button style.

**Comment by flukeout** [comment]
@xmatthewx I'll add a quick note to the build deck about the transition details when you use a button in Play Mode.

**Comment by xmatthewx** [comment]
Although... is there a way to follow the link while in the editor?

**Comment by flukeout** [comment]
```Desk 8``` shows a way to tackle it - first tap selects it, second tap follows the link. Alternatively, you may have to switch to Preview mode. Either way, I'll update the deck.

**Comment by xmatthewx** [comment]
When an element is selected, a tap needs to move the item to the top of the z-index. 

Maybe we add a button below. When unset, that button could trigger the destination picker. 

![screenshot 2015-04-24 13 52 20](https://cloud.githubusercontent.com/assets/53411/7324994/261d6a7a-ea89-11e4-9b8c-a77d49dd680b.png)


cc @vazquez

**Comment by flukeout** [comment]
Another, similar option is what google drive does.
When you click the link, you get an option to modify or follow.

Also - I'm not convinced about tapping to bring things forward. It doesn't solve things being stuck behind other things. Something we should consider.

![image](https://cloud.githubusercontent.com/assets/25212/7326353/849ba32e-ea79-11e4-9689-e073ae45d0bc.png)

**Comment by xmatthewx** [comment]
I like the follow link button. Could be used to set destination of a new link too, so it's not buried in the edit view.

**Comment by xmatthewx** [comment]
If someone deletes a destination page, I suggest we don't do anything fancy. At most, just unset button and show "Set link" rather than "follow link"

@flukeout - review @vazquez's UI work on this #1549. Any UX gaps? If not, let's call this done and close this issue.

**Comment by flukeout** [comment]
Work in #1549 looks good UX-wise to me. We had some UI feedback during our crit, but this ticket here is done.
