### ISSUE TITLE
UX for color tinker mode

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1525]
UX is documented in the [build deck](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.g98904dc8c_9_4). 

Should also include:
 - notes on most recent tinker colors available as non-tinker swatches
 - integration with tile background color picker (not yet spec'd)

**Comment by flukeout** [comment]
@xmatthewx @vazquez I'm leaning towards doing a slider-based tinker mode - I don't think we'll have the engineering capacity for a full-fledged color picker like the one in the UX spec so far. 

![image](https://cloud.githubusercontent.com/assets/25212/7309549/b99a4a4e-e9d4-11e4-80ff-b030c67f109f.png)

In the UI we can show the various values on the sliders themselves, like here:
![image](https://cloud.githubusercontent.com/assets/25212/7309567/e7c95f0e-e9d4-11e4-9755-0619007621aa.png)

The one reservation I have is that we're using hex as a default, and this doesn't map as nicely to it.

**Comment by xmatthewx** [comment]
Engineering with sliders to start makes sense. Finding the right picker shouldn't be impossible. 

Here's one I dug up we could refactor: http://jsbin.com/gewehiyepe

![screenshot 2015-04-24 11 18 52](https://cloud.githubusercontent.com/assets/53411/7322076/ba4fbbe6-ea73-11e4-8121-de37dbd2cfae.png)

**Comment by flukeout** [comment]
@xmatthewx is that really #123456? Anyway agreed - it's not really about finding a suitable one, but launching with something we can reasonably accomplish.

On another note, I saw some feedback from @LauraReynal's research that challenged the kind of visual colorpickers we've been considering because they're already familiar to users and don't really teach you anything.

**Comment by xmatthewx** [comment]
:dart:  truly #123456

**Comment by LauraReynal** [comment]
The Hex color picking view that we have does not offer any challenge to the teens . 
The RGBA is a bit more difficult for them and might be more interesting to dive in. 

I guess the question is: which ever color picking we choose, how can we enhance better the learning that we want to achieve ? 
Right now it's not challenging enough to foster learning, they just see it as "choose your color" or "customize"

**Comment by xmatthewx** [comment]
We've settled on the picker in #1528 and I think that's the last open question. @flukeout - True? If so, let's close this and track anything further there.

**Comment by flukeout** [comment]
Agreed. Done.
