### ISSUE TITLE
UI - Color picker for tinker mode

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1528]

**Comment by vazquez** [comment]
Leave UI Feedback: http://invis.io/BK2M18Q28

What do you think of this?

![new image picker](https://cloud.githubusercontent.com/assets/1119821/7355581/d2f82244-ecf0-11e4-997c-c0fc914a789b.png)

**Comment by vazquez** [comment]
Here is another.

Leave UI Feedback: http://invis.io/BK2M18Q28

![new image picker 2](https://cloud.githubusercontent.com/assets/1119821/7356054/dbf084a6-ecf3-11e4-9476-cfe76bfa8ecb.png)

**Comment by thisandagain** [comment]
RGBB isn't a thing is it? It seems really confusing to have multiple values (RGB + Brightness) affecting the brightness of a color.

**Comment by vazquez** [comment]
Adobe Kuler uses RGB + B. We, however, are adding the extra Transparency slider. Maybe the sliders make things more confusing :confused:

**Comment by xmatthewx** [comment]
You're both right. It's a bit weird. Kuler has a B slider that moves RGB in sync. An attempt to give RGB control like HSL?

**Comment by vazquez** [comment]
I will give this a shot next!

![ba4fbbe6-ea73-11e4-8121-de37dbd2cfae](https://cloud.githubusercontent.com/assets/1119821/7372704/515584f6-ed96-11e4-9c4d-cdb7583b1aae.png)

**Comment by thisandagain** [comment]
Cool ... we have enough to do without reinventing color spaces. :wink: 

One scheme to look at might be HWB as it was designed to be intuitive (very similar to what is posted above):
https://en.wikipedia.org/wiki/HWB_color_model
http://fettblog.eu/hwb-colors/
http://alvyray.com/Papers/CG/HWB_JGTv208.pdf

**Comment by vazquez** [comment]
Thanks @thisandagain, good resources :)

This *does* feel a lot simpler and more intuitive.

I think I can improve the selection handles.

![new image picker](https://cloud.githubusercontent.com/assets/1119821/7376454/e1c99100-edad-11e4-95c6-fe050fb6511f.png)

**Comment by flukeout** [comment]
@vazquez Can you update the color of the value numbers in the RGBA sliders to white instead of green?

**Comment by vazquez** [comment]
Done! :rocket:
