### ISSUE TITLE
UX for project settings

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1531]
UX for project settings was listed in the roadmap as a Beta feature, but I think UX should be resolved now. Access to settings shuffled around in previous heartbeats but was never resolved in https://github.com/mozilla/webmaker-desktop/issues/12

Proposal:
 - settings are accessed exclusively from the within a project (not Make view).
 - settings are accessed via the vertical ellipses menu button ⋮
 - Menu = 
  - ~~Preview~~ Play [1]
  - Share Project
  - Project Settings
 - Settings view = 
  - Title Field
  - Delete project

Out-of-scope for v1 (unless we get ahead of schedule):
 - Set start page
 - Set preview
 - Set project colors
 - Project description

Play view needs UX/UI to share and edit (authors) or remix (others). Earlier designs included an easy to toggle preview. We have moved away from that. Should only revisit if testing shows we need it after we've resolved other RC features. 

cc @flukeout @vazquez 

edit: moving Description out of v1

**Comment by thisandagain** [comment]
Unless we have a really strong story for how it will be displayed to viewers in the consumptive experience of the project I suggest we omit the project description for 1.0. The moment we add comments in 1.1 we'll want to move the description into the discussion thread anyway.

**Comment by xmatthewx** [comment]
:+1:  that's my preferences. As I mentioned in the api discussion, I think descriptions add friction to quick, fun projects.
