### ISSUE TITLE
UX for refresh & progress indicators 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1539]
Identify places in the app where we need to deal with loading/uploading, empty state and progress, pull to refresh ... such as adding images and project lists in Discover. Define specs for a smooth and confusion free experience. 

 - http://www.google.com/design/spec/patterns/swipe-to-refresh.html#
 - http://www.google.com/design/spec/components/progress-activity.html#

**Comment by flukeout** [comment]
To start, listing some places where we might need to address these/
By the way, I like that indeterminate to determinate progress indicator from the google spec.

**Refresh**
* Pull down on Discover view to refresh

**Load & Progress**
* Loading Discover view
* Opening a Project / Loading all images & assets in an opened project
* Signing In
* Loading an image
* Populating Image search results

**Comment by xmatthewx** [comment]
Any failures for background processes?

**Failures**
 - project fails to save to server
 - image fails to upload

**Comment by thisandagain** [comment]
We can probably do the API failures in-line (see: Twitter, Instagram, Vine, etc. etc. for tons of benchmarks). Image upload status (progress bar) and failure notifications are the biggest thing I'm worried about here.

**Comment by xmatthewx** [comment]
When users add an image from their gallery, they'd expect to use it immediately while it uploads in the background. If we need it, an unobtrusive progress indicator would be ideal. Something like this?

![uploading](https://cloud.githubusercontent.com/assets/53411/7432912/4dc4f3c4-effa-11e4-9358-abd755a2b3c8.png)

**Comment by thisandagain** [comment]
This feels pretty good. I'm curious if we should have a persistent loading indicator elsewhere as well. For example, what happens if a user presses back while in this view and starts another page?

**Comment by flukeout** [comment]
Expanding on @xmatthewx's idea by adding a project-wide persistent uploading / syncing indicator that also blocks the "Share" action, which makes sense because the project isn't ready.

Just realized that the "Project Settings" action should still be accessible though.

![image](https://cloud.githubusercontent.com/assets/25212/7465002/fd8a67e6-f27d-11e4-9920-1195e103831b.png)

**Comment by flukeout** [comment]
Expanding on @xmatthewx's idea.

![image](https://cloud.githubusercontent.com/assets/25212/7465073/089f2080-f27f-11e4-95f5-1a5ce8d23899.png)

I also think we should grey out the Share option in the project menu until everything is uploaded. It makes sense to prevent sharing until the project is actually ready to be shared, right?

![image](https://cloud.githubusercontent.com/assets/25212/7465095/5e10c73a-f27f-11e4-982f-3ccef20e827d.png)

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/7465653/167481c8-f289-11e4-9117-8378a0c3b123.png)

**Comment by flukeout** [comment]
Here's an ugly first pass at **Initial Load**

![image](https://cloud.githubusercontent.com/assets/25212/7465820/ccb250ac-f28c-11e4-9983-6782555db2a0.png)

**Comment by xmatthewx** [comment]
Good progress. Pun intended. 

Idea: if we animate the arrival of each page with a pop, it could be fun to watch a project load and reveal itself on the map. Slow loading would be less frustrating. 

A couple of thoughts: 
 - Loading and refresh things all look right
 - I like the position of your indicator in the header
 - Spinner on image seems redundant with gray mask
 - Good catch on sharing concern. I'd rather not block sharing. Too valuable. Instead, we could have a nice placeholder for broken images in Play view.

**Comment by flukeout** [comment]
Here are some options for the Initial Load experience, starting zoomed in to the start tile which should be the default view based on testing.

![image](https://cloud.githubusercontent.com/assets/25212/7484106/f293a85e-f339-11e4-9e04-0e25b148add9.png)

**Comment by xmatthewx** [comment]
Option 1 - showing background color will be quick and feel responsive
~~Option 2~~ - could take too long for big projects or slow connections
Option 3 - we could pop in the color and then content. we might buy ourselves a second with animation
~~Option 4~~ - this might feel broken

Can a visitor zoom out while they wait? Or is zoom disabled?

Worth a quick prototype? Let's discuss.

**Comment by flukeout** [comment]
Moved discover page to #1677
