### ISSUE TITLE
UX - spec Android back button 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1545]
Define how system back button should behave. 

Here's a first attempt:
 - dismiss dialogs
 - close keyboard
 - back to prior tab (make/discover) 
 - back to prior view (from user profile, tinker mode, element editor, project settings,...)
 - zoom out from page view to map view
 - zoom in ?? (I vote never)
 - exit a project (with a confirmation??)
 - exit the application only if there's absolutely nothing else to do (I've seen accidental exists intercepted with a prompt, "tap back again to exit app.")

**Comment by xmatthewx** [comment]
cc @flukeout

**Comment by flukeout** [comment]
Seems like ``back arrow to zoom out`` is the most important one - saw lots of going back to Discover view by 'accident'.

Not sure about ``back to previous tab (between make & discover)`` - seems like you'd get stuck in a cycle going back and forth? Doesn't seem like the right interaction, is that what you meant?

**Comment by xmatthewx** [comment]
> Seems like back arrow to zoom out is the most important one 

Agreed. Important and unique. 

> back to previous tab

I think it would go back to whatever you did before you hit the tab, not add your tab-via-back-button to the queue. I agree it's a bit confusing. We should just follow material design's lead on this one.

**Comment by xmatthewx** [comment]
closing. ready to implement in #1546
