### ISSUE TITLE
Play, Edit ... Tomayto, Tomahto

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1555]
The Play experience and Edit experience differ on Map view and Page view. Might be nice to make a consolidated list of those difference, so we can plan the build appropriately. 

@k88hudson @Pomax @gvn - true or false?

**Comment by k88hudson** [comment]
Personally, what would be most useful for me would be to have comps for both views attached to the respective implementation tickets.

**Comment by xmatthewx** [comment]
I brought this up because we're talking about a single view that varies a bit for [viewers](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.g98904dc8c_44_13) and [editors](https://docs.google.com/presentation/d/1ihVXe53q6U7YLKiYURKXedE5TzOW7x7iwCNeJBY4dpE/edit#slide=id.gae931fbd6_7_20) (ex: single to open vs select). I'll close this and leave it to @Pomax or whoever implements it to flag us with any questions.
