### ISSUE TITLE
Implement user project list within "Make" view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1558]
depends on UI in #1464

**Comment by thisandagain** [comment]
Because we don't have login in alpha, we should implement this without the "profile" at the top of this view.

**Comment by gvn** [comment]
Related: #1641

**Comment by k88hudson** [comment]
@xmatthewx I'm assuming we're omitting the option menu since none of that functionality exists yet?

**Comment by xmatthewx** [comment]
Will this list in alpha include the project you can make on device, or just dummy data? A "clear project" would be nice to have for testing. Not essential if it's lots of useless work. Fine to leave it out.

**Comment by thisandagain** [comment]
Resolved in ae61068
