### ISSUE TITLE
UX for sharing flow

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1561]
Consider various flows including unnamed projects, and new users w/o accounts. Design in tandem with login #1522.

**Comment by flukeout** [comment]
@xmatthewx, some quick questions?
* Why worry about unnamed projects?
  * If we have a good default starting project name, does this matter?
* Why worry about new users without accounts?
  * Do you need to have an account to share something?
* I think just a global 'share project' action is good, or do we want to share specific tiles?

**Comment by xmatthewx** [comment]
> unnamed projects

Ok. Let's figure default project titles.

> Users without accounts

I previously assumed users would be able to play around with the tool before they signed up. We've nixed that for now. So, no need to worry about users without accounts. 

> Global share

Sharing a whole project is good enough for now. 

In conclusion: Sharing will utilize Android functionality. There might not be much to figure out. Let's confirm that and close this.

**Comment by flukeout** [comment]
Yeah - @vazquez already built in the UI for sharing in the invision mock and then the native android stuff can take over. I'll mock up the play mode sharing UX, since as of right now, we don't utilize the header in the zoomed-in views.

**Comment by xmatthewx** [comment]
Share handled by Android, accessed via vertical ellipses in project header. 

![screenshot 2015-05-01 11 32 20](https://cloud.githubusercontent.com/assets/53411/7432400/c989b1ac-eff5-11e4-9181-38b8dfb810db.png)
