### ISSUE TITLE
Android WebViews load too slowly when starting an activity

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1595]
They take a while to instantiate :-1:. Let's hope we can fix this.

**Comment by ryanw-ny** [comment]
There is definitely going to be a overhead when using web view, that really isn't avoidable to a extent. I don't think this would be worth fixing because of issue #1467, which is going to migrate from web view to crosswalk anyways.

**Comment by thisandagain** [comment]
:+1: let's revisit once #1467 is landed.
