### ISSUE TITLE
Create a colors less file

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1596]
Because it makes us happy

**Comment by k88hudson** [comment]
cc @gvn

**Comment by gvn** [comment]
@vazquez - Do you have a standardized palette that you're working from?

**Comment by gvn** [comment]
Also, this palette should be represented in our built style guide.

**Comment by vazquez** [comment]
@gvn Will have something for you by the end of the day. Sorry about the delay.

**Comment by vazquez** [comment]
![colours](https://cloud.githubusercontent.com/assets/1119821/7435791/f474d99a-f014-11e4-854d-1fb963e5d56d.png)

This is the Sketch file: https://www.dropbox.com/s/fivy1fgmq5etiis/Colours.sketch?dl=0

@gvn Let me know if I'm missing any as we go along.

**Comment by gvn** [comment]
That's super awesome. I will add it to the style guide!

**Comment by gvn** [comment]
I think we should name the colors what they are instead of how they will be used since they'll undoubtedly be used for more than one purpose. I'll name the LESS variables in the build after those colors...

EG: "Light Blue", "Heather Gray", etc.

@vazquez Do you want to name them?

**Comment by vazquez** [comment]
Oh boy! :smile: Okay give me 5 minutes. Have to harness my inner colour connoisseur.

**Comment by gvn** [comment]
Definitely need a "Vivid Tangerine". :wink:

**Comment by vazquez** [comment]
Hopefully I didn't go too crazy. I provided a more common option in parentheses for a couple of them.

![colours](https://cloud.githubusercontent.com/assets/1119821/7436059/ab6d8bb8-f017-11e4-9c2b-786cc7c33c61.png)

**Comment by gvn** [comment]
That's perfect! I'll add them!

**Comment by thisandagain** [comment]
:heart: "Shadow Plum". I'll update the Android `colors.xml` to match as well.

**Comment by k88hudson** [comment]
beautiful :dancers:

**Comment by davidascher** [comment]
I think the light grey is more of a "dusty fog" myself.

(spent too much time looking at paint chips w/ Sylvia)
​

**Comment by gvn** [comment]
Adding colors in #1627.

Will still need to replace all the hard coded values in the build once it lands...
