### ISSUE TITLE
UX for z-index

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1597]
Tapping an already selected item is how I've expected us to handle shifting elements to the top of z-index stack. 

> I'm not convinced about tapping to bring things forward. It doesn't solve things being stuck behind other things. Something we should consider.  - @flukeout https://github.com/mozilla/webmaker-app/issues/1524#issuecomment-96036691

One opinionated default we could include: text and buttons should always be in front of images. This might introduce some edge case problems for authors, but it would likely solve more problems than it would cause.

**Comment by Pomax** [comment]
we can make this automatic behaviour based on a static property in the blocks used for element types. E.g. give https://github.com/mozilla/webmaker-app/blob/v1/www_src/pages/project/blocks/Text.jsx a `statics: { alwaysOnTop: true }` and then we can hook up the [zindex event handler](https://github.com/mozilla/webmaker-app/blob/v1/www_src/pages/project/Positionable.jsx#L99) to taps when the element is selected fairly easily.

**Comment by flukeout** [comment]
Here's a crazy idea. Tap + Hold an element to reveal overlay menu with Z-index control (and additional stuff like duplicating).

![image](https://cloud.githubusercontent.com/assets/25212/7423907/e8b7468a-ef4f-11e4-8e13-3823d81d65b4.png)

**Comment by flukeout** [comment]
@xmatthewx I'm okay running with tap-to-bring-to-front for now. We can see how it performs in testing.

**Comment by xmatthewx** [comment]
Cool. Closing. Tracking in #1515.
