### ISSUE TITLE
Mock API resources for testing

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1612]
Here are a few mock API resources that I've been using for testing. Not 100% complete, but far enough to start to identify rough edges throughout all of the views. These gists can be directly accessed / consumed via the `api.js` library within the app like so:

```js
var api = require('../lib/api');
api({
    uri: '/c0645e6953e9949f8e5c/raw',
    useCache: false
}, function (err, body) {
    // do some stuff
});
```

 /cc @k88hudson @secretrobotron @cadecairos 

---

#### Discover
```bash
GET – /discover
https://gist.githubusercontent.com/thisandagain/c0645e6953e9949f8e5c/raw
```

#### User
```bash
GET – /users/:user
https://gist.githubusercontent.com/thisandagain/401dc5eeeb434a6e3cf5/raw
```

#### Project
```bash
GET – /users/:user/projects/:project
https://gist.githubusercontent.com/thisandagain/59123dd736a87b21879a/raw
```

#### Pages
```bash
GET – /users/:user/projects/:project/pages
https://gist.githubusercontent.com/thisandagain/9b5549580dcb26345e97/raw
```

#### Element
```bash
GET – /users/:user/projects/:project/pages/:page/elements/:element
https://gist.githubusercontent.com/thisandagain/e54d914ea5d5b142b0ff/raw
```

**Comment by k88hudson** [comment]
A few things seem weird to me here:

* Why is the project response different from pages? Shouldn't pages just be a child of projects? (not in the DB data model, but in the API response)
* You're missing a single page response, i.e. `/users/:user/projects/:project/:page`
* You're missing a projects response, i.e. `/users/:user/projects`, although maybe this isn't for v1.

**Comment by k88hudson** [comment]
@thisandagain ^

**Comment by thisandagain** [comment]
Awesome. This is great feedback.

- Re: `/users/:user/projects` not  including pages / elements. I was getting worried about size ... we have a real use case in the discovery and make views where we need to be able to render an array of projects but don't need any of the page information. Pages and elements are not needed to render those cards and good list performance will be critical to the browsing experience.
- Re: `/users/:user/projects/:project/pages/:page`. Great catch. Will add.
- Re: `/users/:user/projects`. Another good catch. Needed to render the "make" view. Will add.

**Comment by k88hudson** [comment]
Totally agree that `/users/:user/projects` should not include pages/elements. My concern is that there's not a great use case for `/users/:user/projects/:project` (i.e., for a single project) not including pages at least.

**Comment by k88hudson** [comment]
Either that, or you should include project metadata for the `/users/:user/projects/:project/pages` response to avoid always having to make two requests on the map view all the time... but that seems way weirder to me.

**Comment by thisandagain** [comment]
Yeah... it's weird to have a single project and multiple projects not share the same data model. Also weird to include a parent object's metadata in the child. Do we need the project object to render the map view? I didn't see a need for it.

**Comment by k88hudson** [comment]
Really? I think that's a pretty common.

We need it to know what the project title is, for example, as well as what project `id` to create new pages at.

**Comment by thisandagain** [comment]
Ok. Sounds good. Will do. :+1:

**Comment by thisandagain** [comment]
Ok. Will do.

**Comment by k88hudson** [comment]
Thanks :smile:

**Comment by gvn** [comment]
I think Pages is malformed...

![screenshot 2015-04-30 15 53 37](https://cloud.githubusercontent.com/assets/206379/7424019/35de0858-ef51-11e4-9611-b4f745284e94.png)

**Comment by gvn** [comment]
Also, although I like the Pages schema, and it seems pretty standard, it does require iteration to do a lookup by ID.

See: https://github.com/mozilla/webmaker-app/pull/1617/files#r29477481

**Comment by thisandagain** [comment]
Fixed the issue with the pages schema.

**Comment by thisandagain** [comment]
Hmm... that's interesting. So I suppose the alternate you are suggestion would be to structure it as:
```js
{
    "guid": {
        // page
    },
    "guid": {
        // page
    }
}
```

That seems pretty odd as you'll still need to do an object iteration (slower) in any instance you don't already have the IDs ala:
```js
for (var property in object) {
    if (object.hasOwnProperty(property)) {
        // do stuff
    }
}
```

I suppose at the end of the day that would mean an object iteration vs. an array iteration and creating a map at runtime. I'm trying to think of examples right now for reference. Do you agree with that assessment?

**Comment by gvn** [comment]
Yeah, honestly the more I think about it...let's just do it the way you have it. I'm prematurely optimizing for one use case...

![retreat](https://cloud.githubusercontent.com/assets/206379/7424302/653320b8-ef54-11e4-8e18-5719b46aec31.gif)

**Comment by thisandagain** [comment]
LOL. This has created all sorts of good discussion... thanks!

**Comment by k88hudson** [comment]
Also that is the best gif

**Comment by thisandagain** [comment]
Tracking remaining API responses within `mock.json` files for each view. Closing.
