### ISSUE TITLE
Build Fluid Map Zoom

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-app#1624]
Here is the initial pass on the Fluid Zoom UX:

**Version 1** - All the buttons.
https://dl.dropboxusercontent.com/u/109902/tiles/zoom-ux.pdf

**Version 2** - Simplified + Just one Button
https://dl.dropboxusercontent.com/u/109902/tiles/zoom-ux-2.pdf

Ping @k88hudson @thisandagain @xmatthewx

**Comment by thisandagain** [comment]
Great. Couple questions we might want to clarify in the diagram:
- Where does the page background color button sit in the flow?
- Where does the page delete button sit in the flow?

**Comment by flukeout** [comment]
@thisandagain In Version 2, both of those would live in the Page Editor view, I'll update the diagram to reflect that.

**Comment by xmatthewx** [comment]
v2 looks right. Nice and clean.  

The transition from Map to Page will require a little magic. Should Page view fade in over Map view? Or use the Android parent-child transition to pop it open?

**Comment by flukeout** [comment]
[Parent to child transition](http://www.google.com/design/spec/patterns/navigational-transitions.html#navigational-transitions-parent-to-child) for reference.

@xmatthewx Not sure why we need a specific transition instead of just zooming and centering the tile when entering Page Editor. Can you elaborate on the magic you think is needed? I think having a different transition will make subsequent 'swipe' navigation feel less expected.

**Comment by xmatthewx** [comment]
If Map view uses thumbnails and Page view uses elements, there's going to be a moment when we have to destroy the map view and show the page view. I just wonder if there will be any hiccups. If we don't magic, fantastic.

**Comment by flukeout** [comment]
Okay right, that kind of magic. We'll have to make this a two phone app then. The second phone will be like "HEY LOOK OVER HERE FOR A SEC" to distract the user while we do our thing. When they look back, presto.

**Comment by thisandagain** [comment]
Yeah... I'm a little worried about that transition too. Once we nail this UX, let's just transform this into an implementation ticket. It would be nice to get a jump start on the activity transitions early next week as it'll likely require a lot of tweaking.

On the UX front, I think the only thing I'm stuck on is the decision density that we've built up in the page view. The prior implementation was more balanced and I feel like we may be overloading a single view by removing the selected state in the map view.

**Comment by flukeout** [comment]
**Version 3**
This addresses the 'density' problem by moving "page delete" and "page background" color actions to the map view.

* [Version 3](https://dl.dropboxusercontent.com/u/109902/tiles/zoom-ux-3.pdf)

**Comment by thisandagain** [comment]
Cool. This feels pretty good. What was the thinking behind swapping the order of delete and edit between the project and page views?

**Comment by flukeout** [comment]
@thisandagain Forgot to even consider that order, will update the diagram.

**Comment by xmatthewx** [comment]
Looks good. Resolves lots of details. A few things:
 - Tap pencil - open page nearest center? Not selected?
 - Can I deselect page by taping on map background? 
  - If so, does anything break?
  - If not, by default do we select the most recently added or edited page?
 - Note: Add new page --> selected
 - Note: Tap and hold --> selected
 - "Or Tap Any Tile" - selected tile only? Single tap? This might invite accidental opens. Let's stick with just the pencil for Alpha. We can consider tap or double tap to open a page later. 

Page Editor:
 - Add Element - can this deselect everything even if dismissed? Would be helpful for complex collages. 
 - Note: Tap selected - move to top

:dragon: :pencil2:   :scissors:   :dragon_face: :fork_and_knife:

**Comment by flukeout** [comment]
**Map**
* Tap Pencil edits the selected tile for consistency with other UI (trash & color(
* No deselecting pages
* If selected page is deleted, we auto-select closest
* Auto select last-edited and newly created pages
* Removed "tap any tile" as it was there in error

**Page Editor**
* Agree on both points.

**Comment by xmatthewx** [comment]
If we add these last bits to the diagram, I think we can review it in the morning meeting and run with it.

**Comment by thisandagain** [comment]
:+1:

**Comment by flukeout** [comment]
Updated [the diagram](https://dl.dropboxusercontent.com/u/109902/tiles/zoom-ux-3.pdf) to include the delete tile and add new tile interactions.

**Comment by xmatthewx** [comment]
@k88hudson - let's review this with @flukeout

**Comment by vazquez** [comment]
#### Updating UI
Updating UI as per Luke's Version 3 Diagram. Posting key screens here, and updating all screens in InVision.

##### Map View Element Selected
![tile map view tile selected](https://cloud.githubusercontent.com/assets/1119821/7501331/0e910868-f3e8-11e4-9dae-0e76f6dfcb4c.png)  

#### Page View Element Not Selected
![tile view](https://cloud.githubusercontent.com/assets/1119821/7501230/711f32b2-f3e7-11e4-909d-ec6ba1426d7a.png)  

##### Page View Element Selected
![select text](https://cloud.githubusercontent.com/assets/1119821/7501299/df519586-f3e7-11e4-820e-0102eac2ad57.png)

**Comment by xmatthewx** [comment]
:+1: ...not my favorite paint bucket, but better than the brush.

**Comment by Pomax** [comment]
would the paint bucket recolor the page?

**Comment by flukeout** [comment]
@Pomax correct!

**Comment by k88hudson** [comment]
Initial alpha build is done. Major issues remaining includes https://github.com/mozilla/webmaker-app/issues/1697 , which deals with the origin of the zoom, and https://github.com/mozilla/webmaker-app/issues/1698, which deals with the buttons. Please file additional fixes as new tickets.
