### ISSUE TITLE
Page - Always add elements to center of page at top z-index

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1631]
When adding an element to a page, the elements slowly move down the y-axis over time eventually going off the edge of the page. At this point the user effectively can no-longer add elements.

/cc @flukeout @Pomax

**Comment by flukeout** [comment]
Seconded, I also referenced this in the big list on #1515, where I've checked it off there so it can live here.

I recommend just placing things smack dab in the middle every time.

**Comment by Pomax** [comment]
center of centers? Let me add that in.

**Comment by flukeout** [comment]
The centerest.
