### ISSUE TITLE
Element scales & rotates unexpectedly

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-app#1635]
Steps to reproduce:
* Add text element to a page
* Move element to another spot on the page
* Without releasing the finger you used to move, place second finger anywhere on the screen
* Element scales & rotates unexpectedly

Hypothesis
* When second finger touches, it's using the original starting point of the element as it's reference point for the second touch, not the current location of the element

**Comment by thisandagain** [comment]
@flukeout Did you see this on the latest version off of `v1`? @Pomax made a bunch of improvements late last week that improved this.

**Comment by flukeout** [comment]
@thisandagain Yeah - pulled v1 this morning and found this. Are you not able to reproduce on device?

**Comment by thisandagain** [comment]
@flukeout I'm not and your description exactly matches what I experienced before we landed @Pomax 's patch from https://github.com/mozilla/webmaker-app/pull/1611

**Comment by flukeout** [comment]
@thisandagain, @Pomax and I are both able to reproduce this. I can walk you through the steps on Vidyo if you want

**Comment by Pomax** [comment]
Confirmed, running into this, will examine.

**Comment by thisandagain** [comment]
Great. Thanks folks.
