### ISSUE TITLE
Experiment with swipe gesture in Page Editor view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-app#1643]
@Pomax - our current UX assumption, is that you can swipe between adjacent pages in the Edit Page view. Have you experimented with making this possible? I'm concerned with swipes conflicting with Element manipulations, so I'd like us to tackle this and experiment. Let me know if you have questions.

**Comment by xmatthewx** [comment]
+1 - relates to #1515

**Comment by xmatthewx** [comment]
duplicates #1648
