### ISSUE TITLE
Add alert on "Change Image" button for Alpha

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1647]
We don't have a way to change the image content in the image editor. Should we skip this altogether for alpha? Should we remove the button?

**Comment by thisandagain** [comment]
The desired scope for alpha was having a friendly default or defaults (different random image each time). I think it's good to show the button but perhaps display an alert?

**Comment by thisandagain** [comment]
Let's add an alert along the lines of "Not implemented (yet)" for alpha.

**Comment by gvn** [comment]
Is there an alert design? (cc @vazquez) 

I just whipped this up for the moment...

![image](https://cloud.githubusercontent.com/assets/206379/7479402/46c0fa0e-f316-11e4-8fe2-e6ca14a5eef3.png)

**Comment by vazquez** [comment]
@gvn What about this? The triangle on top of the box is a nice to have.

![choose image not implemented](https://cloud.githubusercontent.com/assets/1119821/7480141/56ca23f8-f31b-11e4-9b62-146d0a1abc81.png)

**Comment by gvn** [comment]
Looks cool...can you link me to the Sketch file?

**Comment by vazquez** [comment]
Yes, one sec.

Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by vazquez** [comment]
@gvn - https://www.dropbox.com/s/o3c5bn5dmnq8f7a/Alert%20Choose%20Image.sketch?dl=0

**Comment by thisandagain** [comment]
Resolved in #1664

**Comment by xmatthewx** [comment]
I think we've got to change the text on that alert. Too much tech speak. How about: Feature coming soon, or just "Coming soon!"

**Comment by thisandagain** [comment]
Changed to "Coming Soon!"
