### ISSUE TITLE
Interim text editor

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1654]
We need something to edit the text content in the editor view.

Let's use an edit dialog for now.

**Comment by Pomax** [comment]
is there any design for this in terms of where that dialog should be, or are we just winging it using something like "double tap on the text -> now you can edit it, tap outside to commit"?

**Comment by xmatthewx** [comment]
This is a reasonable interim solution. This dialog might be useful for other settings in the future. @vazquez plz comment if I did anything screwy. 

![text options edit text temp](https://cloud.githubusercontent.com/assets/53411/7484272/91593e62-f354-11e4-9ae6-55ec0f255e86.png)

**Comment by vazquez** [comment]
Looks good :+1:

**Comment by k88hudson** [comment]
I would recommend `Window.prompt` since this is not a huge priority.. would that be crazy?

We could always implement the design at a later time if it is needed

**Comment by xmatthewx** [comment]
Easy = not crazy

**Comment by Pomax** [comment]
if Android gracefully does window.prompt: :+1:

**Comment by k88hudson** [comment]
done
