### ISSUE TITLE
Page - Fails to load after adding an element

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1661]
STR:
- Navigate to the page view
- Add any element
- Go back to the prior (project) view
- Return to the page view

Expected:
- Page view loads with element that was added and persisted to disk by the binding mixin

Action:
- Page view fails to load

**Comment by Pomax** [comment]
reproduced. This seems to be caused by a missing binding for `this.dims` in the project view before we hit the render function. Fixing.

**Comment by thisandagain** [comment]
Resolved in #1662
