### ISSUE TITLE
UI - Segmented Control

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#168]
Create segmented control component as per spec: https://redpen.io/yq6334167211aa1739
Example use case: https://redpen.io/cxe597d91e2604ff14

![buttons](https://cloud.githubusercontent.com/assets/747641/4242503/52bc3782-39fe-11e4-91ce-0c994c256b5c.png)

**Comment by k88hudson** [comment]
Thanks for your work on this everyone. This issue is now resolved :)
