### ISSUE TITLE
Edit element leads to Link editor for all types

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#1688]
A couple bugs around editing an element
 - editing Image & Text leads to Link editor
 - back button removes content from Page

Steps to reproduce:
 - Select Image or Text element in page view
 - Tap paintbrush
 - Link editor opens
 - Tap back button in header

Fixes:
 - [ ] change paintbrush icon to pencil
 - [ ] auto select element after add new
 - [ ] open element editor based on type
 - [ ] fix back button in header

**Comment by k88hudson** [comment]
This is known and will be resolved with https://github.com/mozilla/webmaker-app/issues/1655.
