### ISSUE TITLE
On back, route params are empty

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#1689]
After pressing the back button I don't seem to be actually getting any route params being returned, just an empty object

**Comment by k88hudson** [comment]
Hm, actually i think i know why...

**Comment by k88hudson** [comment]
Ok, this seems to only be an issue when you press the back button.

**Comment by k88hudson** [comment]
@thisandagain any idea why this might be the case?

**Comment by k88hudson** [comment]
Definitely related to this line being `null`
https://github.com/mozilla/webmaker-app/blob/v1/app/src/main/java/mozilla/org/webmaker/WebmakerActivity.java#L36

**Comment by thisandagain** [comment]
The issue here is that the back button doesn't trigger the router and thus the route params are never attached to the intent extras (thus `intentExtras` = `null`).

**Comment by thisandagain** [comment]
As per Vidyo call: will resolve by persisting / restoring route params to `SharedPreferences` via react mixin.

**Comment by k88hudson** [comment]
Hurray! fixed!
