### ISSUE TITLE
inconsistent casing between filenames and requires()

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-app#1692]
e.g.in www_src/pages/page/page.jsx we have var Positionable = require('./positionable.jsx');
but the actual name of the file is Positionable.jsx.
This is the problem for those of us who use case-sensitive OS's like Linux!
Loading the app throws errors about 'positionable.jsx not found' because of it.

**Comment by thisandagain** [comment]
Great catch @errietta ! :smile: :+1:

**Comment by errietta** [comment]
R? @thisandagain
