### ISSUE TITLE
Positionable - Cannot restore state

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#1696]
First noticed in #1690 

:beetle: One bug that I'm noticing is that after adding elements to a page, if you exit, go to another page, and then return those elements are rendered at a different origin / position.

STR:
- Enter project view
- Open page at 0,0
- Add three elements (rotate and scale them)
- Exit page and open page at 0,1
- Add one element (don't rotate and scale)
- Exit and then return to both pages

Expected:
- Elements are in the position you left them in

Actual
- Elements seem to be shifted into the top left corner

**Comment by k88hudson** [comment]
Ok, looks like the reason is that the Positionable component has some state that doesn't get persisted to the actual element (xoffset and yoffset) so that will need some refactoring

**Comment by k88hudson** [comment]
@Pomax can you take a look at this today?

**Comment by Pomax** [comment]
yup

**Comment by xmatthewx** [comment]
Seems to only happen the first time you exit after a new element is added. Exit and return again, the element retains it's position, regardless of whether it's been moved or not. Seems to be offset -50% of the pages height and width.

**Comment by Pomax** [comment]
I suspect it's the page.jsx component not caching its own dimensions correctly. It's using `this.dims` at the moment instead of state, so I'm moving that into state and we'll see if that helps.
