### ISSUE TITLE
Phone Block Non-Functional

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#369]
When you insert "place a call" brick in your template, and then if you click on it, you end up lost in the contact folder, and cannot go back to the app. You must close the page and open the app again.

**Comment by thisandagain** [comment]
Phone block is currently non-functional is Firefox OS 2.0

**Comment by Pomax** [comment]
the normative behaviour in FFOS for this is to "slide back" to the application, so if you swipe from the left into the screen, you can get back to the webmaker app from the phone app.
