### ISSUE TITLE
Make template icons transparent (Blocked)

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-app#400]
Currently the color and circle is baked into the template icons - let's change it so they're white icons on a transparent background and we can set the shape and color of the circle via css.

![image](https://cloud.githubusercontent.com/assets/25212/4741487/c69928b2-5a16-11e4-8277-3332019e0af3.png)

**Comment by gesa** [comment]
I believe we can close this, all the templates are using white icons with transparent backgrounds now. (sorry I can't find the commit—maybe b70617ccbbd8be978937a99057d3a71f09b58101 ?)
