### ISSUE TITLE
Develop strategy and UX for fatal Model and fs errors beyond console.log()

### ISSUE THREAD

**Issue by humphd** [mozilla/webmaker-app#440]
The `Model` exposes a number of methods that can all fail in ways that can't be ignored, for example

* `Model.restore(callback)` - https://github.com/mozillafordevelopment/webmaker-app/blob/82bc01d7e52d150e8b2d4394b5bda9312b4e5826/lib/index.js#L50-L51

There are also other places where the Model's raw `fs` is is used, for example:

https://github.com/mozillafordevelopment/webmaker-app/blob/77597541cb048472c43ec97c046318b73dd57844/views/profile/index.js#L31-L51

Whenever the `fs` methods are called, the possibility of there being a fatal error is always present.  Any number of things can go wrong (no more disk space, OOM, permission issues all of a sudden, corruption of data, ...).  The point is, it's dangerous to ignore these errors, which seems to be happening in the code (doing `console.log(err)` and continuing on isn't enough).

I started to add proper error handling, but the real issue is what you do with such errors at the top level, and before the user encounters an app that doesn't seem to work.  Sometimes you can ignore an error (e.g., `ENOENT` when a file doesn't exist and you simply create the file).  But, if the error was something else, the recover code to create that file might also fail, and for the same reason.

I'd like to suggest a couple of things:
* Add proper `if(err){...}` code paths for all callbacks from `fs` methods
* Log errors so you can see what's happening deep in your stacks, but then bubble that error on the callback chain.
* Deal with (i.e., swallow) all `fs` errors in callbacks that are non-fatal (e.g., `ENOENT` type issues)
* Figure out what the top-level actions are.  In some cases, you could auto-recover (e.g., format the filesystem and sync).  In other cases, I suspect there is user intervention required, or at least some kind of UI messaging to let him/her know that things aren't OK, data can't be saved, data was lost, etc.

Every error returned by an `fs` method means something, and shouldn't be ignored.

**Comment by thisandagain** [comment]
Covered in new API approach and lib from #1509
