### ISSUE TITLE
Migrate to github.com/mozilla & update documentation

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#450]
- [x] Move repos
    - webmaker-app
    - webmaker-app-publisher
    - beaker
- [x] Update docs (@k88hudson)
- [x] Update Travis-CI keys

**Comment by thisandagain** [comment]
The main repo (this one) has been moved to the mozilla org. Still need to test / fix Travis-CI.

**Comment by thisandagain** [comment]
New repo locations:
https://github.com/mozilla/webmaker-app (app)
https://github.com/mozilla/webmaker-app-cordova (beaker)
https://github.com/mozilla/webmaker-app-publisher (publisher)

**Comment by k88hudson** [comment]
:dancer:

**Comment by k88hudson** [comment]
Docs are updated.

We still need to change the name on Transifex and the s3 task.

@jp can you help with this (the resource is currently named `mobile-appmaker` and needs to be renamed to `webmaker-app`)

**Comment by k88hudson** [comment]
Done!

**Comment by k88hudson** [comment]
Actually i lied. ping @jdotpz re: Transifex?
