### ISSUE TITLE
Improving Tea-Shop template for Kenya

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#458]
Ideas for working on the tea-shop template: 

- Possibility to add a company logo for the title of your shop 
- Possibility to have a background color 
- Possibility to move blocks around 
- Possibility to take photos from your phone gallery
- Possilbility to have a map to show the location of the shop 
- Possiblity to have links to websites or social media presence 
=> "Insert link" brick ?
- possiblity to have a menu with categories of products ? 
     Example:  Tea leaves, cakes...

Any other ideas ?
The general feeling is: more customization. Vendors want to differenciate their shops from others as much as possible.
Let me know what is possible, and im happy to jump on a quick call to brainstorm like we did with @xmatthewx last time. 

Thanks 
@thisandagain @flukeout @k88hudson

**Comment by LauraReynal** [comment]
Reopen because some bugs on this templates for Android : 
- the counter buttons are not aligned, the + sign is a lign under 
- The "place an order button" does not show any text, simply a blue box
==> people dont get it by themselves I dont explain so lets try to improve this and see if it works better. They just dont see the link between counter and submit button

**Comment by thisandagain** [comment]
Fixed!
