### ISSUE TITLE
Set a string freeze date

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#508]
This is to ensure we have sufficient time to do localization

**Comment by alicoding** [comment]
When is the date we are showing/doing at the MWC? I think we need at least 1 week minimum for translators in order to do the translation, review and QA.

**Comment by thisandagain** [comment]
March 2nd. I added https://github.com/mozilla/webmaker-app/issues/987 for Friday which gives us 2 weeks for translators. Work for you @alicoding ?

**Comment by alicoding** [comment]
That's perfect!
