### ISSUE TITLE
Refine the way we pick a color 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#522]
When the user click on the brick edit page to change the text: 
* He changes the text, and then clicks on color
* He changes to blue, and then is lost " Its broken, I cannot save" 
* He cliks on the < to go the previous brick edit page, and says "Here, you see it does not work, the text is still black"

=> Show the change of color on the brick edit page to allow the user to preview his edit before going back to the general page. 
=> add a "save" button on the Pick a color page 

@flukeout

**Comment by thisandagain** [comment]
Addressed in #669
