### ISSUE TITLE
Make "preview/edit/data" bar swipe-able

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#537]
People wanted to swipe the preview / play toggle

![image](https://cloud.githubusercontent.com/assets/1455535/5219479/8acf38c2-7626-11e4-9092-a9949a0c2f5b.png)

PR in progress: https://github.com/mozillafordevelopment/webmaker-app/pull/492

**Comment by thisandagain** [comment]
Removing bar in #869
