### ISSUE TITLE
Keyboard issues on FFOS

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#543]
> * Keyboard stuck around sometimes after changing font-size and was visible on the edit / preview page.
  * Can we force clear it when changing from brick details to edit view?
  * Also trying to clear out the keyboard sometimes led to unexpected interactions - try to reduce keyboard based interactions? We can def use a different UI for font size at least.

**Comment by Pomax** [comment]
@k88hudson are there any STR at all that I can use to even get in this state? (I've not seen this happen yet)

**Comment by thisandagain** [comment]
This is a pretty old issue. Feel free to close if you can't replicate.

**Comment by Pomax** [comment]
thus closed.
