### ISSUE TITLE
Scrolling through templates list doesn't work on ffOS

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-app#564]
in firefox OS, I can't scroll through the templates list leaving me stuck with the first few options
![2014-11-28-21-38-20](https://cloud.githubusercontent.com/assets/134585/5232417/340fa8c4-7747-11e4-92af-90716a1a2165.png)

**Comment by k88hudson** [comment]
I don't think this is an issue anymore, seems to be resolved
