### ISSUE TITLE
Sign In - UI adjustments to "Check your email" screen

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#569]
Platform: Android 4.4
Release: http://webmaker-app.mofodev.net via Beaker

UI nitpicks:
- [ ] Use title case for "Check your email"
- [ ] Fix inconsistent right margin on "Next" button
- [ ] Checkbox for "Remember me" should not have a line break afterwards
- [ ] Change "Remember me for one year" to "Remember me"

![screenshot_2014-12-01-10-41-28](https://cloud.githubusercontent.com/assets/747641/5253868/44754546-7960-11e4-93ca-cc221cff04b4.png)

**Comment by k88hudson** [comment]
This was resolved

**Comment by k88hudson** [comment]
Oops I lied! PR is here https://github.com/mozilla/webmaker-login-ux/pull/87

**Comment by k88hudson** [comment]
Merged in webmaker-login-ux.  :dancer:
