### ISSUE TITLE
Publish - Published app does not render on Chrome

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#574]
Platform: Android 4.4
Release: http://webmaker-app.mofodev.net via Beaker
Example: http://apps.mofodev.net/p/testm01/-Jc689lHjeA_tAoGVUUB/

![screenshot_2014-12-01-10-44-59](https://cloud.githubusercontent.com/assets/747641/5254094/6c395502-7962-11e4-812a-e9255b8f0bd8.png)

**Comment by k88hudson** [comment]
Closing in favour of filing specific publishing improvement tickets, since this particular issue was resolved.
