### ISSUE TITLE
Unable to find my current work 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#584]
Today, not a single person is able to find the app he was working on, if the page closed by mistake.

I click on template > I edit > I make a false move and the edit page closes > Im back on Make > I start again fresh and loose all my previous work. 

In the meantime, my profile is filling with drafts that I will never use and which are confusing :)

**Comment by thisandagain** [comment]
I *believe* we have this fixed from the Firebase transition, but feel free to re-open if you still see this issue.
