### ISSUE TITLE
Replace "block editor" with a transition state

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#591]
A lot of people find it difficult to understand the editing paradigm and visualize changes they were making whilst editing blocks.

We want to try transitioning the block to the top, fading out the rest of the app and adding editing UI on the same page.

Some things to consider:
* how does this work for large blocks? e.g. image
* how do we exit that state/initiate a "save"?

**Comment by thisandagain** [comment]
Addressed in new editor design.
