### ISSUE TITLE
Redesign blog template

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#596]
We'd like to try a first-run experience that involves pre-populating the main screen with some "ready-made" apps. The first three we were thinking of trying are:

* store (vendor)
* blog
* survey

**Comment by vazquez** [comment]
#### Blog Template

![profile 3 1x](https://cloud.githubusercontent.com/assets/1119821/5727605/5cbca7a4-9b32-11e4-87f3-65018dc3d4fd.png)

I designed the template with photos, but I can replace with illustrations in the future as per @thisandagain's feedback.

cc: @cassiemc @k88hudson

**Comment by cassiemc** [comment]
Could you throw it in redpen please?

**Comment by flukeout** [comment]
I like that the blog template gives information and tips on writing a successful blog, that's cool. I think we'll need a better way to delete content from the app though - because cleaning this out once you've read it will be a PITA.

**Comment by vazquez** [comment]
Redpen link @cassiemc https://redpen.io/sk40fcc4b898b13bfe

**Comment by vazquez** [comment]
Updated design:

![profile 5 1x](https://cloud.githubusercontent.com/assets/1119821/5741768/4c8817a2-9bdb-11e4-810a-4bc4b75844c8.png)

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/sk40fcc4b898b13bfe

**Comment by cassiemc** [comment]
R- Replied with some comments on Redpen. There is still some thinking to do here, most notably to dramatically shorten the content.

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/sk40fcc4b898b13bfe

- The "Add" button feedback will be addressed in a separate ticket #516 
- The "Delete App" button feedback has already been addressed in a separate ticket #670

**Comment by cassiemc** [comment]
almost there! a bit more shortening if possible.

**Comment by vazquez** [comment]
Right back at you :) What about this? https://redpen.io/sk40fcc4b898b13bfe

**Comment by cassiemc** [comment]
R+! So much more digestible, nice work.

**Comment by vazquez** [comment]
I agree :)

**Comment by k88hudson** [comment]
I filed an implementation ticket for blog here (since I'm not sure we'll be able to fit in the implementation this week) #730
