### ISSUE TITLE
Improve language on existing "Make" (Templates) page

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#597]
We need something like "Create an App", so that users know what the expected action is when they choose an app template

**Comment by vazquez** [comment]
Design review please @cassiemc!

A: https://redpen.io/cn517f4568ebc19aa1
B: https://redpen.io/sqa97836578d8b6e28

**Comment by cassiemc** [comment]
R+ on option B. 

As mentioned in redpen I did like the previous icons that were white outlines vs. the white filled circle backgrounds, but not a breaker by any means.

**Comment by vazquez** [comment]
![make 7 1x](https://cloud.githubusercontent.com/assets/1119821/5667518/8bd25494-9736-11e4-8fd3-96258611f8d0.png)

**Comment by cassiemc** [comment]
I dig it!

**Comment by vazquez** [comment]
@k88hudson @thisandagain @LauraReynal 

Are we keeping the same templates for India field research? We currently have the following:
- From Scratch (addressed)
- Journalist
- Vendor (addressed)
- Medic
- Teacher (addressed)
- How To
- Scientist
- Family
- Blogger (addressed)
- Club
- Safety
- Activist

Which other ones should I focus on for icons and copy?

**Comment by vazquez** [comment]
Club:

![start from scratch choosing this option 3 oval 19 2](https://cloud.githubusercontent.com/assets/1119821/5668593/c63aa246-973e-11e4-8d2d-f770058dba89.png)

**Comment by vazquez** [comment]
Icons can be found here @k88hudson: https://www.dropbox.com/s/1ef01g9tto8gkv3/Template%20Icons.zip?dl=0

**Comment by k88hudson** [comment]
Thanks!

**Comment by LauraReynal** [comment]
Re opening this issue, after 4 testing sessions there are 2 important feedbacks:
- Too much text for each block: Could we try with just "Create a blog" ie just the title to see if better?
People dont read the sub text
- Never use the black color: It's too negative, sad, and inapropriate in certain cultures ( in this case India)
=> use something more colorful for Start from scratch

@k88hudson @vazquez

**Comment by vazquez** [comment]
As per Laura's comments, making changes to the Templates page.

![make 11 1x](https://cloud.githubusercontent.com/assets/1119821/5740309/30c9e5aa-9bd0-11e4-9f32-411a3ab88353.png)

Colours:

- #FF5C5A
- #97CC3B
- #F79131
- #F2C233
- #DC8AEB
- #8C8AEB
- #27AAE1

**Comment by LauraReynal** [comment]
Thanks @vazquez we will test this starting tomorrow :) !

Laura de Reynal
Webmaker

**Comment by k88hudson** [comment]
@LauraReynal still needs to be implemented but should be no problem by tmr

**Comment by xmatthewx** [comment]
Nice colours and execution @vazquez! 

In an earlier design, we want from a page similar to the one you've designed to a landing page for each template. This landing page explained things in a sentence or two, listed a few apps made from the template to try, and then had a CTA button. Might be worth testing.

**Comment by k88hudson** [comment]
@xmatthewx we actually implemented https://cloud.githubusercontent.com/assets/1119821/5667518/8bd25494-9736-11e4-8fd3-96258611f8d0.png currently, and laura found that the descriptions were overwhelming/not needed

**Comment by k88hudson** [comment]
@vazquez can you take a quick look at http://wm.ngrok.com/templates (temp link)?

**Comment by vazquez** [comment]
@k88hudson Looking great :)

**Comment by k88hudson** [comment]
Done!

**Comment by LauraReynal** [comment]
Hey @vazquez @thisandagain @k88hudson @flukeout Just a quick note to say the new Make page is LOVED by everyone "beautfiul" "self explanatory" "Very nice design" "intuitive" "this page speaks for itself" are things I hear all the time now :smile: :clap: :clap: Thank you for this great work !

**Comment by k88hudson** [comment]
woooot!!! great job everyone :smile:  just a heads up @LauraReynal the next thing we will be updating is the preview screen when you choose a template (https://redpen.io/ep9847126f99a1bcf9)

**Comment by LauraReynal** [comment]
OH.YEAH. This will be AWESOME ! 
:rock: :sparkles: :fire: this page was confusing people

**Comment by vazquez** [comment]
That is great to hear! It made my day :)
