### ISSUE TITLE
Replace all pngs with svg illustrations in starter apps/templates

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#599]
because data be costly :dancer:

**Comment by gesa** [comment]
#833 closes #599

**Comment by gesa** [comment]
The tricky part: the icon chooser doesn't just use the icon name, it uses the full icon path and extension. So all legacy apps could be impacted by changing the default icon paths.

**Comment by thisandagain** [comment]
**Now** would be the time to break that! :wink:

**Comment by thisandagain** [comment]
To be specific, the time to break that is prior to this landing: https://github.com/mozilla/webmaker-app/pull/1184

**Comment by gesa** [comment]
:+1:

@thisandagain: I wonder if I should expand the scope of my PR to change the icons in all the templates as well?

**Comment by thisandagain** [comment]
Yes please!

**Comment by gesa** [comment]
I think this actually *was* closed by #1193
