### ISSUE TITLE
UX prototypes for editor

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-app#607]
**Prototype 1 -  http://flukeout.com/examples/mobileui/**
Exposes UI to sort, delete and duplicate when you tap the arrows on the right side of a brick.
(Sorting doesn't work)

Feedback
* is there an undo? i always want undo on my phone!
* confirm button for delete? slows things down too much?
* more fidelity around revealing the options, so you're not just squinting for the < button?

**Prototype 2 - http://flukeout.com/examples/mobile2/**
Swipe left to reveal reveal the delete, duplicate & sort UI.
**Note** - none of the interactions work. Just demo to show revealing / hiding the UI.

**Prototype 3 - http://flukeout.com/examples/mobile3/**
Please use **Chrome**, the animations are nicer. This one show off the "tap to sort" UI concept. 

**Prototype 5** - http://flukeout.com/examples/mobile5/
One more kick at the can here, use Chrome for best effect.

**Comment by k88hudson** [comment]
@cassiemc if you could take a look at http://flukeout.com/examples/mobileui/ (and others), that would be super awesome

**Comment by thisandagain** [comment]
Let's work with @cassiemc and @flukeout to pick a direction here and then schedule a sprint for executing it.

**Comment by flukeout** [comment]
http://flukeout.com/examples/mobile5/ is the latest / greatest and the one I wanted to test. It's almost there - I just need some way to simulate / mock editing each brick.

**Comment by k88hudson** [comment]
@flukeout @thisandagain I did a UI pass on your latest demo, R? https://redpen.io/p/ec6e7f6957e1246560

I'd love to be able to give this to a dev to implement next sprint

**Comment by thisandagain** [comment]
:smile:

**Comment by thisandagain** [comment]
UX complete. Tracking UI in #754
