### ISSUE TITLE
Tab bar images are low resolution

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#614]
This only appears in the actual .apk app for me

**Comment by k88hudson** [comment]
These:
![image](https://cloud.githubusercontent.com/assets/1455535/5652571/d37e10b0-967f-11e4-8cf5-1c0f8953582d.png)

**Comment by gvn** [comment]
Hmm. These are SVG, so is this a bug/feature in Android? @k88hudson

**Comment by k88hudson** [comment]
ah! good catch. could be svg resizing issues, i've seen that cause resolution issues before

**Comment by k88hudson** [comment]
@gvn do you want to try resizing the images and replacing them?

**Comment by gvn** [comment]
Do you mean change the dimensions via CSS since they're SVG or something else?

**Comment by k88hudson** [comment]
No, i've seen issues where like if the svg has a size setting (in the code/svg) that is too small it won't scale up properly

**Comment by gvn** [comment]
Are all 3 images aliased? I see the left and right ones have width & height set in the SVG while the middle one is scaled via CSS.

**Comment by thisandagain** [comment]
Fixed in latest build

**Comment by gvn** [comment]
![done done](https://cloud.githubusercontent.com/assets/206379/6140955/8a027022-b153-11e4-9a1b-c4c2a3219a74.gif)
