### ISSUE TITLE
Quality review

### ISSUE THREAD

**Issue by cassiemc** [mozilla/webmaker-app#622]
I'm on the hook for quality on these issues. We will do ad hoc reviews, but wanted to file this meta ticket so it doesn't get lost.

For this heartbeat, we've defined quality specifically as:
- is login experience optimal?
- are problems resolved to meet original user issues from Kenya?

**Comment by k88hudson** [comment]
We dropped the ball on getting a proper process ready for this – sorry @cassiemc. We will improve on this next milestone

**Comment by cassiemc** [comment]
No problemo @k88hudson just let me know where/how to see it. It probably didn't help that I found it challenging to attend all the standups. Let's keep thinking about specific ways to address this. We have issues 154, 134 and 135 filed already, so there is a lot to look at here.

**Comment by k88hudson** [comment]
So, we kind of did this informally throughout the week/during check-in.

Is there anything else you'd like to add @thisandagain before we close?

**Comment by thisandagain** [comment]
Nope. All set. Will address further issues in planning ticket for editor UX and UI continuity.
