### ISSUE TITLE
Installation Service

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#633]
For distribution we need something better than providing one-off links for each platform. Ideally, users could go to `webmaker.org/install` and be directed to download / install the Firefox OS app or the Android app while we are in development with the intent that those links would point to the Firefox Marketplace and Google Play stores at launch. Thoughts @k88hudson ?

See: https://github.com/mozillafordevelopment/webmaker-app/issues/628

**Comment by k88hudson** [comment]
@thisandagain if I update this to redirect to the android sdk (it already triggers a ffos install), do you want to get rid of the separate bitlys?

**Comment by thisandagain** [comment]
Sure! That's ideal so we can just do the UA detection in one place.

**Comment by thisandagain** [comment]
Also... *pretty* sure the Fennec team wants mzl.la/android back. :wink:

**Comment by k88hudson** [comment]
This is done. @thisandagain can you let the teams who wanted to use android/ffos bitly links know they are free to be re-used now?

**Comment by thisandagain** [comment]
Will do. Thanks @k88hudson

**Comment by thisandagain** [comment]
Can we get a prettier install service URL than: `https://webmaker-dist.s3.amazonaws.com/install.html`?

**Comment by k88hudson** [comment]
haha, yes :wink:

**Comment by thisandagain** [comment]
Flow diagram for Install Page & Install Service:
![install_flow](https://cloud.githubusercontent.com/assets/747641/6273088/802aa37e-b821-11e4-9509-dd16c6acfeb0.png)

/cc @k88hudson @cadecairos @jbuck @secretrobotron

**Comment by simonwex** [comment]
^ nice, @thisandagain I think I see orion's belt!

**Comment by k88hudson** [comment]
@thisandagain I updated https://github.com/mozilla/webmaker-app-cordova/pull/32/files to reflect all of this except the redirect, which will have to be implemented after the install page actually exists.

**Comment by thisandagain** [comment]
:+1:

**Comment by k88hudson** [comment]
Filed https://github.com/mozilla/webmaker-app/issues/1246

**Comment by k88hudson** [comment]
Now that this has landed I'm going to close, follow-up changes will be addressed in #1246
