### ISSUE TITLE
Add Livereload to gulp dev

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-app#652]
It'd be really nice to have livereload. :v:

**Comment by k88hudson** [comment]
We had this initially, but personally I find it's slightly buggy – perhaps we could add an alternate `live` task that is the same as `dev` but has live reload enabled

**Comment by gvn** [comment]
What sorts of bugs were you running into?

**Comment by k88hudson** [comment]
Because css compiles at a different speed than js and a lot of copying of static files happen, it would reload several times and/or before it's ready

**Comment by k88hudson** [comment]
since switching to browserify via gulp-run compilation is a LOT faster though, so might be ok. if you want to try it again go for it
