### ISSUE TITLE
Documentation for running webmaker-app in Heroku

### ISSUE THREAD

**Issue by tanay1337** [mozilla/webmaker-app#653]
It would be great if we could have documentation for instructions on how to deploy webmaker-app at Heroku. 

Reason: It would be great for students as `npm install` takes quite some data, so students could do all the downloading and repository cloning through `c9.io` for instance and from there deploy to heroku to test. This whole process takes a very little amount of bandwidth and would help many students in remote locations to contribute!

**Comment by k88hudson** [comment]
This is a great idea, we should definitely look into this

**Comment by tanay1337** [comment]
Recently discovered `koding.com` a website similar to `c9.io` which allows setting of custom ports, using which I was able to deploy many components of webmaker there (without using heroku). However, I was unable to change the port for `webmaker-app` and it could not be deployed there. Some information on this would be very helpful as well!

**Comment by thisandagain** [comment]
This is no longer needed based on updated architecture in the v1 branch. https://github.com/mozilla/webmaker-app/tree/v1
