### ISSUE TITLE
Expose contacts via cordova

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#657]
We need to expose a list of contacts from the phone (Android, FFOS, iOS)

**Comment by k88hudson** [comment]
https://github.com/apache/cordova-plugin-contacts/blob/master/doc/index.md

**Comment by gvn** [comment]
If you want to specify a schema let me know. Initial thought is something like:

```javascript
[
  {name: "Guy Dudesworthy", number: 1234567890}
]
```

**Comment by k88hudson** [comment]
Great, that looks reasonable to me

**Comment by k88hudson** [comment]
Done!
