### ISSUE TITLE
Update publishing UI to add contacts

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#658]
See: https://redpen.io/fn6bd4b0dbeaf8e985

Note that the text for "add contacts" should probably change to "edit contacts" once people are added.

Depends on #656

**Comment by k88hudson** [comment]
Note: 
* only implement share by SMS and show in discovery gallery
* show in discovery gallery should add a boolean flag

**Comment by gvn** [comment]
I'm gonna use this ticket just for the contact picker UI and do the publish privacy flag in #694 since it's another feature...
