### ISSUE TITLE
Implement discovery front end

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#663]
Designs: https://redpen.io/p/gp122b0c5b39e0a85d

* Replace near me with newest
* used "featured" flag (boolean) for firebase storage

**Comment by gvn** [comment]
@k88hudson Is there documentation for the web service?

**Comment by k88hudson** [comment]
@k88hudson it's all directly through firebase, so you should look at the app (I just added you) and check out https://www.firebase.com/docs/web/api/query/
