### ISSUE TITLE
Build an IRC bot to display all new "makes" from app

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#664]
Build an IRC bot that posts a screenshot and a link every time that a make is published via the app.

**Comment by thisandagain** [comment]
Use: for moderation of the explore gallery.

**Comment by gvn** [comment]
FYI: I'm planning to use `isFeatured` as the flag param.

Ex: https://webmaker-app-dev.firebaseio.com/staging/apps/-JfTnO1ShfJjKnrC4oZt

**Comment by thisandagain** [comment]
:+1:

**Comment by errietta** [comment]
https://github.com/errietta/webmaker-announce-bot/tree/master

**Comment by thisandagain** [comment]
\o/

**Comment by k88hudson** [comment]
Almost done. tracking here https://github.com/MozillaFoundation/mofo-devops/issues/3

**Comment by thisandagain** [comment]
@simonwex could we get your help deploying this?

**Comment by cassiemc** [comment]
:+1:
