### ISSUE TITLE
Can't seem to publish from Android app

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#666]
On Nexus 5, using app installed today found at mzl.la/android
Signed in, created a journalist app, hit publish, got:

![2015-01-06 22 52 55](https://cloud.githubusercontent.com/assets/51278/5637742/bd760448-95b3-11e4-9667-b38978eb9fef.png)

@k88hudson says it's supposed to work, so filing.

**Comment by k88hudson** [comment]
This seems to be a problem with the staging publishing server, getting 404 responses on publish

**Comment by k88hudson** [comment]
Looks like the latest tag wasn't pulled in. Trying to re-deploy now

**Comment by k88hudson** [comment]
This is resolved
