### ISSUE TITLE
Add new block doesn't work

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#668]
Regression is on master, not last tag.

STR:
1. Go to http://webmaker-app.mofodev.net/make/***/add
2. Try to add block

ACTUAL: text editor opens, no block added
EXPECTED: block added, correct editor opened

**Comment by gvn** [comment]
I'm having some trouble debugging this since I'm not super familiar with this part of the app, but I have noticed that `block-id` is coming through as `null` here:

https://github.com/mozilla/webmaker-app/blob/master/views/add/index.js#L55
