### ISSUE TITLE
Rename "input" block to "text box"

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#671]
Research suggested no one understands what "input" means here:

![image](https://cloud.githubusercontent.com/assets/1455535/5652537/819e34aa-967f-11e4-94a6-4a5b89e21f16.png)

Any suggestions @xmatthewx @cassiemc @vazquez ?

**Comment by k88hudson** [comment]
(it's an text input block)

**Comment by vazquez** [comment]
What about 'text field'?

Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by cassiemc** [comment]
Or just 'text'

**Comment by xmatthewx** [comment]
It's tricky. Input and field are both weird words. Text is the name of the block that allows someone to display text. 

Most people will use this brick to gather info or get answers to a question such as "What's your address for delivery?" In super plain language: the user adds a box for someone else to put text in it and then send it back.

Maybe it's called:
 - Info box
 - Text box
 - Question (emphasis on the label)
 - Answer
 - Q&A (translatable?)
 - Form (paper forms might be more universally familiar)

**Comment by cassiemc** [comment]
I like 'text box' or 'form'

**Comment by vazquez** [comment]
I like text box, it has a clearer visual connotation.

Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by k88hudson** [comment]
Ok, let's go with 'text box'. Thanks everyone :)
