### ISSUE TITLE
Prototype image uploading service for offline/slow network conditions

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#672]
Key objectives:
* Should minimize unnecessary data usage
* Should be tolerant to intermittent/poor network conditions

That means we should:
* compress on the client (and/or use take advantage of what the device can provide us through cordova)
* store copies of images locally until they need to be uploaded (i.e. published)
* avoid a transactional model of uploading if possible, where UI is blocked until upload is done/lost connection or refresh causes total failure of upload

**Comment by k88hudson** [comment]
Just a note: this will/should not be completed immediately. Intention is just to start researching/thinking about options.

**Comment by davidascher** [comment]
fyi: https://github.com/joelvardy/Javascript-image-upload

**Comment by k88hudson** [comment]
cc @thisandagain @jbuck if you want to add anything here
