### ISSUE TITLE
Image uploading: v1 of image uploading service

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#673]
Although this will be replaced by what we come up with #672, can we add a very simple endpoint to https://github.com/mozilla/webmaker-app-publisher that publishes images to s3 and returns a URL?

**Comment by davidascher** [comment]
FYI: https://github.com/jimmynicol/image-resizer may be useful (although I
don't think it helps with upload-on-a-dribble-bit)

**Comment by k88hudson** [comment]
Should also include docs please (in https://github.com/mozilla/webmaker-app/tree/master/_docs)
