### ISSUE TITLE
Redesign Survey Template

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#675]
Let's make a survey template that uses the new data blocks.

Design notes here: https://github.com/mozilla/webmaker-app/issues/219

This does not need to be completed by end-of-week.

**Comment by vazquez** [comment]
I'm making a survey template for teachers to get to know their students better.

![survey template](https://cloud.githubusercontent.com/assets/1119821/5706531/bf46a5fc-9a4f-11e4-9e92-b9adf9dc98e1.png)

**Comment by vazquez** [comment]
@k88hudson @thisandagain 

Looking for feedback on template. Specifically, how many fields do you think the template needs to have?

I am designing for dropdowns, although I don't see the functionality present yet when running the app.

**Comment by k88hudson** [comment]
@vazquez i think that looks like a good start!

Codebase exists, but we will need to do a UX pass on dropdowns. If we need to we can replace with inputs for now

**Comment by k88hudson** [comment]
@vazquez The image at the top seems a little bit superfluous/awkward. Perhaps we could use a more relevant/contextual illustration (maybe classroom related?)

What do you think

**Comment by vazquez** [comment]
Redpen link @cassiemc  https://redpen.io/ywb7a57b152489f041

**Comment by vazquez** [comment]
Shorter template, different graphic.

![profile 4 1x](https://cloud.githubusercontent.com/assets/1119821/5740800/e1542058-9bd4-11e4-9b7a-ad0b75350cfe.png)

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/ywb7a57b152489f041

**Comment by cassiemc** [comment]
This is great content-wise. A couple UI things to consider if you want to reply in the redpen.

**Comment by vazquez** [comment]
Stand by for another R? in a little while.

**Comment by cassiemc** [comment]
@vazquez k

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/ywb7a57b152489f041

**Comment by cassiemc** [comment]
I think that addresses a couple questions but left a few more in the redpen.

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/ywb7a57b152489f041

**Comment by vazquez** [comment]
@cassiemc has R+ this design

**Comment by thisandagain** [comment]
\o/

**Comment by vazquez** [comment]
Final Design on Redpen: https://redpen.io/ywb7a57b152489f041

![profile 4 1x](https://cloud.githubusercontent.com/assets/1119821/5783455/22022754-9d91-11e4-8e0a-409de5e51a78.png)
