### ISSUE TITLE
Do a comprehensive design review of the app so far

### ISSUE THREAD

**Issue by cassiemc** [mozilla/webmaker-app#680]
I'll look at this link and file anything I see as followup issues. http://webmaker-app.mofodev.net/

**Comment by k88hudson** [comment]
:dancer:

**Comment by cassiemc** [comment]
@k88hudson @thisandagain Is this needed/helpful for the jan30 milestone?

**Comment by thisandagain** [comment]
@cassiemc Yup... the sooner, the better.

**Comment by thisandagain** [comment]
Tracking UI concerns in milestone (to kickoff on next sprint):
https://github.com/mozilla/webmaker-app/milestones/UI%20Improvements

Please feel free to add issues!
