### ISSUE TITLE
Allow users to opt in/out of being a featured app

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-app#694]
Sounds like we need something like a checkbox during the publish step for a user to decide whether they want their app featured or not.

This will also require another param on the app objects. I'm thinking `isDiscoverable` (boolean).

**Comment by gvn** [comment]
@thisandagain I'm assuming this will need to be designed?

**Comment by k88hudson** [comment]
why do we need this separately from show in gallery?

**Comment by gvn** [comment]
Is that a thing?

**Comment by gvn** [comment]
Nevermind, found it...

![image](https://cloud.githubusercontent.com/assets/206379/5726935/36ddc98c-9b14-11e4-9e94-12cf7f0a0958.png)

**Comment by gvn** [comment]
Also, let's *not* allow guests to turn this flag on so that we can use it for the newest apps query.

**Comment by k88hudson** [comment]
:dancer:

**Comment by gvn** [comment]
:metal:
