### ISSUE TITLE
Figure out migrations

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#696]
We need to be sure that:

* old apps are properly supported (i.e. data is migrated when schemas change)
* existing apps can benefit from future bug fixes/updates
* this is testable/verifiable

**Comment by gvn** [comment]
If we are going to continue to store as JSON then using something like [JSON Schema](http://json-schema.org/) might be quite useful. I've used it to validate JSON config files in the past.

I'm pretty sure there are other JSON/POJO schema validation options as well...

**Comment by k88hudson** [comment]
Agreed!

A contributor did some awesome work writing block/template validator tests for us here https://github.com/mozilla/webmaker-app/blob/master/test/unit/templates.js#L2

and it's SUPER helpful.

**Comment by thisandagain** [comment]
Tracking in https://github.com/mozilla/api.webmaker.org/issues
