### ISSUE TITLE
Create living style guide

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-app#698]
Add a view, such as /style-guide, that shows off all the components and reusable styles.

See discussion here for more details: https://github.com/MozillaFoundation/plan/issues/165

For now, let's hold off and do this when we port to React.

**Comment by thisandagain** [comment]
/cc @vazquez @k88hudson 

I would be nice to have some discussion about a plan for this given some of the new architecture work that is in progress.

**Comment by thisandagain** [comment]
Closing based on discussions we've had thus far re: react and design assets. Will re-address in next heartbeat w/ plan.
