### ISSUE TITLE
Link to offline/epub version of docs from docs website

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#703]
This was filed by @toolness:

>When I'm on a slow/nonexistent internet connection, I like having all my stuff on my local computer so I can access it easily... I couldn't find any info on this in the book, and it wasn't until I read "contributing to these docs" that I found this GitHub repo.

>I guess at minimum, one could just clone this repo and read its markdown files directly to view the docs, but is there an easy way to get the pretty version on one's local computer without an internet connection?

**Comment by k88hudson** [comment]
Note urls are:
* epub: https://www.gitbook.com/download/epub/book/k88hudson/webmaker-mobile-guide
* mobi: https://www.gitbook.com/download/mobi/book/k88hudson/webmaker-mobile-guide
* pdf: https://www.gitbook.com/download/pdf/book/k88hudson/webmaker-mobile-guide

**Comment by pippinlee** [comment]
Happy to help out.

Looks like adding them to the second paragraph of the book (referencing documentation offline), or to the "Contributing to these docs" section could make sense. Have a preference?

**Comment by k88hudson** [comment]
I think it might make more sense to put them on the front page –

Also adding a link called "Download" linking to the pdf might not be a bad idea in the sidebar (see `book.js`)
