### ISSUE TITLE
Template - Change Safety App template

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#705]
No one understands it or click on it. 
The cool thing it shows right now is the combination of a map brick + a call brick.
We should make the title more attractive and general so that people would actually check it out. 
Proposed: 
- Map template
- Create a Map app (but this is not really true)
- Create with a map
cc @k88hudson @vazquez

**Comment by vazquez** [comment]
Some ideas:

- Create a Quick Call App
- Build a Rolodex App (confusing)
- Create a Contact Card

Create a Contact Card is my favourite.

**Comment by LauraReynal** [comment]
Yes for the contact app that would be awesome. 
But what about the map leverage ? If we are going to have the map brick we could test the idea with a static map to start and see if this gets traction ? 


Laura de Reynal
Webmaker

**Comment by thisandagain** [comment]
Let's hold off on this until https://github.com/mozilla/webmaker-app/pull/600 lands
