### ISSUE TITLE
Android device back button does not work on all pages 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#707]
Page: choosing a color. 
Clicks on device back button : does not do anything 
Clicks on app back button: does not go back or quit the app

Almost each time we clicked Android Device back button, the app broke. 

==> Need to check back and save for each page.
It works sometimes on some pages, but not for the majority

**Comment by Pomax** [comment]
do we have concrete STR? I tried blogger app -> first text -> pick color, but on that view the back buttons seem to work correclty. Do we have a guaranteed failure that I can debug off of?
