### ISSUE TITLE
Bricks: Counter, Submit, Input 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#709]
- Counter brick is not understood
- Input Brick is not understood 
- Submit brick is not understood
people don't see that Submit is tight to either Counter or Input 

==> 2 reasons why people don't get it:
1- vocabulary is very vague and difficult for non native english speakers 
2- if you are not there, people don't get how those bricks work, either independantly or together. 

Solution: Create the small survey template issue #675 
And....I think this wont be enough, how can we make these 3 bricks more intuitive ? Any thoughts?
Thanks

**Comment by LauraReynal** [comment]
cc @thisandagain some details in this bug as per our earlier chat 
+ the things that people want to count is "Likes"

**Comment by LauraReynal** [comment]
During the 3 weeks of testing in India, this problem was encountered each time. @thisandagain @k88hudson

**Comment by thisandagain** [comment]
:+1: Thanks for the feedback @LauraReynal . Let's talk about this in Seattle and try to sketch a few options. /cc @vazquez
