### ISSUE TITLE
Adjust icon colour choices to incorporate template colours

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#712]
Right now they are different. (try picking a template from /templates and editing the icon – the colour is not one of the choices)

![image](https://cloud.githubusercontent.com/assets/1455535/5744342/1878ed34-9bee-11e4-95ab-6dbe00b2cdbc.png)

**Comment by gesa** [comment]
Should this be removing colors from the array and replacing them with template colors? or just adding more colors?

**Comment by k88hudson** [comment]
hm, good question. @vazquez what is your recommendation here

**Comment by vazquez** [comment]
![colors 2](https://cloud.githubusercontent.com/assets/1119821/5825452/556689ac-a0b9-11e4-89aa-ed0a86bf08e0.png)

**Comment by gesa** [comment]
love this palette @vazquez, but just want to confirm, is this color widow alright?

![](http://snaps.akibraun.com/cxiwk.png)

**Comment by vazquez** [comment]
Thanks for bringing it up Aki, I hadn't realized it lol.

Let's remove the first dark grey (1st one). It occurs to me now that users won't choose that colour because of the cultural implication of the colour black (or very close to) as seen in the field research that Laura is doing.
