### ISSUE TITLE
Improve the Preview view

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#714]
This view needs some UI and usability love.

![2015-01-14 11 36 35](https://cloud.githubusercontent.com/assets/1119821/5745601/014b776c-9bf8-11e4-9c1a-0ada008526e6.png)

**Comment by k88hudson** [comment]
Note that we will be implementing a screen shot service in the future, but it does not currently exist

**Comment by vazquez** [comment]
This is what I'm thinking to improve the Preview view:

![preview view](https://cloud.githubusercontent.com/assets/1119821/5747044/d82d7b36-9c02-11e4-9893-b72da3e94ffe.png)

Redpen @cassiemc: https://redpen.io/fj86a2cb79d2a161b9
cc: @thisandagain

**Comment by vazquez** [comment]
Another idea in an effort to simplify actions on this page:

![preview view 2 1x](https://cloud.githubusercontent.com/assets/1119821/5761494/d1ae9f18-9ca9-11e4-8cbb-4b3f884c00c5.png)

Above, the button becomes buried below, so we would need to move it up top:

![preview view 3 1x](https://cloud.githubusercontent.com/assets/1119821/5761495/d1b1988a-9ca9-11e4-8d53-951b64da4404.png)

**Comment by vazquez** [comment]
Feedback @cassiemc https://redpen.io/fj86a2cb79d2a161b9 and https://redpen.io/kebc109a15d54a153c

**Comment by cassiemc** [comment]
Left some comments on redpen.

**Comment by k88hudson** [comment]
Let's pick this up during the next sprint

**Comment by vazquez** [comment]
R? @cassiemc 

This was the result of a design jam session between Kate and I, we're both happy with the outcome :)

**Comment by cassiemc** [comment]
R- but close – Love the simplified layout. The button language doesn't feel intuitive to me, though.

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/ep9847126f99a1bcf9

The Templates page's title is "Make Your Own App". As such, contextually this button should say: "Make This App". What do you think?

These are other ideas:

- Create App
- Start Building
- Modify This App
- Create & Start Building
- Build This App

**Comment by cassiemc** [comment]
Isn't it more like, "Use this template"? You're still making your own app (not THIS app), you're just using pre-loaded content and structure.

I think something along the lines of "Start building" could work too.

**Comment by vazquez** [comment]
@cassiemc 

Perhaps this is a place where user testing will give us our answer, but I think "Use this template" might be confusing because the user doesn't know we're calling it a template up until this point in the experience.

I have a solution. 

What about adding some introductory text to the Templates page:

![make 11 1x](https://cloud.githubusercontent.com/assets/1119821/5802298/9884de94-9fc1-11e4-9033-99de1ebd8167.png)

This way we can use "Use this template" on the button in the Preview page because there is a taxonomical connection between screens:

![preview view 5 1x](https://cloud.githubusercontent.com/assets/1119821/5802317/bea8d80a-9fc1-11e4-8912-6414cc122140.png)

**Comment by cassiemc** [comment]
Appreciate you thinking this through Ricardo! 

I think I prefer the simplicity of "Start Building" though, rather than modifying the other screen (feels like unnecessary added complexity).

+1 to user testing, that could be really helpful here. cc @LauraReynal

**Comment by vazquez** [comment]
"Start building" is indeed simple and action oriented.

R? @cassiemc https://redpen.io/ep9847126f99a1bcf9

**Comment by cassiemc** [comment]
R+ (so long as both words are usually capitalized in buttons?).

Love how persistent you are @vazquez keep it up. :thumbsup: :thumbsup:

**Comment by LauraReynal** [comment]
Hey guys ! so happy this page gets a new look :) will test this as soon as it is pushed and give feedback asap, but this is looking great :smile: @vazquez @cassiemc 
users were telling me this page was confusing, so I think we are on the right track
