### ISSUE TITLE
Migrate assets to google drive

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#727]
@thisandagain @LauraReynal how would you feel about moving the M4D stuff on dropbox to google drive, since we have this on our Mozilla accounts?

cc @simonwex

**Comment by simonwex** [comment]
:+1: - The billing model for Dropbox is problematic when we add many users to shared folders.

**Comment by thisandagain** [comment]
Yup. Sounds good to me. I was having major problems with the GDrive sync utility on Mac OS 10.10 when we moved to LDAP but it seems to be fixed now.

**Comment by thisandagain** [comment]
https://drive.google.com/open?id=0B-1AZgKn5Nc7fkszYTk5LTdMN2ZwdjJXb1lwM1hzTGEtc2N2ejhxSm5Pc2dkYkRUOVlWUlk&authuser=0

**Comment by vazquez** [comment]
My file is under WMA > GUI > Archives > 201501_ui > Master.sketch
