### ISSUE TITLE
Improve design of "how-to" template

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#731]
* Replace photos with illustrations
* Could use some shortening

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/nabf0752c6e3b46fe9

**Comment by cassiemc** [comment]
Left some Qs

**Comment by vazquez** [comment]
Reposting what I posted on Redpen.

This UI has a little bit of wishful thinking. 

Currently a user would have to enter the • and numbers by hand, yes. However, I imagine us implementing a markdown editor, making this a whole lot easier to the user. I think a use-case like this would definitely benefit from this feature addition.

I added a Github issue to address this feature.

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/nabf0752c6e3b46fe9

**Comment by cassiemc** [comment]
R+

**Comment by vazquez** [comment]
Illustration: https://dl.dropboxusercontent.com/u/43783651/Mozilla/brushes-illustration.svg
