### ISSUE TITLE
Improve design of "Community Announcement" template

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#732]
* Replace photo with illustration
* Improve typography

Any ideas to make this more interactive/exciting?

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/tn0a780c9517707c1b

**Comment by cassiemc** [comment]
I haz questions. Mostly about the news/travel combo theme and who is the target audience for this template.

**Comment by vazquez** [comment]
The user has just tapped on "Share Community News" CTA in the Templates page. As such, what I was thinking for the target audience are individuals who want to share something about their community. 

In this case, I was designing for a person that had discovered Kelso Conservation area, and wanted to share the news with others in his/her community to raise awareness of the camping site as a weekend travel spot.

The "News / Travel" section at the top is just to mimic the sections that one normally sees when reading newspapers. I can remove the section if it causes confusion.

**Comment by vazquez** [comment]
ping @cassiemc for R? https://redpen.io/tn0a780c9517707c1b

**Comment by vazquez** [comment]
ping @cassiemc for review

**Comment by vazquez** [comment]
@cassiemc for R?

The persona we are designing this template for is Lewis, from our Bangladesh Report. Lewis is an artist and community leader. A great use for Lewis would be to post a community bulletin to bring people together for a common cause. He would want to post a bulletin to bring people together to an art exhibit, a call to all spoken word poets, etc. 

We are turning away from "Share Community News" and instead we are going to call the template "Create Community Bulletin"

This is the new design for this template: https://redpen.io/tn0a780c9517707c1b

**Comment by cassiemc** [comment]
Cool, this is clearer to me, thanks. A few things to address, left comments on redpen.

**Comment by vazquez** [comment]
@cassiemc for R?

Addressed feedback. Here you go! https://redpen.io/tn0a780c9517707c1b

**Comment by cassiemc** [comment]
Only niggly is whether this palette in the illustration is webmaker enough, but we can re-assess later. R+!
