### ISSUE TITLE
Add a Horizontal Rule brick

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#733]
It allows us to easily separate content. A good use case can be found in the survey.

![profile 4 1x](https://cloud.githubusercontent.com/assets/1119821/5780639/31e97f58-9d7a-11e4-95dd-b2de6184eb80.png)

**Comment by gesa** [comment]
@vazquez is this something that will need to go through a design process? or is a circle with a line inside (like this) sufficient?
![](http://snaps.akibraun.com/Screen-Shot-2015-01-20-at-16.51.26.png)

**Comment by vazquez** [comment]
I'm in the process of redesigning the Add screen. I should have it done by
Thuesday. For now, however, this looks good :) Go go Designer Aki! :)

Just a note that it is spelled "separator"

On Tuesday, January 20, 2015, Aki <notifications@github.com> wrote:

> @vazquez <https://github.com/vazquez> is this something that will need to
> go through a design process? or is a circle with a line inside (like this)
> sufficient?
>
> <https://camo.githubusercontent.com/fb654d629e87c9105fe31cac2b7688e3f39a46d5/687474703a2f2f736e6170732e616b69627261756e2e636f6d2f53637265656e2d53686f742d323031352d30312d32302d61742d31362e35312e32362e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-app/issues/733#issuecomment-70770195>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by gesa** [comment]
spelling is hard  😳

Thanks Ricardo!
