### ISSUE TITLE
Implement dropdown block

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#734]
Right now there is some code for a dropdown block, but it needs to be re-added and a UX-pass.

**Comment by k88hudson** [comment]
There is some code for a "dropdown" block here: https://github.com/mozilla/webmaker-app/tree/master/blocks/dropdown. Basically we need to add it back into the list of blocks on the "add" view here https://github.com/mozilla/webmaker-app/blob/master/views/add/index.js, although once that is done it will need a UX pass (says @thisandagain)

**Comment by gesa** [comment]
Well thing one I notice while poking around here is that it doesn't have an icon. @vazquez could you help with that?

**Comment by vazquez** [comment]
What do you think @thisandagain? https://redpen.io/tj6ba2b6c0fdd817ae

**Comment by thisandagain** [comment]
R+

**Comment by vazquez** [comment]
SVG asset available here: https://github.com/mozilla/webmaker-app/issues/872

**Comment by thisandagain** [comment]
Moving to backlog in favor of https://github.com/mozilla/webmaker-app/issues/896
