### ISSUE TITLE
Implement survey template

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#736]
Design: https://redpen.io/ywb7a57b152489f041

Ricardo, can you add the image assets here?

**Comment by vazquez** [comment]
SVG Illustration: https://dl.dropboxusercontent.com/u/43783651/Mozilla/survey-illustration.svg

**Comment by vazquez** [comment]
SVG Icon: https://dl.dropboxusercontent.com/u/43783651/Mozilla/survey.svg
