### ISSUE TITLE
Publishing is failing on staging

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#746]
When trying to publish an app (on FF/Mac or Android 4.4), I get:

![screenshot 2015-01-16 15 52 07](https://cloud.githubusercontent.com/assets/51278/5786460/5d62b0e4-9d9a-11e4-97cc-77aaa66ccb08.png)

(yes, i'm signed in)
/cc @k88hudson

**Comment by k88hudson** [comment]
FYI this is an issue with the staging server (https://webmaker-publisher.mofostaging.net/healthcheck)

**Comment by davidascher** [comment]
I'd like us to get cranky about uptime before we actually need to.  Is this
a bug that @jdotpz needs to be aware of?

**Comment by k88hudson** [comment]
@davidascher impossible to say without actually looking into this bug, but it seems like this is a login bug not an ops issue (probably an outdated package if i had to guess)

**Comment by jdotpz** [comment]
I agree with Kate, a 401 Unauthorized should be a login bug.
We haven't seen any alerts on our monitored ELB for this staging app (http://opsview.mofoprod.net:3000/cgi-bin/history.cgi?host=wmpublisher-staging-elb&service=check_elb_node_health).
That said, I've setup a healthcheck monitor for the overall site status, which of course should always coincide with the ELB status, but more visibility is always better than less.  (Almost always)

**Comment by davidascher** [comment]
So, how do we get someone to dig in?  Assign to @jbuck ? /cc @simonwex

**Comment by k88hudson** [comment]
@davidascher @jbuck is already assigned and this ticket is included in the current milestone

**Comment by jbuck** [comment]
I think the issue is that the staging env does not have the correct secret key for cookie signing. I'm changing it to match the other staging apps, and I'll test publishing an app once that's done.

**Comment by jbuck** [comment]
This appears to have fixed the login bug, but now I receive a 500 Access Denied error.

**Comment by k88hudson** [comment]
@jbuck Access Denied sounds like S3 key problems to me

**Comment by jbuck** [comment]
Indeed, the IAM user didn't have permissions necessary to write files. I added the permissions, and now I get a "The specified key does not exist." error.

**Comment by jbuck** [comment]
Steps to fix this:
- [ ] deploy static files to S3 bucket
- [ ] add s3 deploy task to travis

**Comment by jbuck** [comment]
Confirmed, everything is working.

**Comment by davidascher** [comment]
thx @jbuck
