### ISSUE TITLE
Login regression: Checkbox alignment is off

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#747]
I thought i saw an issue about this go by, but filing anyway:
![screenshot 2015-01-16 15 51 51](https://cloud.githubusercontent.com/assets/51278/5786617/047d0012-9d9d-11e4-8501-b5926aae9437.png)

**Comment by k88hudson** [comment]
Seems like a regression

**Comment by k88hudson** [comment]
Since we decide to remove login moving to backlog
