### ISSUE TITLE
Redesign Vendor Template

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#748]
Improve visual content on the vendor template. There has been some notes written on this in #458.

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/qa147e90fc1216193b

**Comment by vazquez** [comment]
Ping @cassiemc for Review

**Comment by cassiemc** [comment]
@vazquez R- a few tweaks.

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/qa147e90fc1216193b

**Comment by cassiemc** [comment]
Left a few comments on color. Any resolution around including product price and description in this template?

**Comment by vazquez** [comment]
R? @cassiemc https://redpen.io/qa147e90fc1216193b

The colours are on brand now (the shadows were made by bumping up the saturation)

I talked to Kate and this is functionality that we currently don't have and would require some UX thinking. We think it would be a brick of its own, called Product (or something like that) that would allow the user to build out a product list, price, and description. I will file an issue for this.

**Comment by cassiemc** [comment]
Ok, R+ :)

**Comment by vazquez** [comment]
Shop Asset: https://www.dropbox.com/s/zksaoty4z5jc9a9/shop.svg?dl=0
Tea Asset: https://www.dropbox.com/s/bja5f06xrdm601d/tea.svg?dl=0
Pie (yum) Asset: https://www.dropbox.com/s/rhg17uu31pukrv5/pie.svg?dl=0
