### ISSUE TITLE
Turn off appcache

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#749]
Perhaps now that we're bundling assets in the cordova package we don't really need appcache anymore... thoughts?

The only thing that we might want to consider using it for is network requests, although if we figure out some kind of real offline db mirroring solution (via localforage or something) we won't need it for that either

**Comment by davidascher** [comment]
Don't we need appcache to deal with app updates after-the-initial install?

**Comment by k88hudson** [comment]
@davidascher unfortunately there are no mechanisms in appcache to help with that. The trade off of not using the iframe approach is that we can't really do in-app updates anymore (at least, the way were originally planning to do)

**Comment by davidascher** [comment]
Ah, that's a problem.  Let's talk off-bug, as doing in-app updates is a
non-negotiable feature.

**Comment by k88hudson** [comment]
@davidascher sure, happy to discuss
