### ISSUE TITLE
Image uploading: Store images from device locally until publish

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#751]
We can likely do this with localForage, as it supports storing binary assets.

The ideal situation would be:

* When a picture is taken and saved in a block, store it/link to it locally
* Only actually upload/swap out the URL in the block when the user initiates publish

Does that sound sane?

**Comment by davidascher** [comment]
+1

Two general themes in terms of dealing with network usage:

 * be predictable
 * be thrifty

The scheme you present does the former well.  I think there's a separate
question about whether we should upload full-res images on devices w/ much
higher res cameras than screen resolution, but that's probably best
discussed somewhere else.

**Comment by k88hudson** [comment]
Ok here is the strategy for this:
* when a user takes a picture, instead of setting a data url on the firebase object, store the image via localForage and set `$data.imageLocal` instead of `$data.value` https://github.com/mozilla/webmaker-app/blob/master/components/block-editors/image/index.js#L16.
*  It might also be a good idea to store a hash/version with it so we can tell whether or not we have to re-upload a remote copy, but a filename/keyname would probably work for that
* In https://github.com/mozilla/webmaker-app/blob/master/lib/publish.js or https://github.com/mozilla/webmaker-app/blob/master/views/share/index.js#L113, publish the `imageLocal` value if the `imageRemote` value doesn't exist or has a different hash/keyname

**Comment by k88hudson** [comment]
@thisandagain @vazquez so @jbuck wants to know if we can we remove the URL option for images, and only allow from gallery/from camera? I would be in favour of this

**Comment by thisandagain** [comment]
:+1: from my POV. @vazquez ?

**Comment by vazquez** [comment]
It simplifies the experience. I'm an aye :+1:

**Comment by k88hudson** [comment]
I think given the extendI'd prefer to land this on a branch/land on master after MWC and stick with the Data URI strategy for now/focus on improving the UX

**Comment by k88hudson** [comment]
there are still issues with making sure the data URIs get uploaded in time/don't block publishing, thoughts @jbuck?

**Comment by thisandagain** [comment]
Tracking in https://github.com/mozilla/api.webmaker.org/issues/8
