### ISSUE TITLE
Webmaker app should not use calc

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#753]
Doesn't work in 4.2 :(

http://caniuse.com/#feat=calc

cc @gvn @flukeout just so you know

**Comment by gvn** [comment]
Heh I didn't even know this existed! :dancers:

**Comment by k88hudson** [comment]
hah yeah it's useful.

**Comment by gvn** [comment]
Well now that I know about it I'll be sure to not use it. Lulz.
