### ISSUE TITLE
Design UI for Editor

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#754]
Based on prototypes created in #607, refine the UI for the editor.

**Comment by k88hudson** [comment]
@vazquez do you need my sketch files for this?

**Comment by thisandagain** [comment]
:+1: would be great to get the source. Speaking of, @flukeout do we have access to your source for the prototypes?

**Comment by k88hudson** [comment]
https://drive.google.com/file/d/0B9Spnx3qAl7pWmhOaUxGbWJKTTA/view?usp=sharing

**Comment by vazquez** [comment]
UI Assets: https://dl.dropboxusercontent.com/u/43783651/Editor%20Assets.zip

**Comment by thisandagain** [comment]
:boom: Thanks @vazquez 
/cc @gvn

**Comment by vazquez** [comment]
Redpen: https://redpen.io/dccd679b59a724685f

**Comment by vazquez** [comment]
UX Interaction: http://flukeout.com/examples/mobile5/#

**Comment by vazquez** [comment]
This is the Sketch File for the UI Editor: https://www.dropbox.com/s/nogxrg4cef36c1e/UI-Editor.sketch?dl=0

**Comment by vazquez** [comment]
Closing this design issue, build issue is in #790
