### ISSUE TITLE
Figure out auto-updating

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#758]
We need to be able to do this from within the app.

Our original strategy was to use an iframe. There are other things we can consider.

We need to figure this out pre 1.0

**Comment by thisandagain** [comment]
:+1: Lots of ways to tackle this without descending into iframe madness as per our original approach. Perhaps this is something we can discuss during the work week?

**Comment by k88hudson** [comment]
@thisandagain sounds good
