### ISSUE TITLE
Localization walk-through / QA

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#760]
We need to walk through the app in each of our 4 target locales (+ en-US) to check for:
- Missing strings
- UI that is squished / un-even / etc

For each issue a ticket should be filed and attached to this localization milestone with a screenshot.

**Comment by thisandagain** [comment]
@alicoding to provide final locales / languages based on Transifex community activity for India.

**Comment by alicoding** [comment]
Ref to https://github.com/mozilla/webmaker-app/issues/763

**Comment by alicoding** [comment]
This ticket will have to stay open until we have all the locales we want to support fully translated 100% and also integrated into the repo.

**Comment by alicoding** [comment]
* Spanish (Mexico) 100%
* Portuguese (Brazil) 100%

**Comment by secretrobotron** [comment]
Should depend on https://github.com/mozilla/webmaker.org/issues/1268 too, probably.
