### ISSUE TITLE
Use paid service to bring target locales up to 100%

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#762]
At the end of the sprint (if we still have gaps in our localizations for each target locale) we should put through an order for Transifex's paid service to bring each locale up to 100% complete.

**Comment by alicoding** [comment]
I'm going to close this since Transifex doesn't offer any of the language we want and I'm going to try ask the community from various team and also our contributors that @LauraReynal introduce as well.

**Comment by thisandagain** [comment]
Great. Thanks for the update @alicoding
