### ISSUE TITLE
Make sure we support all four countries for localization

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#763]
- [x]  Bengali (Bangladesh)  
- [x]  Portuguese (Brazil)  
- [x] Swahili (Kenya) 
- [x] Hindi (India)

For Indian we have these, but only the first two is our P1:
* Panjabi
* Kannada
* Oriya
* Telugu
* Tamil
* Malayalam

We also want to support

**Comment by alicoding** [comment]
We got Bengali (India) and Hindi (India) covered and translated 100% \o/

**Comment by thisandagain** [comment]
:tada: :smile: Thanks @alicoding . Just sent a note on the Swahili coverage, hopefully we can find a volunteer(s).

**Comment by alicoding** [comment]
I just made an announcement to the community to get the file to be translated.

Track it here: https://www.transifex.com/projects/p/webmaker/resource/webmaker-app/

**Comment by alicoding** [comment]
I think this is good now so closing this.
