### ISSUE TITLE
Find contributors/translators for Kenya language support: Swahili

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#764]
Currently we don't have that support on our Transifex project here https://www.transifex.com/projects/p/webmaker/ if we can't find one we might have to use paid service here, but it would be nice to find so we can verify strings and do QA on that language.

**Comment by LauraReynal** [comment]
Reached out to all community members I know - @alicoding feel free to bounce on my email and detail more. 
Will do a Facebook post in the group as well. But Ali, what is the link to send people too when they are ready to start working ?

**Comment by alicoding** [comment]
@LauraReynal this might be a bit outdated, but still work https://support.mozilla.org/en-US/kb/translate-webmaker

**Comment by LauraReynal** [comment]
@alicoding I'll let you give the instructions, as they ask for Transifex details in the email thread.

**Comment by alicoding** [comment]
89% done so far \o/ https://www.transifex.com/projects/p/webmaker/language/sw/
