### ISSUE TITLE
delete my apps should ask for confirmation

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#775]
I was exploring whether I could delete a single app, and a) I can't, and b) when I hit the "delete my apps" not only are all my apps apparently deleted without a confirmation step but I'm also signed out, which I didn't ask for (and signing in is a pain, even w/ login3).

**Comment by thisandagain** [comment]
As per discussion with @k88hudson and @gvn we are going to remove this functionality from the profile view and move it into the hidden developer menu.

**Comment by thisandagain** [comment]
Resolved in https://github.com/mozilla/webmaker-app/pull/971
