### ISSUE TITLE
Shorten publish urls for staging

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#778]
Feels like we probably need our own url shortener in front of those s3 URLs.
![2015-01-21 22 35 26](https://cloud.githubusercontent.com/assets/51278/5847756/aea1ca32-a185-11e4-8448-84244e05f142.png)

**Comment by k88hudson** [comment]
Eventually we should set up a cloud front distribution in front of the bucket, although having a URL shortener is a good idea too

**Comment by k88hudson** [comment]
Ok, done.
