### ISSUE TITLE
Add language selector in the profile

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#779]
For development at least I think this is needed because currently changing the locale using the query is not persistent and it is a bit annoying when changing the page/refresh and it is back to English again.

**Comment by alicoding** [comment]
I think is not worth spending time on this for now since we have `navigator.language` set but it just doesn't pick up the right locale, so I'm going to file and fix this instead of making a selector that might never be use in the future.

**Comment by thisandagain** [comment]
:+1:
