### ISSUE TITLE
same language but different country

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#780]
This is not easy to solve, and I have done so many research about this and never really get a clear answer to this topic. Also, it can cause serious problem if we don't do this right.

Say we have Bangla language support, but what Bangla should this be when a user enter Webmaker app? Should we always assume that this will be Bangla Indian? What if a Bangla from Bangladesh enters our site? Would this offend them? Why? because we simply assume they are from India but they are not! 

This is not going to be just the case of Bangla, but it will be the same for many others. What I think we need the discussion for here is to know who are the users that we are targeting and making sure we are displaying the right locale.

When we do translation for `bn-IN` (Bangla [India]) the browser not necessary give you the right locale because it is depend on the user's setting. It can be `bn` or `bn-IN`, so we need to make sure we can support both for user who speaks Bangla.

**Comment by thisandagain** [comment]
Really *really* good question. Based on our research in Bangladesh I recommend that we support both `bn-IN` and `bn-BD`. This will avoid some potentially awkward situations with eventual "near me" functionality in the explore / discovery gallery as well as make sure that we are being sensitive to the strong historical connection between language and nationality in this instance.

/cc @k88hudson @LauraReynal

**Comment by LauraReynal** [comment]
:+1: We need to make a difference between the 2 ! YAY ! **thank you** @alicoding for raising this point :high_brightness:

**Comment by alicoding** [comment]
So, the only thing I'm not clear yet is that if the locale request is `bn` what should this be redirect to? `bn-IN` or `bd-BD`?

I'm going to do more of browser's research to see what their locales set for the one we care, but we have to deal with this on Webmaker desktop before for many different locales.

**Comment by jbuck** [comment]
Would it be possible to ask the user?

**Comment by alicoding** [comment]
What language should we ask them? If they come in with Chinese what Chinese language should we ask? Or ask them in English and list with all possible locales support? I’m just using Chinese as an example but it will be similar to Arabic, Telugu and other locales as well.

**Comment by jbuck** [comment]
Hm, maybe you just have a modal dialog that presents the N choices as buttons, with translations for each locale to choose from?

**Comment by alicoding** [comment]
I'm not sure how the UX for that will be since we are going to have multiple languages in the dialog, but that might work.

**Comment by thisandagain** [comment]
If a user comes in as `bn` we should direct to `bn-BD`. Prompting the user is not reasonable / normative UX for mobile apps.
