### ISSUE TITLE
CSS Source maps seem broken

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-app#783]
I think the source maps are broken, which makes debugging CSS more time consuming.

**Comment by gesa** [comment]
I have spent WAY more time on this than I probably should have on this, but this is a *really* weird bug.
I was playing around with [gulp/less.js](https://github.com/mozilla/webmaker-app/blob/master/gulp/less.js) and no matter how I write the sourcemap, Firefox just WON'T accept that it's there. Chrome is fine whether the sourcemap is written inline (how it's currently done) or if it has it's own `.css.map` file. Either way Chrome can tell which `.less` file a rule came from. Firefox just can't seem to comprehend either though. I've scoured the internet high and low, and no one else in the whole wide world seems to be having this problem.

**Comment by alicoding** [comment]
I think there is something wrong with gulp/less.js or `watch` task I'm not sure, but yesterday I spent over an hour or two just trying to debug something with the syntax and it was just because LESS wasn't compiling for some reason.

**Comment by gesa** [comment]
Well the weird thing about the sourcemaps thing is that they **are** being generated. And to my eye the syntax of either `/*# sourceMappingURL=common.css.map */` or `/*# sourceMappingURL=data:application/json;base64,[massive base64 encoded json here] */` looks right. Or, in other words, they are being generated properly. Firefox just isn't down with the game. Or something.

**Comment by gvn** [comment]
FWIW: Source maps weren't working for me in Chrome before and now they are. So...progress! :+1:
