### ISSUE TITLE
Add "Start from Scratch" template view

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#804]
Based on the current UI, we are showing this after a user taps on the "Start from Scratch" template:

![screen shot 2015-01-27 at 11 56 41 am](https://cloud.githubusercontent.com/assets/747641/5925900/bebaee18-a61b-11e4-96bd-52117c326efd.png)

**Comment by vazquez** [comment]
I was thinking the same. We need an empty view.

**Comment by vazquez** [comment]
![preview view 9 1x](https://cloud.githubusercontent.com/assets/1119821/5941789/317b0b16-a6e1-11e4-8151-e94c54459454.png)

**Comment by k88hudson** [comment]
it would be interesting to consider an onboarding experience here for first-time users

**Comment by thisandagain** [comment]
Dropped a few notes in the redpen here: https://redpen.io/sy619ddb5f003a9462

**Comment by vazquez** [comment]
### Design

When a user taps on "Start from Scratch", they get welcomed with this empty view:

![preview view 9 1x](https://cloud.githubusercontent.com/assets/1119821/5982375/4012157e-a890-11e4-9f86-851966a40b6b.png)

**Action:** User taps on the + icon. They get sent to this screen:

![editor - edit 22i](https://cloud.githubusercontent.com/assets/1119821/5982399/929da4ac-a890-11e4-8e74-1940e1005256.png)

The text icon will include an animation, perhaps a bounce up and down, or maybe a signal animation. We can experiment here to see what feels better. 

**Action:** User taps on the Text icon and creates some content. A popup will show when they return to the main view in order to engage the user in creating more content:

![preview view 10 1x](https://cloud.githubusercontent.com/assets/1119821/5982647/22aa97e2-a893-11e4-8409-4e7e285dab36.png)

**Comment by davidascher** [comment]
There's no redpen for this design, so dumping here -- and I realize this is still a conceptual mock.

Do we have a "brand attributes" spec for this app?  Something that articulates the "voice" of the app, even copy aside?

Reason I ask is the smily face feels childish to me, and I don't think is appropriate for an audience of e.g. microentrepreneurs in Kenya.  I'm a big fan of whimsy and fun and a sense of humor (Slack pulls this off beautifully for example), but it's hard to pull off, and very hard to make it localization-resistant.

**Comment by thisandagain** [comment]
Really good question @davidascher. Consistent feedback from field research has been that the app feels very cold / utilitarian and needs more character. While this does feel *a bit* too juvenile, I think it's headed in the right direction. @vazquez perhaps we can play with the look & feel of the character and the copy a bit to bring it into a more mature stance. Benchmarks for this are Duolingo and Foursquare.

**Comment by davidascher** [comment]
Great to hear about the research and to see the benchmarks.  I'm very supportive of us getting more "character," and wanted to flag the fact that in contrast to a lot of our prior work, we're not really targeting a particular young audience w/ this app.  So yes to playful.  Looking forward to the next iterations.

**Comment by vazquez** [comment]
R? @thisandagain [flagged!]

https://redpen.io/kb988058740193b9a1

**Comment by thisandagain** [comment]
Awesome. R+ :cactus: :vhs: :zap: :palm_tree:

**Comment by thisandagain** [comment]
@alicoding to clarify, the objective here is to have the "Start from Scratch" template by-pass the preview view and go right into the editor where the user will see the toucan illustration and prompt to add content.

**Comment by alicoding** [comment]
Should the user always see the message when they click on "Start from Scratch" or we want to make sure we capture the state if they have clicked on that before we shouldn't be displaying that again?

**Comment by vazquez** [comment]
I vote all the time, at least for now. @thisandagain? [flagged!]

**Comment by alicoding** [comment]
@vazquez can I also get the asset for this one as well? (That bird's image or whichever we want to use)

**Comment by thisandagain** [comment]
All the time is cool for now when a user has 0 blocks.

**Comment by vazquez** [comment]
Toucan 1: https://www.dropbox.com/s/m4om581ctskyxz3/toucan1.svg?dl=0
Toucan 2: https://www.dropbox.com/s/jiwwwtzoglzq5cs/toucan2.svg?dl=0
