### ISSUE TITLE
Re-design back button

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#806]
Our current back button was designed with the Firefox OS style-guide in mind. As the visual design of the app has developed, this icon could use some attention:

![screen-shot-2015-01-27-at-1 10 40-pm](https://cloud.githubusercontent.com/assets/747641/5927308/74f415d8-a626-11e4-8359-acb58a166da1.png)

/cc @vazquez

**Comment by vazquez** [comment]
This was a pet peeve of mine so I've already created one to subsitute! I will show it to you tomorrow during our UI walkthrough

**Comment by vazquez** [comment]
![screenshot 2015-01-28 12 06 34](https://cloud.githubusercontent.com/assets/1119821/5942529/2d342178-a6e6-11e4-884c-95e0ddf18d62.png)

**Comment by vazquez** [comment]
SVG asset: https://dl.dropboxusercontent.com/u/43783651/Mozilla/back.svg
