### ISSUE TITLE
Implement new tab menu

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#807]
The visual design of the primary menu was done pretty quickly and could use an update to bring it more in-line with the visual style that @vazquez has brought to the editor and template illustrations as well as integrate more nicely with [Android's primary navigation](https://dribbble.com/shots/344108-Pocket-Casts-Android-3-7-Tab-Bar?list=searches&offset=6). I'd also like to think about how the tab bar should animate / transition between views:

![screen-shot-2015-01-27-at-1 10 40-pm](https://cloud.githubusercontent.com/assets/747641/5927342/b6331e68-a626-11e4-9411-6764327a4429.png)

#### Benchmarks
http://thenextweb.com/apps/2013/11/21/tumblr-redesigns-ios-app-adds-activity-tab-track-new-likes-reblogs-followers/
https://dribbble.com/shots/1766396-Animated-Tab-Bar-Icons-UX-UI-Interface-Mobile-App?list=searches&tag=tab_bar&offset=2
https://dribbble.com/shots/619231-Explore?list=searches&tag=tabbar&offset=1
https://dribbble.com/shots/1240169-Sleep-Cycle?list=searches&tag=tabbar&offset=7

**Comment by vazquez** [comment]
What do you think @thisandagain? [flagged!]

https://redpen.io/tn5a18950dcd0f646c

**Comment by vazquez** [comment]
Finalists!

R? @thisandagain [flagged!]

https://redpen.io/tn5a18950dcd0f646c

**Comment by vazquez** [comment]
Final design: https://redpen.io/tn5a18950dcd0f646c
Icons are available on the M4D Dropbox folder: https://www.dropbox.com/sh/fw70qhcdkqjibo6/AAAha5e0hM5nqxh9CBisdw9Ta?dl=0

Ready for implementation! :cow: :star:
