### ISSUE TITLE
Update visual design of loading state

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#808]
I'd like to look at some other options for non-determinate loading indicators outside of the blocking GIF that we have today:

![screen shot 2015-01-27 at 1 29 56 pm](https://cloud.githubusercontent.com/assets/747641/5927625/aee1a344-a628-11e4-8829-453e7fd0eef0.png)

#### Benchmarks
Inbox (Android)
Google Drive (Android)
Kickstarter (iOS)
Hyperlapse (iOS)

**Comment by k88hudson** [comment]
note that it's a CSS animation also a bit choppy/buggy on android at the moment, so if we keep/change we should do some work to test on device. i'm finding certain animation types run better than others on device

**Comment by vazquez** [comment]
First exploration. Send forth thy thoughts @thisandagain [flagged!]

![untitled-1](https://cloud.githubusercontent.com/assets/1119821/6154059/e154c520-b1f6-11e4-8ca6-70fc654e971c.gif)

**Comment by thisandagain** [comment]
Tracking in #1455
