### ISSUE TITLE
Android - Hide "Cancel" and back buttons

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#810]
When on Android, we should hide the "Cancel" as well as the "<" buttons in favor of the OS-level back button.

![screenshot_2015-01-27-14-13-27](https://cloud.githubusercontent.com/assets/747641/5928560/0ac5a1e4-a631-11e4-89da-e5ac3f58794c.png)

![screenshot_2015-01-27-14-10-12](https://cloud.githubusercontent.com/assets/747641/5928606/5869d1ae-a631-11e4-8300-5d7793298178.png)

**Comment by k88hudson** [comment]
I still see android back buttons on a LOT of applications, are you sure about this?

**Comment by k88hudson** [comment]
specifically, I see it used in child views 
![image](https://cloud.githubusercontent.com/assets/1455535/5962349/4cc3a7b8-a7b1-11e4-90a4-06441ee4cb93.png)

**Comment by thisandagain** [comment]
Hmm... let me check the guidelines, last I looked it wasn't preferred.

**Comment by thisandagain** [comment]
Looks like it's still reserved for transitioning between sibling views (same as >= 2.4). It's hard for us to designate what is a sibling and what is a view change as we aren't working natively, but I think the only place where we have a sibling relationship is the component "edit", "add", and "name / icon" screens within the "make" view:

![siblings](https://cloud.githubusercontent.com/assets/747641/5967943/17295aa6-a7c7-11e4-8c99-335d7da1975b.png)

My recommendation:
- Remove the "<-" and "Cancel" buttons for all views on Android, *except*
- Create a standard (matching) execution for the "edit", "add", and "name / icon" views

@k88hudson @vazquez Thoughts? Any siblings that you think I'm missing?
