### ISSUE TITLE
Implement New Buttons

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#818]
Let's do some iterations of how our buttons styles could look like.

**Comment by k88hudson** [comment]
One thing I'd love to see here is a pressed state for buttons (and anything that is tappable, tbh)

**Comment by thisandagain** [comment]
:+1: on consistent use of "down" states for tappable elements.

**Comment by vazquez** [comment]
What do you think @thisandagain [flagged!] https://redpen.io/dg31f1dab585c0b466

**Comment by vazquez** [comment]
@thisandagain has R+'ed. I will post the final button iterations.

**Comment by vazquez** [comment]
New buttons styles are here. We have two different buttons for a standard button, and a submit button.

Redpen: https://redpen.io/dg31f1dab585c0b466
Button prototype: http://codepen.io/rvazquez/pen/gbGzye

**Comment by k88hudson** [comment]
Love it ++

**Comment by thisandagain** [comment]
@gvn @Pomax This is ready for implementation.

**Comment by Pomax** [comment]
rewriting the less to effect this, but it looks like the pressed state is not as sharp as the unpressed state due to the box-shadow spread. Was that intentional?

**Comment by Pomax** [comment]
the share-dialog seems to have a rogue "not caught by button.less" class btn-cell, what do we want to do with that?

![screenshot 59](https://cloud.githubusercontent.com/assets/177243/6089228/73328900-ae14-11e4-8e9e-52b521a88794.png)

**Comment by Pomax** [comment]
Also seeing a btn-delete in the less, but the delete button doesn't seem to use it at all.

![screenshot 62](https://cloud.githubusercontent.com/assets/177243/6089281/1f86dd1e-ae15-11e4-9c3f-41c8ca1a7a49.png)

**Comment by vazquez** [comment]
For buttons within cells, we do the same treatment but we modify the padding so that the button is a bit thinner.

![screenshot 2015-02-06 18 36 13](https://cloud.githubusercontent.com/assets/1119821/6089328/0dcecd4c-ae2f-11e4-8bfa-e21259189a30.png)

**Comment by vazquez** [comment]
Re: Delete button. Good catch. Let's change that.

Do we update the delete and cancel buttons in this ticket, or would you prefer we file a new issue?

**Comment by Pomax** [comment]
I'm okay with slipping it in here, since it's still button styling.

**Comment by Pomax** [comment]
There's a number of colours that we need here that are not in colors.less, do we want to formalize those here so the LESS changes don't use magic hex codes, or are magic hex codes just fine?

**Comment by Pomax** [comment]
screenshots attached to the PR

**Comment by vazquez** [comment]
Hey man,
Im no longer in front of my computer, but I will get these colours to you
by tomorrow so that Monday first thing you're good to apply changes.

On Friday, February 6, 2015, Mike Kamermans <notifications@github.com>
wrote:

> There's a number of colours that we need here that are not in colors.less,
> do we want to formalize those here so the LESS changes don't use magic hex
> codes, or are magic hex codes just fine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-app/issues/818#issuecomment-73338424>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by vazquez** [comment]
I have updated the Codepen to include the delete and cancel buttons: http://codepen.io/rvazquez/pen/gbGzye
