### ISSUE TITLE
Check your email screen copy and UI improvements

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#824]
- Checkbox is completely out of alignment with its label.
- Copy doesn't make sense from a mobile context.

![screenshot 2015-01-28 12 47 25](https://cloud.githubusercontent.com/assets/1119821/5943317/e4c6875e-a6eb-11e4-968e-91ca066e3fba.png)

**Comment by tanay1337** [comment]
@k88hudson Would like to take this, where do I need to make the changes?

**Comment by k88hudson** [comment]
@tanay1337 this will need to happen with the `webmaker-login-ux` package, however, some design work needs to be done by @vazquez first before the implementation can be done.
