### ISSUE TITLE
Standardize icons in Template view

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#825]
The icons don't feel like they come from the same family, aesthetically speaking. We can improve on a few to make them more cohesive.

**Comment by gesa** [comment]
Is it possible to make all of these SVGs? I'm running into a problem on #833 because some icons are png and some are svg.

**Comment by thisandagain** [comment]
(Follow-up from IRC thread):
Vector assets available here: https://www.dropbox.com/s/txifl55ddcn5yjl/placeholders.ai?dl=0

![vibsshgukn8i1yxvudpymiipdtyeuwimruqdzlnzxwq](https://cloud.githubusercontent.com/assets/747641/5967625/d580dbae-a7c3-11e4-8b30-bffaca0ffddd.png)
