### ISSUE TITLE
Preview should not be a window

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#831]
The preview screen should not be a frame for which the app is displayed on, but rather it should display the whole preview at once without the need to use any scrollbars or windows.

![screenshot 2015-01-28 13 09 38](https://cloud.githubusercontent.com/assets/1119821/5943683/15c5a7e2-a6ef-11e4-987b-e3c68a438fa8.png)

**Comment by k88hudson** [comment]
@tanay1337 is going to take this one

**Comment by gvn** [comment]
Looks like this has been resolved...
