### ISSUE TITLE
Add animation to icon chooser

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#833]
We should add an animation to the icon chooser, it feels like a swipe gesture so we should animate for that effect.

![screenshot 2015-01-28 13 11 29](https://cloud.githubusercontent.com/assets/1119821/5943718/5c376de6-a6ef-11e4-8cef-8e4687fe195b.png)

**Comment by k88hudson** [comment]
@Pomax actually @gesa is already working on this
