### ISSUE TITLE
Implement Universal Done button

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#834]
Something like this:

![screenshot 2015-01-28 13 15 17](https://cloud.githubusercontent.com/assets/1119821/5943775/bf63d27e-a6ef-11e4-8651-e5af22cce526.png)

**Comment by k88hudson** [comment]
:heart: love it

**Comment by vazquez** [comment]
R? @thisandagain https://redpen.io/jgf0776e463d7fb269

This would replace all instances where we are currently displaying "Done" in the top right hand side.

**Comment by thisandagain** [comment]
R+

**Comment by vazquez** [comment]
Disabled state: https://redpen.io/ud6f8ec7d4e09bbbbf
Enabled state: https://redpen.io/jgf0776e463d7fb269

The checkmark icon is available as part of the Ionic framework icons. 
CSS class name: `ion-checkmark-round` Font-size: 18px

**Comment by thisandagain** [comment]
@vazquez Do you have a hex color for the "down" state of the enabled button?

**Comment by vazquez** [comment]
Yes! `#589EEA` for the pressed state of the enabled button

**Comment by thisandagain** [comment]
@vazquez Can we get an updated version of this that takes the new header into account?

**Comment by vazquez** [comment]
Good catch! On it :shipit:

On Monday, February 9, 2015, Andrew Sliwinski <notifications@github.com>
wrote:

> Assigned #834 <https://github.com/mozilla/webmaker-app/issues/834> to
> @vazquez <https://github.com/vazquez>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-app/issues/834#event-232869180>.
>


--  [[unflagged]](http://plzkthx.herokuapp.com)
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by vazquez** [comment]
New design! :boom: 

Inactive State: https://redpen.io/ud6f8ec7d4e09bbbbf
Active State: https://redpen.io/jgf0776e463d7fb269

The inactive state is at 30% opacity. Active state goes to a full 100% opacity.
The dark blue is used in segmented control, but just in case you need it it's `#315D8A`

The checkmark icon is available as part of the Ionic framework icons.
CSS class name: `ion-checkmark-round` font-size: 18px

**Comment by Pomax** [comment]
implemented in PR https://github.com/mozilla/webmaker-app/pull/1022

**Comment by Pomax** [comment]
UX implement and fully functional for color picker in https://github.com/mozilla/webmaker-app/pull/1024

**Comment by Pomax** [comment]
landed via #1022 and #1024
