### ISSUE TITLE
Redesign Data view

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#835]
Redesign this

![screenshot 2015-01-28 13 25 18](https://cloud.githubusercontent.com/assets/1119821/5943949/1defcb26-a6f1-11e4-897a-73d513b3ae5b.png)

:meat_on_bone:

**Comment by vazquez** [comment]
R? @thisandagain [flagged!]

https://redpen.io/xocb5ef9fd726a57b0

**Comment by thisandagain** [comment]
Perfect. Thanks @vazquez R+

**Comment by thisandagain** [comment]
@gvn @Pomax This is ready to go.
