### ISSUE TITLE
Implement new back button

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#837]
As per design in #806 
SVG asset: https://dl.dropboxusercontent.com/u/43783651/Mozilla/back.svg

**Comment by k88hudson** [comment]
I kinda feel like we should be using the android back button

**Comment by k88hudson** [comment]
which is

![image](https://cloud.githubusercontent.com/assets/1455535/5962010/9175b958-a7ae-11e4-9fb2-aaa65de274ad.png)

**Comment by vazquez** [comment]
I'm also seeing it expressed as this in the Android design docs 
https://developer.android.com/design/patterns/navigation.html

![screenshot 2015-01-29 13 25 23](https://cloud.githubusercontent.com/assets/1119821/5963450/561de5d6-a7ba-11e4-9289-6548cb9d1e0d.png)

I'll do more research!

**Comment by davidascher** [comment]
see also http://developer.android.com/design/patterns/navigation.html

**Comment by vazquez** [comment]
We are moving forward with the standard Android back button! 

SVG Asset: https://dl.dropboxusercontent.com/u/43783651/Mozilla/back.svg
