### ISSUE TITLE
Implement Preview view

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#839]
The Preview screen is accessed when the user is on their Profile and click on any of their apps.

**Comment by vazquez** [comment]
@thisandagain Take a look at this: https://redpen.io/vraf9ede99ae4f8086

**Comment by vazquez** [comment]
@thisandagain R? https://redpen.io/wy5af842444b6a2667

**Comment by vazquez** [comment]
There are alternative "App Data: icon treatments here:

- https://redpen.io/uy3441b4568470c09f
- https://redpen.io/ze034632758fd0c2b2

**Comment by k88hudson** [comment]
Implementation ticket filed here. https://github.com/mozilla/webmaker-app/issues/868 
Please update with finalized designs once you have them

**Comment by vazquez** [comment]
R? @thisandagain [flagged!]

Admin: https://redpen.io/ck555642cf38b02adb
Consumer: https://redpen.io/vd06771345f2712a65

**Comment by thisandagain** [comment]
Left a few comments in redpen ... getting really close! :smile:

**Comment by vazquez** [comment]
Feedback addressed!

R? @thisandagain [flagged!]

Admin: https://redpen.io/ck555642cf38b02adb
Consumer: https://redpen.io/vd06771345f2712a65

**Comment by thisandagain** [comment]
:smile: Yeah! R+

**Comment by k88hudson** [comment]
:tada: :tada:

**Comment by vazquez** [comment]
Keep in mind there are two different Preview views.

The Admin view is accessed when an owner of the app visits their app.

The Consumer view is accessed when a visitor checks out an app created by someone else.

:shipit:

**Comment by vazquez** [comment]
This issue is ready for implementation! :cow: :star:

**Comment by thisandagain** [comment]
@Pomax can you take this one?

**Comment by thisandagain** [comment]
Tracking implementation at https://github.com/mozilla/webmaker-app/issues/868
