### ISSUE TITLE
Replace toggle element with alternative pattern

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#841]
So I have been doing an insane amount of UI optimization/testing and I have not been able to get the toggle element, that is,

![image](https://cloud.githubusercontent.com/assets/1455535/5961801/255275c8-a7ad-11e4-959f-e9d9619d1a4f.png)

to feel good to people. I tried a number of different strategies:

* binding the toggle thing to swipe/finger position
* just toggling on up/down
* listening to swipes and doing a toggle based on direction

All of them felt way less responsive than alternative UI patterns like buttons/checkboxes. 

There's more that could be done, but I just wanted to call this out. Happy to demo, happy to discuss further.

**Comment by k88hudson** [comment]
cc @thisandagain @vazquez

**Comment by thisandagain** [comment]
@vazquez and I just had a quick catch-up on this. Plan is for @vazquez to design a simple / nice looking checkbox so we can avoid fussing with gestures. Hope that helps @k88hudson !

**Comment by vazquez** [comment]
I am going for a standard Android checkbox treatment. R? @thisandagain https://redpen.io/oj1ca6fe5608fc9fe3
