### ISSUE TITLE
Replace font awesome with ?

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#848]
Some possible options:

* http://zavoloklom.github.io/material-design-iconic-font/icons.html
* http://ionicons.com/ (android subset)
* just use our own

if we use our own, i'd prefer to figure out a more optimized solution that just including individual svgs, preferably generating an icon font

**Comment by thisandagain** [comment]
:+1:

**Comment by vazquez** [comment]
I'm with @thisandagain. My UI design is moving towards an Android aesthetic, as such it would be great to start with an Android icon subset like ionicons.

**Comment by davidascher** [comment]
I'm not worried about these icons, but want to flag that we'll need an
esthetic that looks ok on desktop as well.

**Comment by vazquez** [comment]
We are moving forward with Ionicons.

**Comment by k88hudson** [comment]
resolved
