### ISSUE TITLE
localize unlocalized strings v2

### ISSUE THREAD

**Issue by alicoding** [mozilla/webmaker-app#849]
There seems to be more strings missed or never localized in these files:

`components/modalPrompt/index.html`
`components/publishFooter/index.html`
`components/sideMenu/index.html`

**Comment by davidascher** [comment]
Is it possible to build a travis-triggered test to detect these?

**Comment by alicoding** [comment]
I think it is possible if we can look for a string inside any of the specify tags or DOM in general. So if we don't use `<p>{{ something | i18n}}</p> ` and have it as `<p>something in here</p>` maybe we can safely assume that this is not localized.

**Comment by thisandagain** [comment]
Let's hold off on automating this until after MWC as we'll likely be porting to react which will alter directives / approach.

**Comment by davidascher** [comment]
+1

**Comment by thisandagain** [comment]
Can this be closed @alicoding ?
