### ISSUE TITLE
Change blue variable

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#856]
We are going from:

![screenshot 2015-01-30 15 59 37](https://cloud.githubusercontent.com/assets/1119821/5983184/1106377a-a899-11e4-96e7-57a72364d6bc.png)

to:

![screenshot 2015-01-30 16 00 31](https://cloud.githubusercontent.com/assets/1119821/5983190/1fd6805c-a899-11e4-9efc-5b102325ba40.png)

New Less variable: `@turquoise: #5AA1E8;`

**Comment by k88hudson** [comment]
@tanay1337 want to take this one? the file to update is in the `static/styles` folder

**Comment by tanay1337** [comment]
Sure @k88hudson :) Fixed here: https://github.com/mozilla/webmaker-app/pull/866
