### ISSUE TITLE
SMS sharing doesn't use real contacts

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#860]
and @k88hudson was surprised

dev screen shows version 0.0.16

**Comment by k88hudson** [comment]
@cadecairos can you verify if this is an issue on android/ffos? I am guessing this is a result of installing the web-app build instead of the real packaged firefox os app

**Comment by cadecairos** [comment]
on Android, when running master, the share screen doesn't display at all

**Comment by cadecairos** [comment]
same deal on FXos - am I doing something wrong?

**Comment by cadecairos** [comment]
update: Seems to be a problem in FXOS, not in Android

**Comment by davidascher** [comment]
My app still doesn't use my contacts.  k88hudson -- fixed, and if so, in
what version?

**Comment by cadecairos** [comment]
I'm definitely seeing this on my emulator and Flame device.

**Comment by k88hudson** [comment]
This should be resovled since i removed the cordova shim
