### ISSUE TITLE
Sign-in 'Next' button could be clearer

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-app#862]

**Comment by adamlofting** [comment]
![wm-app-signin](https://cloud.githubusercontent.com/assets/1901816/5999623/7347bd80-aacb-11e4-9e4b-adc96b10a721.png)
It took me a while longer than I'd like to admit to notice that `next` button in the top right. I even tried clicking the title `Sign In To Webmaker` first.

This feels like a place for a big, easy-to-click, momentum-maintaining button below the username field :ghost:

**Comment by gesa** [comment]
Cosign, I encountered the same barrier, not knowing what to tap to move on to the next step.

**Comment by thisandagain** [comment]
:+1: Tracking in #834
