### ISSUE TITLE
Implement new toggle element

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#865]
Design is in #841

**Comment by gesa** [comment]
Oh oops @thisandagain I unassigned myself from this because it was in the wrong milestone and I had thought I self-assigned. Sorry about that! Reassigning to myself now. Should we move this to the "Ship feature-complete" milestone?

**Comment by thisandagain** [comment]
No worries @gesa ! Yup... good catch.

**Comment by vazquez** [comment]
Final design: https://redpen.io/oj1ca6fe5608fc9fe3
The icons are available on Ionicons. 

`ion-android-checkbox-outline-blank` and `ion-android-checkbox-outline`

**Comment by gesa** [comment]
NTS: there's a TODO at https://github.com/mozilla/webmaker-app/blob/master/views/detail/index.html that will need to be fixed when this issue is implemented.

**Comment by gesa** [comment]
So. Ionicon isn't included in webmaker app & isn't available via npm. :frowning: There isn't a super obvious place in the app to dump external libs. (so, [NEEDINFO] @k88hudson )

Other than that though, this is ready! ^_^

**Comment by gesa** [comment]
nm on needinfo @k88hudson 
Blocked by #848
