### ISSUE TITLE
Test and fix or handle any bugs/error states with SMS sharing 

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#874]
I'm concerned about the SMS plugin we're using not being good enough at handling edge cases like SIM cards not being available, etc.

Please look at the following in FFOS and Android and fix bugs or handle error states with appropriate error messages as needed.
* whether your contact list shows up properly
* sending an SMS to a real number
* sending an SMS to a number that doesn't exist
* sending an SMS to an invalid number (if possible)
* trying to send an SMS without a SIM card

and anything else you can find.

**Comment by k88hudson** [comment]
cc @secretrobotron @thisandagain this is probably useful for a QA script as well.

**Comment by cadecairos** [comment]
Preliminary results:

Nexus S, Android 4.4.4, Valid SIM
> whether your contact list shows up properly
It does!
> sending an SMS to a real number
It works! tested sharing, and the send sms button on published apps (asks to open the messaging app)
> sending an SMS to a number that doesn't exist
sending to (555) 555-5555 "succeeds"?
> sending an SMS to an invalid number (if possible)
Not sure how to go about this one
> trying to send an SMS without a SIM card
logs say the sms was sent, but it's a lie. not sure why no errors appear.

**Comment by secretrobotron** [comment]
:+1: thanks!

**Comment by thisandagain** [comment]
@cadecairos do you have a PR that is sending the SMS messages?
