### ISSUE TITLE
Complete "publish footer" component for publish view

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#876]
Original design: https://redpen.io/tg20fe8562fe6ff39d

I think some design updates are needed here @thisandagain @vazquez.

* For firefox os we can have an install button, but for Android, we aren't able to programmatically trigger "add to homescreen" AFAIK. Is there something we can do to indicate to people how to do that?
* What should "sharing" and "learn more" look like in this context? We can use the existing details view, but we will need to publish the code needed for that bundled with that app

**Comment by thisandagain** [comment]
Ok. On the case. :shipit:
