### ISSUE TITLE
Review links/language after creating account on Mobile App

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-app#879]
After creating a new account on the mobile app I see two options:

1. A `Let's Go` button which appears to be greyed out / disable (but does work correctly)
2. A link to explore desktop webmaker, which we probably don't want here

![screen shot 2015-02-03 at 14 11 35](https://cloud.githubusercontent.com/assets/1901816/6021580/cd297b98-abae-11e4-870e-0dd65127ca49.png)

**Comment by tanay1337** [comment]
@thisandagain @k88hudson Can I take this one?

**Comment by davidascher** [comment]
@adamlofting: what user agent? android, ffos, desktop?

**Comment by k88hudson** [comment]
@tanay1337 we are temporarily disabling login, which this is part of, so I would hold off for now.

**Comment by adamlofting** [comment]
@davidascher Hmmm...
I was playing with ffos some of the time yesterday, but I'm pretty sure that screenshot was desktop. Which given the question, might explain the answer :smiley:
