### ISSUE TITLE
Apps created as a guest are "lost" after creating an account

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-app#880]
Steps:
1. Build app(s) as a guest
2. Decide the tool is good :thumbsup:, so create an account 
3. Login
4. User's carefully handcrafted apps appear to be lost :warning: :cold_sweat:
  * They still reside in local storage, so you find them again if you logout
  * But you can't get them into your account

**Comment by thisandagain** [comment]
Tracking in #883
