### ISSUE TITLE
Deploy nightly builds of ffos cordova app + tagged staging builds of android/ffos

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#882]
We deploy a nightly build of the Android APK (see https://github.com/mozilla/webmaker-app-cordova/blob/master/.travis.yml) right now, but we also need to:

* [x] deploy a nightly build of ffos cordova on `branch: master`
* [x] deploy a staging build of android on tags only
* [x] deploy a staging build of ffos on tags only

**Comment by k88hudson** [comment]
So, besides the fact that the zip functionality seems to be busted in cordova, I figured out why the ffos build can't be installed via an install page:

Unless I'm totally missing something, it seems that privileged apps may *only* be installed via marketplace (see https://developer.mozilla.org/en-US/Marketplace/Options/Packaged_apps) 

The only other way to install them AFAICT is via the Web IDE.

Perhaps we can just upload a zip and link to it/ explain how to install? Thoughts @secretrobotron @thisandagain?

**Comment by davidascher** [comment]
We should probably think about putting a beta in the marketplace in time for MWC.  @fwenzel or @digitarald may have advice for how to do that in a way that can evolve to a 1.0 later on.

**Comment by digitarald** [comment]
These 2 packages can help to push apps to the phone via remote debug protocol:
- https://github.com/harthur/firefox-client
- Most recent: https://github.com/mozilla/node-firefox

[Loop](https://github.com/mozilla-b2g/firefoxos-loop-client/) showcases that flow using grunt. I would recommend having a build step that auto updates the nightly app package in Marketplace: https://firefox-marketplace-api.readthedocs.org/en/latest/

**Comment by fwenzel** [comment]
> zip functionality seems to be busted in cordova
Is that a bug with the Firefox OS / Cordova code? We can fix that.

**Comment by k88hudson** [comment]
@fwenzel yes I've been meaning to file in cordova's bug tracker. I think it's an issue with this package https://github.com/cthackers/adm-zip

**Comment by fwenzel** [comment]
@k88hudson please point @zalun at it when you've filed it, he should be able to help track this down

**Comment by k88hudson** [comment]
Ok, this is all done. Turns out we did not need to deploy to marketplace (for now) since the app doesn't need privileged permissions.
