### ISSUE TITLE
Implement offline state for discovery mode, sharing

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#885]
If users *start* in an offline state, they won't have access to the content in /discovery. We can do a better job at caching previous searches in the future, but for now we should at least have a better "can't connect" state for this view.

I'd love to see something that encourages to try a template instead or something similar.

**Comment by vazquez** [comment]
R? @thisandagain [flagged!]

https://redpen.io/hu048d7666fd6138e1

**Comment by thisandagain** [comment]
One small copy tweak. Otherwise R+ [[unflagged]](http://plzkthx.herokuapp.com)

**Comment by vazquez** [comment]
R? @thisandagain [flagged!]

I'm trying to add some humour in microcopy. What do you think of these?

![screenshot 2015-02-12 12 46 37](https://cloud.githubusercontent.com/assets/1119821/6173877/3292b164-b2b9-11e4-8a61-e5c4a7d16361.png)

![screenshot 2015-02-12 12 49 08](https://cloud.githubusercontent.com/assets/1119821/6173883/3fbf7e80-b2b9-11e4-9754-5848c917c227.png)

![screenshot 2015-02-12 12 45 55](https://cloud.githubusercontent.com/assets/1119821/6173884/45d063c0-b2b9-11e4-9013-c0eaedb4f7c5.png)

**Comment by vazquez** [comment]
Final design: https://redpen.io/hu048d7666fd6138e1

2 assets are needed in this view;

- WMA > GUI > Icons > arrow-fade-down.svg
- WMA > GUI > Icons > no-internet.svg

**Comment by thisandagain** [comment]
`./lib/network` needs hookup.
