### ISSUE TITLE
Implement desktop UI for published apps

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#886]
Published apps currently look strange on desktop browsers because the expand to fill the full width of the screen. We should provide a "frame" (ala Appmaker) and a call-to-action to download / install Webmaker App.

/cc @flukeout @secretrobotron

**Comment by k88hudson** [comment]
You can link to mzl.la/webmaker for now for the install page

**Comment by vazquez** [comment]
R? @thisandagain [flagged!]

https://redpen.io/maa5b6555c3c2262f1

**Comment by thisandagain** [comment]
Awesome. R+ :penguin: 
/cc @k88hudson

**Comment by vazquez** [comment]
Background asset (1x and 2x) and the device (svg) is available on Google Drive.

WMA > GUI > Desktop UI Frame

**Comment by k88hudson** [comment]
Done!
