### ISSUE TITLE
Improve font-size picking 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#887]
Changing a the font size for a text is difficult for users. They asked for : 
- a scale, or another visual way to change the size 
- no "px" => they don't understand what it means

**Comment by xmatthewx** [comment]
A slider with preview of text probably works fine. Snap to a few intervals.

![screenshot 2015-02-06 15 29 49](https://cloud.githubusercontent.com/assets/53411/6087077/0bee389c-ae15-11e4-9a67-9c6f9a0d5660.png)


Or a button group

![screenshot 2015-02-06 15 27 39](https://cloud.githubusercontent.com/assets/53411/6087080/10430b16-ae15-11e4-9bb0-d96a23249bab.png)

**Comment by thisandagain** [comment]
:+1: I'm leaning towards button group.
