### ISSUE TITLE
change the word "template"

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#888]
This word "template" does not make sense to a lot of people. 
Maybe "example" or "ideas" could work better

**Comment by tanay1337** [comment]
@LauraReynal Or "Sample" might be a choice?

**Comment by LauraReynal** [comment]
I think "sample" has a marketing connotation, and might not be understood by everyone.  

I prefer "Examples" which is pretty straight forward, and simpler. 
 It says : **"here is something you could do, but feel free to do differently"** :smile:

**Comment by xmatthewx** [comment]
Examples sounds like a good fit.

**Comment by thisandagain** [comment]
Resolved in 0518b4c1fee1274b92baebd48bfc8af480e17f15
