### ISSUE TITLE
Make page colors 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#891]
@vazquez All users loved the new design, and we can be sure this "Make Page" is no longer confusing. 
However, I got lots of comments on the colors. Too bright and flashy. Do you think we could rework the palette ?

**Comment by vazquez** [comment]
Definitely Laura. We are going to tackle this in #826

**Comment by vazquez** [comment]
Thanks for relaying the feedback!

**Comment by thisandagain** [comment]
Tracking in #826
