### ISSUE TITLE
Create a Brick for Links 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-app#896]
All users (99%)  want to be able to share links in their app. 
They want the link to be either : 
- Internal -> will link to bottom of app or up (avoiding scrolling)
- External

**Comment by thisandagain** [comment]
I'd prefer this over "drop-down". :+1:

**Comment by thisandagain** [comment]
@vazquez Mind designing an icon for this? I had one spec'd a while back but it could use a second look.

**Comment by thisandagain** [comment]
Pushing "drop-down" to the back-log.

**Comment by vazquez** [comment]
Oh yes, this will be awesome :) I'll design an icon :star:

**Comment by vazquez** [comment]
Hey @LauraReynal [flagged!] and @thisandagain [flagged!], I'm looking for some feedback.

I have 3 different explorations of this icon:

1. ![screenshot 2015-02-04 14 09 55](https://cloud.githubusercontent.com/assets/1119821/6047390/8909dc36-ac77-11e4-8921-0439c52fcd30.png)

2. ![screenshot 2015-02-04 14 10 51](https://cloud.githubusercontent.com/assets/1119821/6047421/a38c27f8-ac77-11e4-87ec-2669fba17cac.png)

3. ![screenshot 2015-02-04 14 11 27](https://cloud.githubusercontent.com/assets/1119821/6047441/bf5fdf6a-ac77-11e4-8328-74eea535c742.png)

The good things about the 3rd iteration is that it's very clear. But the bad part about it is that it only represents an external link.

***Question for everybody:*** should we have two icons? One for internal and one for external? 

This would pose 2 challenges:
-  We need to depict what an internal link icon would look like.
-  We would have to add another action in the "Add Content" screen. Is it worth it?

Maybe the first 2 iterations are sufficient. Maybe I've been looking at this screen for too long, initiating an existential icon crisis. Either way, let me know your thoughts :smile:

**Comment by thisandagain** [comment]
One observation after looking at paper prototypes created during the india research trip was that users didn't really understand the distinction between the "Submit" button and a link. We might actually want to look at merging those components and making a "link" just an alternate form of the overall "Button" component. Thoughts @vazquez @LauraReynal ?

**Comment by LauraReynal** [comment]
:+1: Agreed. 
In users mind, the button could do what they wanted: Everyone made links. No one made the call and sms buttons that we have today for example. 
BUT when they saw the call and sms buttons they loved it, so I propose to keep those.

**Comment by thisandagain** [comment]
For the sake of time / simplicity, let's go with your first option @vazquez.

**Comment by vazquez** [comment]
Icon is available on the M4D Dropbox folder: https://www.dropbox.com/s/it90gy60vs6rsbz/link.svg?dl=0

**Comment by vazquez** [comment]
Design spec of what the experience would look like once the icon is tapped.

We need a label and http URL

**Comment by vazquez** [comment]
R? @thisandagain [flagged!]

https://redpen.io/or3e84298a3ea2272d (5 screens, just keep pressing right arrow)

**Comment by thisandagain** [comment]
Great! R+

**Comment by alicoding** [comment]
@vazquez @thisandagain I've few questions here:

1. what would happen when the user click on the `www` label? 
2. Are we going to allow them to input `http://` or `https://`?

**Comment by thisandagain** [comment]
Good questions:
1. We should remove the "www." prefix from that field as it causes problems with flexibility. Instead, having a placeholder like "https://www.mozilla.org" would likely solve the problem.
2. Allow both `http` and `https`

**Comment by vazquez** [comment]
Agreed. Updated Redpen.

https://redpen.io/npe2cac1ee7dcf37e2
