### ISSUE TITLE
webmaker-app.json and mobile-appmaker.json on Transifex

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker-app#902]
I can see webmaker-app.json on Transifex.
But i can't see mobile-appmaker.json on Transifex (even thought its there because i can download it with webmaker-download-locales).

These two files seem to be exactly the same.

**Comment by k88hudson** [comment]
@alicoding any ideas why this is happening?

**Comment by alicoding** [comment]
We need to ask @jdotpz to nuke that translation folder on our server (s3) and re run the script again to make it clean and only leave it with `webmaker-app` and not `mobile-appmaker`

**Comment by thisandagain** [comment]
@alicoding @jdotpz Update? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by alicoding** [comment]
I think this is done but I will verify and close the ticket once I get home

**Comment by alicoding** [comment]
So, I just checked on our S3 bucket and I still can see `mobile-appmaker` there http://transifex.webmaker.org.s3.amazonaws.com/?prefix=mobile-appmaker/ but that being said is not going to affect us in anyway since we are now running the command using `webmaker-app` as parameter.

I'm closing this ticket.

**Comment by scootergrisen** [comment]
I still get mobile-appmaker.json when i download with:
    webmaker-download-locales "mobile-appmaker"

Why not delete the file if its not being used anymore ?

**Comment by alicoding** [comment]
Don't use mobile-appmaker?

I can't delete it myself and I remember @jdotp did it once but not sure why
it's back again...

**Comment by scootergrisen** [comment]
I dont use it, its just a bit confusing its there.
So other people might be confused to.

**Comment by alicoding** [comment]
I will make sure we remove that, but I don't know if anyone would know it's there if we don't leave a trace of the old app name :P and as long as we don't use it in the process of building our app :)
