### ISSUE TITLE
Implement new visual language in Menu

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-app#907]
This is what it looks like right now:

![editor - editi](https://cloud.githubusercontent.com/assets/1119821/6048084/dfc8aecc-ac7b-11e4-94b1-ba456a9ba94e.png)

We need to update it, as the turquoise colour is deprecated, some icons have been updated, and we generally need to make it look happier.

**Comment by vazquez** [comment]
R? @thisandagain [flagged!]

https://redpen.io/dccd679b59a724685f

**Comment by thisandagain** [comment]
Icons feel a little cramped / small in the frame, but otherwise R+

**Comment by vazquez** [comment]
Feedback adressed!

![menu](https://cloud.githubusercontent.com/assets/1119821/6064058/8a034c28-ad29-11e4-88d9-9900be997c0c.png)


Final design here: https://redpen.io/dccd679b59a724685f
Icons are available on the M4D Dropbox folder: https://www.dropbox.com/sh/kdj9si2qs07e0xc/AAAMBGIUcACX5AYL51mjsLYQa?dl=0

**Comment by thisandagain** [comment]
W00t! Thanks @vazquez. @gvn and @Pomax this is ready for implementation.
