### ISSUE TITLE
images no longer work in published app paths

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#910]
The reason is because image paths in templates are all relative, and the directory structure is different for published apps.

**Comment by k88hudson** [comment]
If you could just add something to publish/index.js that changes relative paths into absolute paths for images i.e.

in the code block that starts with `json.blocks.forEach(function (block) {`, if you look for `block.type === 'image` and `block.attributes.src.value` starting with a `images/`, add a `/` at the beginning on the URL.

**Comment by k88hudson** [comment]
@gesa does that make sense?

**Comment by gesa** [comment]
@k88hudson I think so! Can I get a gut-check on this?

```js
    if (block.type === 'image' &&
            block.attributes.src.value.match(/^images\//)) {
        block.attributes.src.value = '/' + block.attributes.src.value; 
    }
```

**Comment by k88hudson** [comment]
yep, looks good
