### ISSUE TITLE
Increase or remove maximumLineLength

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-app#913]
I keep failing JSCS because of slightly longer than 80 character lines.

I know this is here to increase readability, but we're using 4 space indentation and most Vue components start out fairly nested. It's often tough to fit everything without a bunch of tweaking. It's getting kind of irritating (and I love clean code!).

Suggest we either remove the limit or increase it to 100-120.

(If we do this, let's make sure to update the Sublime project's ruler to reflect our decision.)

**Comment by davidascher** [comment]
Agree. Found it hard to comply and write readable jsx code.

**Comment by jbuck** [comment]
I'm in favour of doing this as well
