### ISSUE TITLE
Share Via Webmaker toggle doesn't do anything

### ISSUE THREAD

**Issue by gesa** [mozilla/webmaker-app#921]
Re this control: (on /make/:id/share)
![](http://snaps.akibraun.com/nitw5.png)

Toggling to the `true` position does give me *visual* confirmation that a make is shared, but upon reloading the page, the toggle is set to the `false` position.

**Comment by k88hudson** [comment]
Resolved by https://github.com/mozilla/webmaker-app/commit/18688cd1807eaf7e67991979315bb96708ea029c

**Comment by k88hudson** [comment]
Oh crap. totally wrong ticket oops
