### ISSUE TITLE
UX Review

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#932]
Reviewed on Android 4.4.4 
Tested as App. Also using mobile Chrome and FF as reference.

@k88hudson - I can file individual bugs. Or, you can let me know which are useful or dupes etc. 

 - [x] `UX` - **Start Building** - Wondering if we need a label above the example preview. Or maybe the button says _Build This Example_

 - [x] `UX` `Enhancement` - **brick selector cancel flow** - Playing with this, I'd like to click a brick in the brick selector, view the edit options, and then cancel to return to the selector (rather than the app). This would require a cancel button in the selector. This is more intuitive and conducive to learning and experimentation.

 - [x] `UX` `Enhancement` - **brick tips** - The brick editor could include a few word tip/explanation at the top. What does SMS brick do? Not too obvious, even for longterm users of apps and the web. Edit screen could say above the Label something like below. We could show this when adding new bricks only, but I think it'd be fine to always display. 
    - "An SMS button triggers a new message to the number you enter below." 
    - "Use a text box to get info from people who use your app." 

 - [x] `UX` - **Scroll-to** 
   - When I edit text, would be great if textarea scrolls to top as keyboard appears
   - When I click pencil on a brick, would be great if it scrolled to center of the screen before toolbar appears. (FF seems to pull it into viewport. In Android app, it can remain partially outside viewport.)
   - When I duplicate a brick, new brick should scroll into view if below viewport
 
 - [x] `UX` - **Move brick** - When I move a brick up or down, keep it in brick-toolbar mode. Otherwise, it's would be annoying to move it far. 

 - [x] `UX` - **Close brick-toolbar** - Wondering if click-outside-to-cancel is obvious enough. Might add an (×) in top right corner, half in box, half above. 

 - [x] `UX` - **Submit Button** - Can I have more than one? Is a text box or counter useful without it? Can we just insert one when adding an input brick? People could move button, but not edit or duplicate it. No need to have it it on the selector screen. 

 - [x] `UX` - **Add a Brick** - ~~Not sure the plus sign in the top corner is an improvement on the previous solution. We might try a floating add button on top right of app body.~~ [ @vazquez has already designed something nicer ]

 - [x] `UX` - **Text Box editor** -  Title should come first as the only required item (before color and type).
 
 - [x] `Enhancement` - **Color picker** - It's not immediately clear that the lower section are based on the upper, especially when a template doesn't use these defaults. Might shift background color on lower section or put a down caret instead of a line between the top and bottom. 

 - [x] `Enhancement` - **Example App use of Separators** - Ricardo's example apps are beautiful. Use of separators should be more contrasty for usability at the expense of aesthetics. Accidentally, the first pencil I always clicked was for a separator I couldn't see. I thought it was a blank text box or a broken brick. 

 cc @thisandagain

**Comment by thisandagain** [comment]
This would be more helpful as individual tickets. The only one that I see a dupe for is "Close brick-toolbar".

**Comment by xmatthewx** [comment]
Sure thing. These are smaller issues dumped here for speedy review. I can refile individually on Monday. Feel free to assign it to me.

**Comment by thisandagain** [comment]
Awesome. Thanks times :100: @xmatthewx

**Comment by k88hudson** [comment]
++ thanks Matthew :dancer:

**Comment by xmatthewx** [comment]
Scroll-to on edit

Certain editing moments put relevant details outside of view. 

   - When I edit text, would be great if textarea scrolls to top as keyboard appears
   - When I click pencil on a brick, would be great if it scrolled to center of the screen before toolbar appears. (FF seems to pull it into viewport. In Android app, it can remain partially outside viewport.)
   - When I duplicate a brick, new brick should scroll into view if below viewport

**Comment by xmatthewx** [comment]
issues filed
