### ISSUE TITLE
Scrollbars on embedded example

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#933]
Android 4.4.4

Scrollbars appear unnecessarily in Build > Promote Biz > Embedded example

![screenshot_2015-02-06-16-57-29](https://cloud.githubusercontent.com/assets/53411/6088565/dcc9b8f0-ae25-11e4-9af4-40ed5f299faf.png)

**Comment by thisandagain** [comment]
Tracking in #931
