### ISSUE TITLE
Edit Title - Cancel is only option

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#935]
Android 4.4.4 

Click pencil to edit title. On the next view, `Cancel` is the only way out. It saves rather than cancels changes. There is no Save button. 

Also, it's slightly jarring to see all the colors and icon when I thought I was only going to edit the app name. But, that's a bigger design task than the bug above.

![screenshot 2015-02-06 17 38 44](https://cloud.githubusercontent.com/assets/53411/6088697/2e3be68a-ae27-11e4-8962-7191e4e5ad6a.png)

**Comment by thisandagain** [comment]
Related to discussions in:
https://github.com/mozilla/webmaker-app/issues/810
https://github.com/mozilla/webmaker-app/issues/834

**Comment by Pomax** [comment]
Simpest fix is we replace "Cancel", which is not what's happening, with "Back", which would be in line with what actually happens.

**Comment by Pomax** [comment]
building solution on top of the work for https://github.com/mozilla/webmaker-app/issues/834 and https://github.com/mozilla/webmaker-app/issues/1022

**Comment by Pomax** [comment]
solved via #1022 and #1024
