### ISSUE TITLE
Validate Counter brick settings

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#936]
Counter seems to allow a Min larger than Max. Initial number should fall within the range.

**Comment by JordanTheriault** [comment]
I will take this one on @thisandagain

**Comment by simonwex** [comment]
@JordanTheriault, that'd be great! Let me know if you run into any problems.

**Comment by JordanTheriault** [comment]
@simonwex I have it giving an error to the user, but they will still be able to save it. However, the counter does not work if the error exists. Is this suitable to close this issue? The comments mention we should not yet disable to the save feature if errors exist. [Branch here.](https://github.com/JordanTheriault/webmaker-app/commit/019f15db35b1c731466b339422b667b00d6650a3)

**Comment by xmatthewx** [comment]
Thanks @JordanTheriault for digging into this. I'm betting this is probably good for now, but I defer to the engineers. If you submit your pull request, the discussion and review can continue there.
