### ISSUE TITLE
Improve brick editor view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#939]
Brick editor views could use a few easy improvements. 

 - [ ] 1. Required Titles should come first
 - [ ] 2. Text color should come after more important settings

Enhancement -  As mentioned in #932, editor could include a few word explanation at the top. Seasoned app users probably couldn't guess what an SMS brick does. We could show this when adding new bricks only, but I think it'd be fine to always display.

## SMS
![screenshot 2015-02-06 18 02 40](https://cloud.githubusercontent.com/assets/53411/6089022/8b79a30c-ae2a-11e4-83f4-af02ec678755.png)

## Text Box
![screenshot 2015-02-06 18 04 58](https://cloud.githubusercontent.com/assets/53411/6089036/b7f0d48c-ae2a-11e4-91ba-b1697f163db2.png)

## Current View
![screenshot 2015-02-06 17 42 17](https://cloud.githubusercontent.com/assets/53411/6088772/1b4fdd0a-ae28-11e4-9d7d-6fa2fd4d4c9a.png)

**Comment by thisandagain** [comment]
I really like this short description idea. :+1:
