### ISSUE TITLE
icon picker fetches icons on demand, making for delays

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#942]
STR:
 - install the app
 - use the blogger template
 - tap on the title
 - hit right arrow next to the large icon

-> delay while the next icon is being fetched, with a blank green disc.

I'm assuming this is a network latency. We should not need any network connectivity while remixing, only when publishing

**Comment by Pomax** [comment]
I get a small delay while the image is switched over to the next on android 4.2 with wifi disabled, but not long enough to "see" an empty disc. Is this still an issue on current master?

**Comment by Pomax** [comment]
fixed on current master
