### ISSUE TITLE
color scheme on sidebar feels off

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#943]
I'm not sure why, but the two blues in this sidebar feel like they clash to me.

![2015-02-06 23 11 30](https://cloud.githubusercontent.com/assets/51278/6089188/b8c47ca4-ae13-11e4-8a1e-9c8655639eb1.png)

**Comment by thisandagain** [comment]
Because they do! :stuck_out_tongue_winking_eye:  

We have an updated design here: https://redpen.io/dccd679b59a724685f
@vazquez do we have a ticket for this that I'm missing?

**Comment by thisandagain** [comment]
Missed because it just closed! :boom: 
https://github.com/mozilla/webmaker-app/issues/907#event-231826825
