### ISSUE TITLE
Publish button/link in header should be further towards the edge

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#944]
![2015-02-06 23 14 00](https://cloud.githubusercontent.com/assets/51278/6089199/e0501440-ae13-11e4-97f0-3deb19d609b7.png)

It currently clusters with the title/pencil grouping.  Right padding should be the same as the left padding on the hamburger.

**Comment by k88hudson** [comment]
True, although Publish button is being removed, so im gonna close this one
