### ISSUE TITLE
Unified Nav

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#945]
The current bottom nav doesn't with mesh with the newer design aesthetically. UX-wise, it's disjointed with the improved editor hamburger navigation. 

I recommend a unified hamburger nav
 - Delete and Share labels should be more explicit: Delete App or Delete this App
 - Probably not all left carets :smile:

![screenshot 2015-02-06 18 09 38](https://cloud.githubusercontent.com/assets/53411/6089181/b78720bc-ae2c-11e4-942e-3d9d24441c24.png)

![screenshot 2015-02-06 18 12 14](https://cloud.githubusercontent.com/assets/53411/6089172/8c40edc0-ae2c-11e4-9dfe-daf4896a5270.png)

 - Current active item in bottom nav doesn't have much contrast with other items.

**Comment by thisandagain** [comment]
Really solid feedback. Agreed. Adding to backlog for now, but would like to address prior to MWC.

**Comment by vazquez** [comment]
We are getting rid of the hamburger menu; this issue is deprecated. This is being tracked in #1179. Closing issue.
