### ISSUE TITLE
pencil icon in editor should align with baseline of text, not descenders

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#946]
See e.g.

![2015-02-06 23 14 00](https://cloud.githubusercontent.com/assets/51278/6089205/1464f138-ae14-11e4-81f9-397ed2b33619.png)

**Comment by thisandagain** [comment]
Yessss. Good eye. :ok_hand:

**Comment by k88hudson** [comment]
hard to do considering text is of variable size though :(

**Comment by k88hudson** [comment]
also :heart: for the use of technical typographical terms
