### ISSUE TITLE
Switching tabs in editors should result in some transition on the main page

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#948]
There's a sharp toggle between Preview and Edit modes which the user can kinda understand, although it could be made smoother.

There's a complete page refresh between Preview/Edit and Data which is quite abrupt.  We could have the data pane slide in from the right for example, or flip in 3d, or …

We currently do nothing with edge swipes.  Maybe doing using left-right edge swipes to switch between modes would work?

**Comment by thisandagain** [comment]
Resolved by https://github.com/mozilla/webmaker-app/pull/937
