### ISSUE TITLE
Produce content for Discover gallery

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-app#949]
@k88hudson just showed me the explore section of webmaker app, but the "featured" section is empty. It's easy to flip on some flags in the firebase db, but we need to choose some apps that deserve to be on that page.

@thisandagain what do you think?

**Comment by thisandagain** [comment]
Yup... good thing to call out as a specific task.

**Comment by davidascher** [comment]
For MWC deliverable, important for the demoers to understand the long term
plan in particular w.r.t. how we foresee doing so on a language or
geography basis (realizing that that feature isn't going to be ready by
then)

**Comment by secretrobotron** [comment]
From a meeting with @thisandagain 
- Try to get 15 apps
- From 5-10 community members
- Apps that community just wants to see & use -- funny, interesting, sharable
- Use local language if possible
- Try to have things started this week, shoot for demos at end-of-heartbeat
- webmaker apps github issues, if they're interested and see or need to file bugs

**Comment by k88hudson** [comment]
Sounds good to me :+1:

**Comment by secretrobotron** [comment]
Appeals sent out to community lists and on twitter at the advice of the teach/community team. Have a couple of people to help out, waiting for more.

:octopus:

**Comment by secretrobotron** [comment]
Got 15 keen responses. Emailed today to engage. When app build and QA script are done today, I'll send out more instructions.

**Comment by k88hudson** [comment]
Awesome, thanks!

**Comment by secretrobotron** [comment]
Couple coming in now. Working with contributors to make more/better:
* https://apps.mofostaging.net/p/-JiwMaBWYWlLlre-5VhJ/
* https://apps.mofostaging.net/p/-Jit2JqblVRBaZJldgyN/
