### ISSUE TITLE
down state on the edit pencil is weird

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#952]
a) I somehow got an orange focus ring

![2015-02-07 00 25 59](https://cloud.githubusercontent.com/assets/51278/6089778/1bfe1790-ae1d-11e4-98f9-478bdeaf4dcc.png)

b) the down state highlight is square on a circular button, that's weird.  
c) somehow the blue highlight is on a pencil that isn't the one my finger's on (which is the orange-highligted one)

![2015-02-07 00 26 03](https://cloud.githubusercontent.com/assets/51278/6089779/2394ca62-ae1d-11e4-978b-108ecef10f7b.png)

**Comment by thisandagain** [comment]
@gesa I'm not sure if this is still an issue, but we should confirm.

**Comment by gesa** [comment]
I can't reproduce *in browser* on Android, FFOS, or firefox. I'll recheck tomorrow when I compile for the first time!

**Comment by gesa** [comment]
Okay false alarm, not compiling until Monday.

@davidascher Are you still able to reproduce this bug?

**Comment by thisandagain** [comment]
Not able to reproduce.
