### ISSUE TITLE
sidebar doesn't need a title

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#953]
or if it has a title, it shouldn't be 'menu', which is an analogy that belongs with the floppy drive, in the trash can, by the side of the desktop.

![2015-02-07 00 28 57](https://cloud.githubusercontent.com/assets/51278/6089808/74505386-ae1d-11e4-9d56-3cf49035cfea.png)

**Comment by vazquez** [comment]
Deprecated. We no longer have a double cheeseburger. Closing issue.
