### ISSUE TITLE
Label embedded example 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#955]
Wondering if we need a label above the example preview to give more context to the view. 

![screenshot 2015-02-08 19 56 19](https://cloud.githubusercontent.com/assets/53411/6099682/e192862a-afcc-11e4-8799-d62b702ac3f5.png)

**Comment by vazquez** [comment]
We are adding a "Preview" label above the app preview. Tracking in #1076. Closing this issue.
