### ISSUE TITLE
Move brick behavior 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-app#958]
When I move a brick up or down, might be better to keep it in brick+toolbar mode. Otherwise, it's would be annoying to move it far. For a good experience,  I think this requires the (x) to close the toolbar. 

This is a minor issue, open for debate.

**Comment by gvn** [comment]
This is actually going to be somewhat complicated so I'd like to push it to a later sprint.

Also, if we do it we should probably make the shim less opaque.
