### ISSUE TITLE
When starting in an offline state, discovery view never loads

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-app#963]
When starting in an offline state, the /discovery view never loads even if you go back online

**Comment by gesa** [comment]
When setting `offline=true` in any and all config files I can find, I can't reproduce this bug. Is there a way to force offline mode that I'm missing? Or has this been resolved?

**Comment by thisandagain** [comment]
Unable to reproduce in Firefox OS 2.0 and Android 4.4 / 5.0
