### ISSUE TITLE
Submit updated locale file to Transifex aka "String Freeze"

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-app#987]
We need to freeze strings at the end of this sprint and submit the updated locale file to Transifex prior to MWC.

**Comment by alicoding** [comment]
@thisandagain so strings freeze on the repo meaning no more string to be add here and then we upload on Transifex and let people do the translation, correct? Also, we should do strings freeze on Transifex for Webmaker App as well. Meaning they shouldn't be changing anything else after certain date, so we need to ask them to fully review them and then we lock the file.

**Comment by alicoding** [comment]
@gvn @thisandagain @Pomax @gesa @k88hudson is there any ticket that you guys are working on will add new string to the file? if not I want to upload this and declare a **String Freeze** state
![mr_freeze_ arnold_schwarzenegger _2](https://cloud.githubusercontent.com/assets/4368149/6191903/2a3f2688-b37b-11e4-9d69-daa9cd22ecfb.gif)

**Comment by thisandagain** [comment]
Doesn't look like we have anything! :smile: :icecream: :snowflake: :snowman:

**Comment by alicoding** [comment]
Then we shall begin! No more new string added. @Pomax @thisandagain @simonwex @k88hudson @gvn @gesa
